-- =====================================================================
-- R1-P 095 - PER-SIGNATURE ACL DISPOSITION VERIFIER (clone only)
-- Generated by db/r1/p/build_acl25.py from the frozen acl-25.json.
-- One test per baseline signature: after 002_public_contract.sql the recorded
-- disposition must hold (revoke_anon_public => no anon EXECUTE, no PUBLIC
-- EXECUTE). Named helpers must additionally stay callable for the intended
-- caller (authenticated + service_role).
-- Production is never touched by this file.
-- =====================================================================
CREATE SCHEMA IF NOT EXISTS t;
DO $BODY$
DECLARE r record; v_oid oid; v_anon boolean; v_pub boolean;
BEGIN
FOR r IN SELECT * FROM (VALUES
  (1,$$public.admin_apply_fix_proposal(p_id uuid, p_confirm boolean)$$,$$revoke_anon_public$$,$$T-P98b.01$$,false),
  (2,$$public.admin_delete_trade_records_by_signal_ids(_signal_ids uuid[])$$,$$revoke_anon_public$$,$$T-P98b.02$$,false),
  (3,$$public.admin_delete_trade_records_by_symbol(_expert_id uuid, _symbol_prefix text)$$,$$revoke_anon_public$$,$$T-P98b.03$$,false),
  (4,$$public.admin_generate_fix_proposals(p_category text)$$,$$revoke_anon_public$$,$$T-P98b.04$$,false),
  (5,$$public.admin_holdings_consistency_audit()$$,$$revoke_anon_public$$,$$T-P98b.05$$,false),
  (6,$$public.admin_list_cron_jobs()$$,$$revoke_anon_public$$,$$T-P98b.06$$,false),
  (7,$$public.admin_reject_fix_proposal(p_id uuid, p_note text)$$,$$revoke_anon_public$$,$$T-P98b.07$$,false),
  (8,$$public.admin_reset_expert_asset_class(_expert_id uuid, _new_asset_class text)$$,$$revoke_anon_public$$,$$T-P98b.08$$,false),
  (9,$$public.admin_trade_dedupe_sweep(p_dry_run boolean)$$,$$revoke_anon_public$$,$$T-P98b.09$$,false),
  (10,$$public.backfill_job_set_done(_id bigint, _status text)$$,$$revoke_anon_public$$,$$T-P98b.10$$,false),
  (11,$$public.backfill_job_set_failed(_id bigint, _error text, _retry_at timestamp with time zone)$$,$$revoke_anon_public$$,$$T-P98b.11$$,false),
  (12,$$public.backfill_legacy_bsr_to_fact(_from date, _to date)$$,$$revoke_anon_public$$,$$T-P98b.12$$,false),
  (13,$$public.backfill_queue_stats()$$,$$revoke_anon_public$$,$$T-P98b.13$$,false),
  (14,$$public.claim_backfill_jobs(_batch_size integer, _max_priority_score integer)$$,$$revoke_anon_public$$,$$T-P98b.14$$,false),
  (15,$$public.enqueue_backfill_jobs(_jobs jsonb)$$,$$revoke_anon_public$$,$$T-P98b.15$$,false),
  (16,$$public.enqueue_bsr_backfill(p_stock_id text, p_days integer)$$,$$revoke_anon_public$$,$$T-P98b.16$$,false),
  (17,$$public.enqueue_institutional_backfill_universe()$$,$$revoke_anon_public$$,$$T-P98b.17$$,false),
  (18,$$public.get_expert_capital_status(_expert_id uuid)$$,$$revoke_anon_public$$,$$T-P98a.18$$,true),
  (19,$$public.get_publish_batch_attempts(_limit integer)$$,$$revoke_anon_public$$,$$T-P98b.19$$,false),
  (20,$$public.get_publish_batch_runs(_limit integer)$$,$$revoke_anon_public$$,$$T-P98b.20$$,false),
  (21,$$public.get_publish_batch_status()$$,$$revoke_anon_public$$,$$T-P98b.21$$,false),
  (22,$$public.has_active_subscription_after(_user_id uuid, _published_at timestamp with time zone)$$,$$revoke_anon_public$$,$$T-P98a.22$$,true),
  (23,$$public.is_tester(_user_id uuid)$$,$$revoke_anon_public$$,$$T-P98a.23$$,true),
  (24,$$public.prune_backfill_job_queue()$$,$$revoke_anon_public$$,$$T-P98b.24$$,false),
  (25,$$public.publish_batch_attempts_touch()$$,$$revoke_anon_public$$,$$T-P98b.25$$,false),
  (26,$$public.recover_stale_backfill_jobs(_stale_after interval)$$,$$revoke_anon_public$$,$$T-P98b.26$$,false),
  (27,$$public.tg_holdings_fix_proposals_updated_at()$$,$$revoke_anon_public$$,$$T-P98b.27$$,false),
  (28,$$public.trade_dedupe_sweep(p_dry_run boolean)$$,$$revoke_anon_public$$,$$T-P98b.28$$,false)
) AS v(n, sig, disposition, test_id, is_named) LOOP
  SELECT p.oid INTO v_oid FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE format('%I.%I(%s)', n.nspname, p.proname,
                pg_get_function_identity_arguments(p.oid)) = r.sig;
  IF v_oid IS NULL THEN
    PERFORM t.ok(r.test_id || ' ' || r.sig || ' [signature absent in clone]', false,
                 'not found in pg_proc');
    CONTINUE;
  END IF;
  v_anon := has_function_privilege('anon', v_oid, 'EXECUTE');
  v_pub  := EXISTS (
     SELECT 1 FROM pg_proc pp,
       LATERAL aclexplode(coalesce(pp.proacl, acldefault('f', pp.proowner))) a
      WHERE pp.oid = v_oid AND a.grantee = 0 AND a.privilege_type = 'EXECUTE');
  PERFORM t.ok(r.test_id || ' ' || r.sig || ' -> ' || r.disposition,
               (NOT v_anon) AND (NOT v_pub),
               format('anon_execute=%s public_execute=%s', v_anon, v_pub));
  IF r.is_named THEN
    PERFORM t.ok(r.test_id || 'i intended caller keeps EXECUTE: ' || r.sig,
      has_function_privilege('authenticated', v_oid, 'EXECUTE')
      AND has_function_privilege('service_role', v_oid, 'EXECUTE'));
  END IF;
END LOOP;
END $BODY$;

DO $BODY$
DECLARE v_count int;
BEGIN
  SELECT count(*)::int INTO v_count FROM t.result
   WHERE name LIKE ('T-P98a.' || '%') OR name LIKE ('T-P98b.' || '%');
  PERFORM t.eq('T-P98d acl-25 coverage: every frozen baseline signature verified',
               v_count, 31);
END $BODY$;
