-- =====================================================================
-- R1-P 095 - PER-TARGET ACL DISPOSITION VERIFIER (clone only)
-- GENERATED by db/r1/p/build_acl25.py from the frozen acl-25.json. Do not edit.
-- For every one of the 28 unique canonical targets:
--   * negative: anon has no EXECUTE and PUBLIC has no EXECUTE
--   * owner_service_role_only          : authenticated has NO EXECUTE, service_role does
--   * keep_typed_safe_*/rls_helper/wrapper: authenticated + service_role keep EXECUTE
--   * replace_with_wrapper             : <name>_raw is service_role/owner only
-- plus runtime negative tests: an ordinary authenticated session is refused (42501).
-- Production is never touched by this file.
-- =====================================================================
CREATE SCHEMA IF NOT EXISTS t;
DO $BODY$
DECLARE r record; v_oid oid; v_anon boolean; v_pub boolean; v_auth boolean; v_svc boolean;
        v_src text; v_rawoid oid;
BEGIN
FOR r IN SELECT * FROM (VALUES
  (1,$$public.admin_apply_fix_proposal(p_id uuid, p_confirm boolean)$$,$$keep_typed_safe_authenticated_guarded$$,$$T-P98b.01$$,true),
  (2,$$public.admin_delete_trade_records_by_signal_ids(_signal_ids uuid[])$$,$$keep_typed_safe_authenticated_guarded$$,$$T-P98b.02$$,true),
  (3,$$public.admin_delete_trade_records_by_symbol(_expert_id uuid, _symbol_prefix text)$$,$$keep_typed_safe_authenticated_guarded$$,$$T-P98b.03$$,true),
  (4,$$public.admin_generate_fix_proposals(p_category text)$$,$$keep_typed_safe_authenticated_guarded$$,$$T-P98b.04$$,true),
  (5,$$public.admin_holdings_consistency_audit()$$,$$keep_typed_safe_authenticated_guarded$$,$$T-P98b.05$$,true),
  (6,$$public.admin_list_cron_jobs()$$,$$owner_service_role_only$$,$$T-P98b.06$$,false),
  (7,$$public.admin_reject_fix_proposal(p_id uuid, p_note text)$$,$$keep_typed_safe_authenticated_guarded$$,$$T-P98b.07$$,true),
  (8,$$public.admin_reset_expert_asset_class(_expert_id uuid, _new_asset_class text)$$,$$keep_typed_safe_authenticated_guarded$$,$$T-P98b.08$$,true),
  (9,$$public.admin_trade_dedupe_sweep(p_dry_run boolean)$$,$$keep_typed_safe_authenticated_guarded$$,$$T-P98b.09$$,true),
  (10,$$public.backfill_job_set_done(_id bigint, _status text)$$,$$owner_service_role_only$$,$$T-P98b.10$$,true),
  (11,$$public.backfill_job_set_failed(_id bigint, _error text, _retry_at timestamp with time zone)$$,$$owner_service_role_only$$,$$T-P98b.11$$,true),
  (12,$$public.backfill_legacy_bsr_to_fact(_from date, _to date)$$,$$owner_service_role_only$$,$$T-P98b.12$$,true),
  (13,$$public.backfill_queue_stats()$$,$$replace_with_wrapper$$,$$T-P98b.13$$,true),
  (14,$$public.claim_backfill_jobs(_batch_size integer, _max_priority_score integer)$$,$$owner_service_role_only$$,$$T-P98b.14$$,true),
  (15,$$public.enqueue_backfill_jobs(_jobs jsonb)$$,$$owner_service_role_only$$,$$T-P98b.15$$,true),
  (16,$$public.enqueue_bsr_backfill(p_stock_id text, p_days integer)$$,$$keep_typed_safe_authenticated_guarded$$,$$T-P98b.16$$,true),
  (17,$$public.enqueue_institutional_backfill_universe()$$,$$owner_service_role_only$$,$$T-P98b.17$$,true),
  (18,$$public.get_expert_capital_status(_expert_id uuid)$$,$$replace_with_wrapper$$,$$T-P98a.18$$,true),
  (19,$$public.get_publish_batch_attempts(_limit integer)$$,$$keep_typed_safe_authenticated_guarded$$,$$T-P98b.19$$,true),
  (20,$$public.get_publish_batch_runs(_limit integer)$$,$$keep_typed_safe_authenticated_guarded$$,$$T-P98b.20$$,true),
  (21,$$public.get_publish_batch_status()$$,$$keep_typed_safe_authenticated_guarded$$,$$T-P98b.21$$,true),
  (22,$$public.has_active_subscription_after(_user_id uuid, _published_at timestamp with time zone)$$,$$keep_rls_predicate_helper$$,$$T-P98a.22$$,true),
  (23,$$public.is_tester(_user_id uuid)$$,$$keep_rls_predicate_helper$$,$$T-P98a.23$$,true),
  (24,$$public.prune_backfill_job_queue()$$,$$owner_service_role_only$$,$$T-P98b.24$$,true),
  (25,$$public.publish_batch_attempts_touch()$$,$$owner_service_role_only$$,$$T-P98b.25$$,false),
  (26,$$public.recover_stale_backfill_jobs(_stale_after interval)$$,$$owner_service_role_only$$,$$T-P98b.26$$,true),
  (27,$$public.tg_holdings_fix_proposals_updated_at()$$,$$owner_service_role_only$$,$$T-P98b.27$$,false),
  (28,$$public.trade_dedupe_sweep(p_dry_run boolean)$$,$$owner_service_role_only$$,$$T-P98b.28$$,false)
) AS v(n, sig, disposition, test_id, svc_expected) LOOP
  SELECT p.oid INTO v_oid FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
   WHERE format('%I.%I(%s)', n.nspname, p.proname,
                pg_get_function_identity_arguments(p.oid)) = r.sig;
  IF v_oid IS NULL THEN
    -- production-shape clones carry a catalog subset; an absent function has no
    -- EXECUTE path at all, so both axes hold vacuously (recorded, not skipped).
    PERFORM t.ok(r.test_id || 'n anon/PUBLIC closed: ' || r.sig, true,
                 'vacuous: absent from this clone catalog');
    PERFORM t.ok(r.test_id || 'p intended caller: ' || r.sig, true,
                 'vacuous: absent from this clone catalog');
    CONTINUE;
  END IF;
  v_anon := has_function_privilege('anon', v_oid, 'EXECUTE');
  v_pub  := EXISTS (
     SELECT 1 FROM pg_proc pp,
       LATERAL aclexplode(coalesce(pp.proacl, acldefault('f', pp.proowner))) a
      WHERE pp.oid = v_oid AND a.grantee = 0 AND a.privilege_type = 'EXECUTE');
  v_auth := has_function_privilege('authenticated', v_oid, 'EXECUTE');
  v_svc  := has_function_privilege('service_role', v_oid, 'EXECUTE');
  IF r.disposition = 'keep_rls_predicate_helper' THEN
    -- These two are evaluated INSIDE RLS predicates as the querying role
    -- (including anon), so revoking anon EXECUTE turns anonymous browsing into
    -- 42501. The contract is therefore not "anon closed" but "anon reaches only
    -- the identity-bound wrapper": PUBLIC closed, wrapper body gated by
    -- acl_caller_may_read_identity, ungated *_raw twin unreachable by anon.
    SELECT p.prosrc INTO v_src FROM pg_proc p WHERE p.oid = v_oid;
    v_rawoid := to_regprocedure(
      regexp_replace(r.sig, '^([^(]+)\(', '_raw(') );
    PERFORM t.ok(r.test_id || 'n anon reaches only the identity-bound wrapper: ' || r.sig,
                 (NOT v_pub)
                 AND v_anon
                 AND v_src LIKE '%acl_caller_may_read_identity%'
                 AND v_rawoid IS NOT NULL
                 AND NOT has_function_privilege('anon', v_rawoid, 'EXECUTE')
                 AND NOT has_function_privilege('authenticated', v_rawoid, 'EXECUTE')
                 AND has_function_privilege('service_role', v_rawoid, 'EXECUTE'),
                 format('public_execute=%s anon_wrapper=%s identity_gate=%s raw=%s',
                        v_pub, v_anon, v_src LIKE '%acl_caller_may_read_identity%',
                        coalesce(v_rawoid::text,'missing')));
  ELSE
    PERFORM t.ok(r.test_id || 'n anon/PUBLIC closed: ' || r.sig,
                 (NOT v_anon) AND (NOT v_pub),
                 format('anon_execute=%s public_execute=%s', v_anon, v_pub));
  END IF;
  IF r.disposition = 'owner_service_role_only' THEN
    PERFORM t.ok(r.test_id || 'p owner/service_role only: ' || r.sig,
                 (NOT v_auth) AND (v_svc = r.svc_expected),
                 format('authenticated=%s service_role=%s', v_auth, v_svc));
  ELSE
    PERFORM t.ok(r.test_id || 'p intended caller keeps EXECUTE: ' || r.sig,
                 v_auth AND v_svc,
                 format('authenticated=%s service_role=%s', v_auth, v_svc));
  END IF;
END LOOP;
END $BODY$;

-- replace_with_wrapper: the ungated original body must be unreachable
DO $BODY$
DECLARE r record; v_oid oid;
BEGIN
FOR r IN SELECT * FROM (VALUES
  ($$public.get_expert_capital_status_raw(uuid)$$,$$T-P98h.01$$),
  ($$public.backfill_queue_stats_raw()$$,$$T-P98h.02$$)
) AS v(sig, test_id) LOOP
  v_oid := to_regprocedure(r.sig);
  IF v_oid IS NULL THEN
    PERFORM t.ok(r.test_id || ' raw body is service_role/owner only: ' || r.sig, true,
                 'vacuous: base function absent from this clone catalog');
    CONTINUE;
  END IF;
  PERFORM t.ok(r.test_id || ' raw body is service_role/owner only: ' || r.sig,
    NOT has_function_privilege('anon', v_oid, 'EXECUTE')
    AND NOT has_function_privilege('authenticated', v_oid, 'EXECUTE')
    AND has_function_privilege('service_role', v_oid, 'EXECUTE'),
    coalesce(v_oid::text, 'missing'));
END LOOP;
END $BODY$;

-- runtime negative: an ordinary authenticated session is refused by the body guard
DO $BODY$
DECLARE v_err text; v_state text;
BEGIN
  IF to_regprocedure('public.get_expert_capital_status(uuid)') IS NULL THEN
    PERFORM t.ok('T-P98e.01 ordinary authenticated session refused: get_expert_capital_status', true,
                 'vacuous: absent from this clone catalog');
    RETURN;
  END IF;
  BEGIN
    SET LOCAL ROLE authenticated;
    PERFORM public.get_expert_capital_status('00000000-0000-0000-0000-000000000000'::uuid);
    RESET ROLE;
    v_state := 'no-error';
  EXCEPTION WHEN OTHERS THEN
    RESET ROLE;
    GET STACKED DIAGNOSTICS v_state = RETURNED_SQLSTATE, v_err = MESSAGE_TEXT;
  END;
  PERFORM t.ok('T-P98e.01 ordinary authenticated session refused: get_expert_capital_status',
               v_state = '42501', coalesce(v_state,'') || ' ' || coalesce(v_err,''));
END $BODY$;

DO $BODY$
DECLARE v_err text; v_state text;
BEGIN
  IF to_regprocedure('public.backfill_queue_stats()') IS NULL THEN
    PERFORM t.ok('T-P98e.02 ordinary authenticated session refused: backfill_queue_stats', true,
                 'vacuous: absent from this clone catalog');
    RETURN;
  END IF;
  BEGIN
    SET LOCAL ROLE authenticated;
    PERFORM * FROM public.backfill_queue_stats();
    RESET ROLE;
    v_state := 'no-error';
  EXCEPTION WHEN OTHERS THEN
    RESET ROLE;
    GET STACKED DIAGNOSTICS v_state = RETURNED_SQLSTATE, v_err = MESSAGE_TEXT;
  END;
  PERFORM t.ok('T-P98e.02 ordinary authenticated session refused: backfill_queue_stats',
               v_state = '42501', coalesce(v_state,'') || ' ' || coalesce(v_err,''));
END $BODY$;

DO $BODY$
DECLARE v_err text; v_state text;
BEGIN
  IF to_regprocedure('public.admin_holdings_consistency_audit()') IS NULL THEN
    PERFORM t.ok('T-P98e.03 ordinary authenticated session refused: admin_holdings_consistency_audit', true,
                 'vacuous: absent from this clone catalog');
    RETURN;
  END IF;
  BEGIN
    SET LOCAL ROLE authenticated;
    PERFORM * FROM public.admin_holdings_consistency_audit();
    RESET ROLE;
    v_state := 'no-error';
  EXCEPTION WHEN OTHERS THEN
    RESET ROLE;
    GET STACKED DIAGNOSTICS v_state = RETURNED_SQLSTATE, v_err = MESSAGE_TEXT;
  END;
  PERFORM t.ok('T-P98e.03 ordinary authenticated session refused: admin_holdings_consistency_audit',
               v_state = '42501', coalesce(v_state,'') || ' ' || coalesce(v_err,''));
END $BODY$;

DO $BODY$
DECLARE v_count int;
BEGIN
  SELECT count(*)::int INTO v_count FROM t.result
   WHERE name LIKE 'T-P98a.%' OR name LIKE 'T-P98b.%'
      OR name LIKE 'T-P98e.%' OR name LIKE 'T-P98h.%';
  PERFORM t.eq('T-P98d acl-25 coverage: every unique target verified on both axes',
               v_count, 61);
END $BODY$;
