project_id = "yqacmrgdjlenbijclngi"

[functions.stock-quote]
verify_jwt = false

[functions.create-analyst]
verify_jwt = false

[functions.daily-performance]
verify_jwt = false

[functions.line-push-signal]
verify_jwt = false

[functions.line-webhook]
verify_jwt = false