project_id = "yqacmrgdjlenbijclngi"

[functions.create-analyst]
verify_jwt = false

[functions.daily-performance]
verify_jwt = false

[functions.line-push-signal]
verify_jwt = false

[functions.line-webhook]
verify_jwt = false

[functions.create-linepay-order]
verify_jwt = false

[functions.confirm-linepay]
verify_jwt = false

[functions.create-ecpay-order]
verify_jwt = false

[functions.ecpay-callback]
verify_jwt = false

[functions.twse-proxy]
verify_jwt = false

[functions.line-push-renewal-reminder]
verify_jwt = false

[functions.create-acpay-order]
verify_jwt = false

[functions.acpay-callback]
verify_jwt = false

[functions.confirm-acpay]
verify_jwt = false

[functions.data-upsert]
verify_jwt = false
