#!/usr/bin/env python3
"""R1-B: read-only catalog extraction of the economic object subset into replayable DDL.
No pg_dump, no data. Emits db/r1/clone/schema.sql"""
import subprocess, os

TABLES = ['experts','expert_plans','expert_signals','expert_signal_legs','trade_records',
          'signal_trade_applications','user_performances','holdings_fix_proposals','current_prices','payment_providers','profiles','user_roles','member_subscriptions',
          'daily_price_snapshots','fx_rates','tw_market_holidays','target_price_history','audit_logs','stock_names','tw_bsr_daily','tw_bsr_sync_queue']
FUNCS = ['handle_signal_trade','save_signal_batch','admin_apply_fix_proposal',
 'admin_delete_trade_records_by_signal_ids','admin_delete_trade_records_by_symbol',
 'admin_signal_dupe_trades_fix','admin_trade_dedupe_sweep','realign_instrument_unit',
 'calculate_expert_performance','enforce_signal_capital_limit','enforce_trade_record_market_currency',
 'enforce_unit_consistency','enforce_user_performance_price','set_expert_signal_market',
 'enforce_signal_recall_same_day','update_updated_at_column','audit_row_change',
 'tg_holdings_fix_proposals_updated_at','recalc_user_summary_on_perf_delete',
 'enqueue_bsr_first_fetch_on_trade','trigger_expert_ai_reindex','has_role','admin_generate_fix_proposals',
 'has_active_subscription','has_active_subscription_after','is_tester','is_subscribed_to_plan',
 'sync_expert_slug_to_profile','sync_expert_currency_with_asset_class','enforce_expert_currency_lock',
 'enforce_expert_asset_class_lock','protect_backtest_fields','set_plan_initial_review_status',
 'enforce_plan_review_workflow','get_effective_user_id','recalc_user_summary','handle_new_user','signal_in_subscription_window',
 'protect_subscription_fields','protect_profile_fields','enforce_payment_provider_default_active','get_expert_capital_status','get_analyst_subscriber_profiles']

def q(sql):
    r = subprocess.run(['psql','-tAqX','-c',sql],capture_output=True,text=True)
    if r.returncode: raise SystemExit('psql failed: '+r.stderr)
    return [l for l in r.stdout.split('\n') if l.strip()]

# auto-discover every trigger function attached to the extracted tables (no hand list drift)
_tl = ",".join("'%s'" % t for t in TABLES)
for _f in q(f"""select distinct tg.tgfoid::regproc::text from pg_trigger tg
 join pg_class c on c.oid=tg.tgrelid join pg_namespace n on n.oid=c.relnamespace
 where not tg.tgisinternal and n.nspname='public' and c.relname in ({_tl})"""):
    _f = _f.split('.')[-1]
    if _f not in FUNCS: FUNCS.append(_f)

out = ["-- R0-B clone schema: extracted read-only from production catalogs",
       "-- generated by db/r0/extract_schema.py","SET client_min_messages=warning;","SET check_function_bodies=off;"]

# enums
out.append('\n-- ENUM TYPES')
for line in q("""select t.typname||'|'||string_agg(quote_literal(e.enumlabel),',' order by e.enumsortorder)
 from pg_type t join pg_enum e on e.enumtypid=t.oid join pg_namespace n on n.oid=t.typnamespace
 where n.nspname='public' group by t.typname order by 1"""):
    name,labels = line.split('|',1)
    out.append(f"CREATE TYPE public.{name} AS ENUM ({labels});")

# tables
out.append('\n-- TABLES')
tl = ",".join("'%s'"%t for t in TABLES)
for t in TABLES:
    cols = q(f"""select column_name||' '||
      case when data_type='USER-DEFINED' then 'public.'||udt_name
           when data_type='ARRAY' then replace(udt_name,'_','')||'[]'
           when character_maximum_length is not null then data_type||'('||character_maximum_length||')'
           when data_type='numeric' and numeric_precision is not null then 'numeric('||numeric_precision||','||coalesce(numeric_scale,0)||')'
           else data_type end ||
      case when column_default is not null then ' DEFAULT '||column_default else '' end ||
      case when is_nullable='NO' then ' NOT NULL' else '' end
      from information_schema.columns where table_schema='public' and table_name='{t}' order by ordinal_position""")
    out.append(f"CREATE TABLE public.{t} (\n  " + ",\n  ".join(cols) + "\n);")

out.append('\n-- CONSTRAINTS')
for line in q(f"""select replace(rel.relname||'|'||con.conname||'|'||pg_get_constraintdef(con.oid), chr(10), ' ')
 from pg_constraint con join pg_class rel on rel.oid=con.conrelid join pg_namespace ns on ns.oid=rel.relnamespace
 where ns.nspname='public' and rel.relname in ({tl}) order by case con.contype when 'p' then 0 when 'u' then 1 else 2 end, rel.relname, con.conname"""):
    rel,name,defn = line.split('|',2)
    out.append(f"ALTER TABLE public.{rel} ADD CONSTRAINT {name} {defn};")

out.append('\n-- INDEXES')
for line in q(f"""select replace(indexdef, chr(10),' ') from pg_indexes where schemaname='public' and tablename in ({tl})
 and indexname not in (select conname from pg_constraint where contype in ('p','u')) order by tablename, indexname"""):
    out.append(line+';')

out.append('\n-- FUNCTIONS')
fl = ",".join("'%s'"%f for f in FUNCS)
for line in q(f"""select replace(pg_get_functiondef(p.oid), chr(10), '~~NL~~') from pg_proc p
 join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ({fl}) order by p.proname"""):
    out.append(line.replace('~~NL~~','\n')+';')

out.append('\n-- FUNCTIONS (pass 2: resolve inter-function dependencies)')
for line in q(f"""select replace(pg_get_functiondef(p.oid), chr(10), '~~NL~~') from pg_proc p
 join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ({fl}) order by p.proname"""):
    out.append(line.replace('~~NL~~','\n')+';')

out.append('\n-- TRIGGERS')
for line in q(f"""select replace(pg_get_triggerdef(tg.oid), chr(10),' ') from pg_trigger tg join pg_class c on c.oid=tg.tgrelid
 join pg_namespace n on n.oid=c.relnamespace where not tg.tgisinternal and n.nspname='public'
 and c.relname in ({tl}) order by c.relname, tg.tgname"""):
    out.append(line+';')

out.append('\n-- RLS + POLICIES')
for t in TABLES:
    out.append(f"ALTER TABLE public.{t} ENABLE ROW LEVEL SECURITY;")
for line in q(f"""select replace(tablename||'|'||policyname||'|'||cmd||'|'||array_to_string(roles,',')||'|'||coalesce(qual,'')||'|'||coalesce(with_check,''), chr(10), ' ')
 from pg_policies where schemaname='public' and tablename in ({tl}) order by tablename, policyname"""):
    tb,pn,cmd,roles,qual,wc = line.split('|',5)
    s = f'CREATE POLICY "{pn}" ON public.{tb} FOR {cmd} TO {roles}'
    if qual: s += f' USING ({qual})'
    if wc: s += f' WITH CHECK ({wc})'
    out.append(s+';')

out.append('\n-- GRANTS (exact production ACL, replayed per grantee; no blanket GRANT ALL)')
for line in q(f"""select c.relname||'|'||coalesce(pg_get_userbyid(a.grantee),'PUBLIC')||'|'||
   string_agg(a.privilege_type,',' order by a.privilege_type)
 from pg_class c join pg_namespace n on n.oid=c.relnamespace, lateral aclexplode(c.relacl) a
 where n.nspname='public' and c.relname in ({tl})
   and coalesce(pg_get_userbyid(a.grantee),'PUBLIC') in ('anon','authenticated','service_role','PUBLIC')
 group by 1,2 order by 1,2"""):
    rel,grantee,privs = line.split('|',2)
    privs = ','.join(p for p in privs.split(',') if p != 'MAINTAIN')  # PG17-only priv, replay-safe subset
    out.append(f"GRANT {privs} ON public.{rel} TO {grantee};")

open('db/r1/clone/schema.sql','w').write('\n'.join(out)+'\n')
print('wrote db/r1/clone/schema.sql', len(out), 'statements-ish')
