-- GENERATED by scripts/gen-bsr-slice-fixture.sh (version 1e.v4)
-- provenance: project_ref=yqacmrgdjlenbijclngi generated_at=2026-08-12T20:46Z (2026-08-12 20:46 Asia/Taipei)
-- function body 為 production 原文（pg_get_functiondef），不得手改。
SET check_function_bodies = off;
SET client_min_messages = warning;
CREATE OR REPLACE FUNCTION public.bsr_backlog_metrics()
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
WITH tpe AS (
  SELECT (now() AT TIME ZONE 'Asia/Taipei')::date AS today_tw
), a AS (
  SELECT count(*)                                                        AS ready_pending_count,
         min(next_run_at)                                                AS oldest_due_since_ts,
         COALESCE(EXTRACT(epoch FROM (now() - min(next_run_at)))/3600.0, 0) AS oldest_due_since_h,
         COALESCE(EXTRACT(epoch FROM (now() - min(enqueued_at)))/3600.0, 0) AS oldest_ready_enqueued_h
    FROM public.tw_bsr_sync_queue
   WHERE status = 'pending' AND next_run_at IS NOT NULL AND next_run_at <= now()
), a_null AS (
  SELECT count(*) AS unclaimable_null_count
    FROM public.tw_bsr_sync_queue
   WHERE status = 'pending' AND next_run_at IS NULL
), b AS (
  SELECT count(*)                                                        AS deferred_count,
         min(next_run_at)                                                AS next_ready_at,
         COALESCE(EXTRACT(epoch FROM (now() - min(enqueued_at)))/3600.0, 0) AS oldest_enqueued_age_h
    FROM public.tw_bsr_sync_queue
   WHERE status = 'pending' AND next_run_at IS NOT NULL AND next_run_at > now()
), cohort AS (
  SELECT q.id, q.stock_id, q.trade_date, q.priority, q.enqueued_at, q.max_attempts
    FROM public.tw_bsr_sync_queue q
   WHERE q.status = 'failed'
     AND (q.last_error LIKE 'finmind_admission_%' OR q.last_error = 'quota_deferred')
), stocks AS (
  SELECT DISTINCT stock_id FROM cohort
), ready5 AS (
  SELECT s.stock_id, x.have5
    FROM stocks s CROSS JOIN tpe
    CROSS JOIN LATERAL (
      SELECT count(DISTINCT f.trade_date) AS have5
        FROM public.tw_chip_fact f
       WHERE f.stock_id = s.stock_id AND f.trade_date >= tpe.today_tw - 10
    ) x
), classified AS (
  SELECT c.*,
         EXISTS (SELECT 1 FROM public.tw_chip_fact f
                  WHERE f.stock_id = c.stock_id AND f.trade_date = c.trade_date) AS has_fact,
         COALESCE(r.have5, 0) AS have5
    FROM cohort c
    LEFT JOIN ready5 r ON r.stock_id = c.stock_id
), c AS (
  SELECT count(*)                                              AS legacy_quota_failed_total,
         count(*) FILTER (WHERE has_fact)                      AS satisfied_reconcilable,
         count(*) FILTER (
           WHERE NOT has_fact
             AND (trade_date = public.expected_latest_bsr_date()
                  OR (trade_date >= (SELECT today_tw FROM tpe) - 10 AND have5 < 5))
         )                                                     AS actionable_still_required,
         count(*) FILTER (
           WHERE NOT has_fact
             AND NOT (trade_date = public.expected_latest_bsr_date()
                      OR (trade_date >= (SELECT today_tw FROM tpe) - 10 AND have5 < 5))
         )                                                     AS obsolete_retained,
         count(*) FILTER (
           WHERE NOT has_fact
             AND max_attempts < 8
             AND (trade_date = public.expected_latest_bsr_date()
                  OR (trade_date >= (SELECT today_tw FROM tpe) - 10 AND have5 < 5))
         )                                                     AS actionable_token_eligible
    FROM classified
), d AS (
  SELECT COALESCE(sum(COALESCE(row_count, 0)), 0)                                       AS tokens_issued_24h,
         COALESCE(sum(COALESCE((metadata->>'reconciled')::int, 0)), 0)                  AS reconciled_24h,
         (SELECT metadata->>'budget_reason' FROM public.data_source_refresh_logs
           WHERE source_key = 'bsr_quota_recovery' ORDER BY created_at DESC LIMIT 1)    AS last_budget_reason,
         (SELECT metadata->>'next_admission_at' FROM public.data_source_refresh_logs
           WHERE source_key = 'bsr_quota_recovery' ORDER BY created_at DESC LIMIT 1)    AS last_next_admission_at
    FROM public.data_source_refresh_logs
   WHERE source_key = 'bsr_quota_recovery' AND created_at >= now() - interval '24 hours'
)
SELECT jsonb_build_object(
  'ready', jsonb_build_object(
     'ready_pending_count', a.ready_pending_count,
     'oldest_due_since_ts', a.oldest_due_since_ts,
     'oldest_due_since_h', round(a.oldest_due_since_h::numeric, 2),
     'oldest_ready_enqueued_h', round(a.oldest_ready_enqueued_h::numeric, 2),
     'unclaimable_null_count', a_null.unclaimable_null_count
  ),
  'deferred', jsonb_build_object(
     'deferred_count', b.deferred_count,
     'next_ready_at', b.next_ready_at,
     'oldest_enqueued_age_h', round(b.oldest_enqueued_age_h::numeric, 2)
  ),
  'cohort', jsonb_build_object(
     'legacy_quota_failed_total', c.legacy_quota_failed_total,
     'satisfied_reconcilable', c.satisfied_reconcilable,
     'actionable_still_required', c.actionable_still_required,
     'actionable_token_eligible', c.actionable_token_eligible,
     'obsolete_retained', c.obsolete_retained,
     'counting_mode', 'exact'
  ),
  'audit', jsonb_build_object(
     'tokens_issued_24h', d.tokens_issued_24h,
     'reconciled_24h', d.reconciled_24h,
     'last_budget_reason', d.last_budget_reason,
     'last_next_admission_at', d.last_next_admission_at
  ),
  'generated_at', now()
)
FROM a, a_null, b, c, d;
$function$
;

CREATE OR REPLACE FUNCTION public.bsr_get_degrade_state(_api text DEFAULT 'finmind'::text)
 RETURNS TABLE(mode text, since timestamp with time zone, reason text, trigger_metric text, trigger_value numeric, last_transition_at timestamp with time zone, cooldown_until timestamp with time zone)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  _cfg jsonb;
BEGIN
  SELECT config INTO _cfg FROM public.tw_bsr_sync_config WHERE key = 'degrade:' || _api;
  IF _cfg IS NULL THEN
    RETURN QUERY SELECT 'normal'::text, now(), 'initial'::text, NULL::text, NULL::numeric, now(), now();
    RETURN;
  END IF;
  RETURN QUERY SELECT
    COALESCE(_cfg->>'mode', 'normal'),
    COALESCE((_cfg->>'since')::timestamptz, now()),
    COALESCE(_cfg->>'reason', ''),
    _cfg->>'trigger_metric',
    NULLIF(_cfg->>'trigger_value','')::numeric,
    COALESCE((_cfg->>'last_transition_at')::timestamptz, now()),
    COALESCE((_cfg->>'cooldown_until')::timestamptz, now());
END;
$function$
;

CREATE OR REPLACE FUNCTION public.bsr_recovery_budget(p_full_budget integer DEFAULT 12)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_metrics jsonb;
  v_ks boolean;
  v_mode text;
  v_reason text;
  v_ready int;
  v_oldest numeric;
  v_level text;
  v_budget int;
  v_breason text;
  v_pools jsonb;
  v_any_pool_ok boolean := false;
  v_next_admission timestamptz;
  DAILY_RESERVE constant int := 30;
  BURST_RESERVE constant int := 30;
BEGIN
  v_metrics := public.bsr_backlog_metrics();
  v_ready  := COALESCE((v_metrics#>>'{ready,ready_pending_count}')::int, 0);
  v_oldest := COALESCE((v_metrics#>>'{ready,oldest_due_since_h}')::numeric, 0);

  SELECT public.check_kill_switch('chips_all') INTO v_ks;
  SELECT mode, reason INTO v_mode, v_reason FROM public.bsr_get_degrade_state('finmind');
  v_mode := COALESCE(v_mode, 'normal');
  v_reason := COALESCE(v_reason, '');

  -- pool snapshot (canary: interactive excluded, it is the user-facing drawer path)
  SELECT jsonb_agg(jsonb_build_object(
           'pool', pool_name,
           'tokens', floor(tokens),
           'used_today', used_today,
           'daily_budget', daily_budget,
           'reset_at', reset_at,
           'excluded', pool_name = 'interactive',
           'issue_ok', pool_name <> 'interactive'
                        AND used_today + 1 <= daily_budget - DAILY_RESERVE
                        AND floor(tokens) >= BURST_RESERVE + 1
         ) ORDER BY pool_name)
    INTO v_pools
    FROM public.finmind_quota_pools;

  SELECT bool_or((p->>'issue_ok')::boolean) INTO v_any_pool_ok
    FROM jsonb_array_elements(COALESCE(v_pools, '[]'::jsonb)) p;

  SELECT min(((reset_at + 1)::timestamp) AT TIME ZONE 'Asia/Taipei')
    INTO v_next_admission
    FROM public.finmind_quota_pools
   WHERE pool_name <> 'interactive';

  IF v_ks IS NOT TRUE THEN
    v_level := 'halted'; v_budget := 0; v_breason := 'kill_switch';
  ELSIF v_mode IN ('claim_halt', 'p1_only') THEN
    v_level := 'halted'; v_budget := 0; v_breason := 'degrade_' || v_mode;
  ELSIF v_mode = 'tier2_paused' THEN
    v_level := 'halted'; v_budget := 0; v_breason := 'degrade_tier2_paused';
  ELSIF v_mode = 'tier3_paused' AND v_reason = 'reservation_stuck' THEN
    v_level := 'halted'; v_budget := 0; v_breason := 'degrade_reservation_stuck';
  ELSIF COALESCE(v_any_pool_ok, false) IS NOT TRUE THEN
    v_level := 'pool_blocked'; v_budget := 0; v_breason := 'pool_reserve_blocked';
  ELSE
    -- capacity caps only; p1_stalled must NOT zero the budget (symptom, not cause)
    v_level := 'canary';
    v_budget := LEAST(1, GREATEST(0, COALESCE(p_full_budget, 12)));
    v_breason := 'cap_1';
    IF v_ready > 600 OR (v_mode = 'tier3_paused' AND v_reason = 'usage_ge_80') THEN
      v_level := 'capped';
      v_budget := LEAST(1, v_budget);
    END IF;
    IF v_budget = 0 THEN v_breason := 'cap_zero'; END IF;
  END IF;

  RETURN jsonb_build_object(
    'level', v_level,
    'budget', v_budget,
    'budget_reason', v_breason,
    'degrade', jsonb_build_object('mode', v_mode, 'reason', v_reason),
    'kill_switch_on', v_ks,
    'pools', COALESCE(v_pools, '[]'::jsonb),
    'next_admission_at', v_next_admission,
    'pending_ready', v_ready,
    'oldest_due_since_h', v_oldest,
    'metrics', v_metrics
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.check_kill_switch(_key text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT COALESCE(
    (SELECT enabled FROM public.system_kill_switches WHERE key = _key),
    true
  ) AND COALESCE(
    (SELECT enabled FROM public.system_kill_switches WHERE key = 'chips_all'),
    true
  );
$function$
;

CREATE OR REPLACE FUNCTION public.checkup_prefetch_universe()
 RETURNS TABLE(code text, supported boolean, reason text, sources text[])
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  WITH raw AS (
    SELECT upper(btrim((regexp_match(split_part(tr.instrument,' ',1), '^([0-9A-Z]{4,6})'))[1])) AS code,
           'trade_records'::text AS src
      FROM public.trade_records tr
     WHERE COALESCE(upper(tr.market),'TW') IN ('TW','TWSE','TPEX','')
       AND split_part(tr.instrument,' ',1) ~ '^[0-9]'
    UNION ALL
    SELECT upper(btrim((regexp_match(split_part(es.instrument,' ',1), '^([0-9A-Z]{4,6})'))[1])),
           'expert_signals'
      FROM public.expert_signals es
     WHERE es.published_at IS NOT NULL
       AND COALESCE(upper(es.market),'TW') IN ('TW','TWSE','TPEX','')
       AND split_part(es.instrument,' ',1) ~ '^[0-9]'
    UNION ALL
    SELECT upper(btrim(COALESCE(h->>'code', h->>'symbol'))), 'checkup_storage'
      FROM public.checkup_storage cs,
           LATERAL jsonb_array_elements(
             CASE
               WHEN jsonb_typeof(cs.data) = 'array' THEN cs.data
               WHEN jsonb_typeof(cs.data->'holdings') = 'array' THEN cs.data->'holdings'
               ELSE '[]'::jsonb
             END
           ) h
     WHERE cs.key = 'pf-holdings-v2'
    UNION ALL
    SELECT upper(btrim(t.code)), 'registry'
      FROM public.chips_prefetch_targets t
     WHERE t.active
  ),
  norm AS (
    SELECT code, src FROM raw WHERE code IS NOT NULL AND code <> ''
  ),
  agg AS (
    SELECT code, array_agg(DISTINCT src ORDER BY src) AS sources
      FROM norm GROUP BY code
  )
  SELECT a.code,
         COALESCE((public.tw_bsr_eligibility(a.code)->>'eligible')::boolean, false) AS supported,
         public.tw_bsr_eligibility(a.code)->>'ineligible_reason' AS reason,
         a.sources
    FROM agg a;
$function$
;

CREATE OR REPLACE FUNCTION public.expected_latest_bsr_date()
 RETURNS date
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  WITH base AS (
    SELECT CASE WHEN EXTRACT(hour FROM (now() AT TIME ZONE 'Asia/Taipei')) >= 15
                THEN (now() AT TIME ZONE 'Asia/Taipei')::date
                ELSE (now() AT TIME ZONE 'Asia/Taipei')::date - 1 END AS d
  ), cand AS (
    SELECT (SELECT d FROM base) - g AS dd FROM generate_series(0, 20) g
  )
  SELECT max(dd) FROM cand
   WHERE EXTRACT(ISODOW FROM dd) < 6
     AND NOT EXISTS (SELECT 1 FROM public.tw_market_holidays h WHERE h.trade_date = dd);
$function$
;

CREATE OR REPLACE FUNCTION public.recover_quota_failed_bsr_jobs(p_max integer DEFAULT 12)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_t0 timestamptz := clock_timestamp();
  v_invocation uuid := gen_random_uuid();
  v_cap int := LEAST(1, GREATEST(0, COALESCE(p_max, 0)));
  v_lock boolean;
  v_before jsonb;
  v_after jsonb;
  v_budget jsonb;
  v_breason text;
  v_pools jsonb;
  v_next_admission text;
  v_today_tw date := (now() AT TIME ZONE 'Asia/Taipei')::date;
  v_reconciled_id bigint;
  v_reconciled int := 0;
  v_token_id bigint;
  v_tokens int := 0;
  v_inspected int := 0;
  v_result jsonb;
  CANDIDATE_LIMIT constant int := 200;
  LOCK_KEY constant bigint := 771001;
BEGIN
  SELECT pg_try_advisory_xact_lock(LOCK_KEY) INTO v_lock;

  IF v_lock IS NOT TRUE THEN
    INSERT INTO public.data_source_refresh_logs
      (source_key, triggered_by, status, started_at, finished_at, duration_ms, row_count, metadata)
    VALUES ('bsr_quota_recovery', NULL, 'skipped', v_t0, clock_timestamp(),
            (EXTRACT(epoch FROM (clock_timestamp() - v_t0)) * 1000)::int, 0,
            jsonb_build_object('invocation_id', v_invocation, 'budget_reason', 'lock_contended',
                               'counting_mode', 'exact', 'tokens_issued', 0, 'reconciled', 0));
    RETURN jsonb_build_object('invocation_id', v_invocation, 'tokens_issued', 0, 'reconciled', 0,
                              'recovered', 0, 'budget_reason', 'lock_contended', 'counting_mode', 'exact');
  END IF;

  v_budget := public.bsr_recovery_budget(GREATEST(v_cap, 0));
  v_breason := v_budget->>'budget_reason';
  v_pools := v_budget->'pools';
  v_next_admission := v_budget->>'next_admission_at';
  v_before := v_budget->'metrics';
  v_cap := LEAST(v_cap, COALESCE((v_budget->>'budget')::int, 0));

  WITH pick AS (
    SELECT q.id
      FROM public.tw_bsr_sync_queue q
     WHERE q.status = 'failed'
       AND (q.last_error LIKE 'finmind_admission_%' OR q.last_error = 'quota_deferred')
       AND EXISTS (SELECT 1 FROM public.tw_chip_fact f
                    WHERE f.stock_id = q.stock_id AND f.trade_date = q.trade_date)
     ORDER BY q.trade_date DESC, q.enqueued_at ASC
     FOR UPDATE SKIP LOCKED
     LIMIT 1
  )
  UPDATE public.tw_bsr_sync_queue q
     SET status = 'done',
         last_error = 'reconciled_fact_exists',
         finished_at = now(),
         last_success_at = COALESCE(q.last_success_at, now()),
         updated_at = now()
    FROM pick
   WHERE q.id = pick.id
  RETURNING q.id INTO v_reconciled_id;

  IF v_reconciled_id IS NOT NULL THEN v_reconciled := 1; END IF;

  IF v_cap > 0 THEN
    WITH cand AS (
      SELECT q.id, q.stock_id, q.trade_date, q.priority, q.enqueued_at
        FROM public.tw_bsr_sync_queue q
       WHERE q.status = 'failed'
         AND (q.last_error LIKE 'finmind_admission_%' OR q.last_error = 'quota_deferred')
         AND q.max_attempts < 8
         AND NOT EXISTS (SELECT 1 FROM public.tw_chip_fact f
                          WHERE f.stock_id = q.stock_id AND f.trade_date = q.trade_date)
       ORDER BY q.trade_date DESC, q.enqueued_at ASC
       LIMIT CANDIDATE_LIMIT
    ),
    ready5 AS (
      SELECT s.stock_id, x.have5
        FROM (SELECT DISTINCT stock_id FROM cand) s
        CROSS JOIN LATERAL (
          SELECT count(DISTINCT f.trade_date) AS have5
            FROM public.tw_chip_fact f
           WHERE f.stock_id = s.stock_id AND f.trade_date >= v_today_tw - 10
        ) x
    ),
    actionable AS (
      SELECT c.id, c.trade_date, c.enqueued_at,
             CASE WHEN c.priority <= 1 THEN 'interactive'
                  WHEN c.priority = 2 THEN 'keepwarm'
                  ELSE 'backfill' END AS pool
        FROM cand c
        LEFT JOIN ready5 r ON r.stock_id = c.stock_id
       WHERE c.trade_date = public.expected_latest_bsr_date()
          OR (c.trade_date >= v_today_tw - 10 AND COALESCE(r.have5, 0) < 5)
    ),
    eligible AS (
      SELECT a.id
        FROM actionable a
        JOIN jsonb_array_elements(COALESCE(v_pools, '[]'::jsonb)) p
          ON p->>'pool' = a.pool AND (p->>'issue_ok')::boolean
       ORDER BY a.trade_date DESC, a.enqueued_at ASC
       LIMIT v_cap
    ),
    locked AS (
      SELECT q.id FROM public.tw_bsr_sync_queue q
       WHERE q.id IN (SELECT id FROM eligible)
       FOR UPDATE SKIP LOCKED
    )
    UPDATE public.tw_bsr_sync_queue q
       SET status = 'pending',
           max_attempts = q.max_attempts + 1,
           next_run_at = now(),
           started_at = NULL,
           finished_at = NULL,
           last_error = 'quota_recovery_token',
           updated_at = now()
      FROM locked
     WHERE q.id = locked.id
    RETURNING q.id INTO v_token_id;

    IF v_token_id IS NOT NULL THEN v_tokens := 1; END IF;

    SELECT LEAST(count(*), CANDIDATE_LIMIT) INTO v_inspected
      FROM public.tw_bsr_sync_queue q
     WHERE q.status = 'failed'
       AND (q.last_error LIKE 'finmind_admission_%' OR q.last_error = 'quota_deferred');
  END IF;

  v_after := public.bsr_backlog_metrics();

  INSERT INTO public.data_source_refresh_logs
    (source_key, triggered_by, status, started_at, finished_at, duration_ms, row_count, metadata)
  VALUES ('bsr_quota_recovery', NULL,
          CASE WHEN v_tokens > 0 OR v_reconciled > 0 THEN 'success' ELSE 'skipped' END,
          v_t0, clock_timestamp(),
          (EXTRACT(epoch FROM (clock_timestamp() - v_t0)) * 1000)::int,
          v_tokens,
          jsonb_build_object(
            'invocation_id', v_invocation,
            'budget_reason', v_breason,
            'degrade', v_budget->'degrade',
            'pools', v_pools,
            'pool_excluded', jsonb_build_array('interactive'),
            'counting_mode', 'exact',
            'candidates_inspected', v_inspected,
            'cap', v_cap,
            'tokens_issued', v_tokens,
            'reconciled', v_reconciled,
            'tokened_job_ids', CASE WHEN v_token_id IS NULL THEN '[]'::jsonb ELSE jsonb_build_array(v_token_id) END,
            'reconciled_job_ids', CASE WHEN v_reconciled_id IS NULL THEN '[]'::jsonb ELSE jsonb_build_array(v_reconciled_id) END,
            'metrics_before', v_before,
            'metrics_after', v_after,
            'next_admission_at', v_next_admission,
            'total_ms', (EXTRACT(epoch FROM (clock_timestamp() - v_t0)) * 1000)::int
          ));

  v_result := jsonb_build_object(
    'invocation_id', v_invocation,
    'tokens_issued', v_tokens,
    'reconciled', v_reconciled,
    'budget_reason', v_breason,
    'counting_mode', 'exact',
    'cap', v_cap,
    'candidates_inspected', v_inspected,
    'tokened_job_ids', CASE WHEN v_token_id IS NULL THEN '[]'::jsonb ELSE jsonb_build_array(v_token_id) END,
    'reconciled_job_ids', CASE WHEN v_reconciled_id IS NULL THEN '[]'::jsonb ELSE jsonb_build_array(v_reconciled_id) END,
    'next_admission_at', v_next_admission,
    'metrics_after', v_after
  );

  RETURN v_result || jsonb_build_object(
    'recovered', v_tokens,
    'remaining', COALESCE((v_after#>>'{cohort,legacy_quota_failed_total}')::int, 0)
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.tw_bsr_eligibility(p_stock_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_sn record;
BEGIN
  IF p_stock_id IS NULL OR btrim(p_stock_id) = '' THEN
    RETURN jsonb_build_object('eligible', false, 'ineligible_reason', 'invalid_stock_id');
  END IF;

  -- 台股個股代號：4 位數字、首位 1-9（FinMind 分點覆蓋範圍）
  IF NOT (p_stock_id ~ '^[1-9][0-9]{3}$') THEN
    -- 若在 stock_names 內找得到但非 tw_stock，回 unsupported_asset_type；否則 invalid
    SELECT symbol, asset_class INTO v_sn
      FROM public.stock_names WHERE symbol = p_stock_id LIMIT 1;
    IF FOUND AND v_sn.asset_class IS NOT NULL AND v_sn.asset_class <> 'tw_stock' THEN
      RETURN jsonb_build_object(
        'eligible', false,
        'ineligible_reason', 'unsupported_asset_type',
        'asset_class', v_sn.asset_class
      );
    END IF;
    -- 4 位數字但首位為 0（ETF/受益憑證）視為 unsupported_asset_type
    IF p_stock_id ~ '^0[0-9]{3,5}$' THEN
      RETURN jsonb_build_object('eligible', false, 'ineligible_reason', 'unsupported_asset_type');
    END IF;
    RETURN jsonb_build_object('eligible', false, 'ineligible_reason', 'invalid_stock_id');
  END IF;

  -- 若 stock_names 明示為非 tw_stock（罕見），視為 unsupported
  SELECT asset_class INTO v_sn FROM public.stock_names WHERE symbol = p_stock_id LIMIT 1;
  IF FOUND AND v_sn.asset_class IS NOT NULL AND v_sn.asset_class <> 'tw_stock' THEN
    RETURN jsonb_build_object(
      'eligible', false,
      'ineligible_reason', 'unsupported_asset_type',
      'asset_class', v_sn.asset_class
    );
  END IF;

  RETURN jsonb_build_object('eligible', true);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.tw_bsr_sync_queue_touch_updated()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN NEW.updated_at = now(); RETURN NEW; END; $function$
;

-- 保留的 trigger binding（唯一一個）
CREATE TRIGGER trg_tw_bsr_sync_queue_updated BEFORE UPDATE ON public.tw_bsr_sync_queue FOR EACH ROW EXECUTE FUNCTION tw_bsr_sync_queue_touch_updated();
