-- GENERATED by scripts/gen-bsr-slice-fixture.sh (version 1e.v4)
-- provenance: project_ref=yqacmrgdjlenbijclngi generated_at=2026-08-12T20:32Z (2026-08-12 20:32 Asia/Taipei)
-- 受測 dependency slice，非完整 current schema。無 rows、無 secrets、無 RLS policy。
-- 簡化項見 Build 1e Final Plan v4 §4。
SET client_min_messages = warning;
CREATE SCHEMA IF NOT EXISTS public;
CREATE TYPE public.signal_action AS ENUM ('buy','sell','add','trim','exit','hold','teaching');
CREATE TYPE public.signal_status AS ENUM ('published','pending');
CREATE TYPE public.trade_status AS ENUM ('open','closed','stopped');
CREATE SEQUENCE public.tw_bsr_sync_queue_id_seq;
CREATE SEQUENCE public.tw_chip_fact_id_seq;
CREATE TABLE public.checkup_storage (
  key text NOT NULL,
  data jsonb DEFAULT '{}'::jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  user_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL
);
CREATE TABLE public.chips_prefetch_targets (
  code text NOT NULL,
  source text DEFAULT 'manual'::text NOT NULL,
  active boolean DEFAULT true NOT NULL,
  supported boolean DEFAULT true NOT NULL,
  reason text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.data_source_refresh_logs (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  source_key text NOT NULL,
  triggered_by uuid,
  status text NOT NULL,
  started_at timestamp with time zone DEFAULT now() NOT NULL,
  finished_at timestamp with time zone,
  duration_ms integer,
  row_count integer,
  error_message text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.expert_signals (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  expert_id uuid NOT NULL,
  plan_id uuid,
  instrument text NOT NULL,
  action signal_action NOT NULL,
  price_hint numeric,
  reason_summary text,
  reason_detail text,
  risk_notes text,
  learning_points text,
  status signal_status DEFAULT 'published'::signal_status NOT NULL,
  taken_down_reason text,
  taken_down_by uuid,
  published_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  line_pushed_at timestamp with time zone,
  quantity integer,
  quantity_unit text DEFAULT '張'::text,
  teaching_topic text,
  overall_summary text,
  batch_id uuid,
  executed_at timestamp with time zone,
  market text NOT NULL,
  is_combo boolean DEFAULT false NOT NULL,
  combo_strategy text,
  net_premium numeric,
  max_loss_per_unit numeric,
  max_profit_per_unit numeric
);
CREATE TABLE public.finmind_quota_pools (
  pool_name text NOT NULL,
  daily_budget integer DEFAULT 100 NOT NULL,
  used_today integer DEFAULT 0 NOT NULL,
  reset_at date DEFAULT ((now() AT TIME ZONE 'Asia/Taipei'::text))::date NOT NULL,
  priority integer DEFAULT 5 NOT NULL,
  last_reject_at timestamp with time zone,
  last_reject_reason text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  capacity integer,
  tokens numeric,
  refill_per_min numeric DEFAULT 0 NOT NULL,
  last_refill_at timestamp with time zone DEFAULT now() NOT NULL,
  borrow_enabled boolean DEFAULT true NOT NULL,
  slo_boost_until timestamp with time zone,
  manual_override boolean DEFAULT false NOT NULL,
  base_daily_budget integer
);
CREATE TABLE public.stock_names (
  symbol text NOT NULL,
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  currency text DEFAULT 'TWD'::text NOT NULL,
  market text,
  asset_class text DEFAULT 'tw_stock'::text NOT NULL
);
CREATE TABLE public.system_kill_switches (
  key text NOT NULL,
  enabled boolean DEFAULT true NOT NULL,
  disabled_reason text,
  auto_trigger_metric text,
  disabled_at timestamp with time zone,
  disabled_by uuid,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.trade_records (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  expert_id uuid NOT NULL,
  signal_id uuid,
  instrument text NOT NULL,
  entry_price numeric,
  exit_price numeric,
  entry_date timestamp with time zone,
  exit_date timestamp with time zone,
  pnl_percent numeric,
  status trade_status DEFAULT 'open'::trade_status NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  current_price numeric,
  price_updated_at timestamp with time zone,
  quantity integer DEFAULT 1 NOT NULL,
  quantity_unit text DEFAULT '張'::text NOT NULL,
  market text,
  currency text,
  is_combo boolean DEFAULT false NOT NULL,
  combo_strategy text,
  net_premium numeric,
  max_loss_per_unit numeric,
  max_profit_per_unit numeric
);
CREATE TABLE public.tw_bsr_sync_config (
  key text NOT NULL,
  config jsonb NOT NULL,
  version integer DEFAULT 1 NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_by uuid,
  note text
);
CREATE TABLE public.tw_bsr_sync_queue (
  id bigint DEFAULT nextval('tw_bsr_sync_queue_id_seq'::regclass) NOT NULL,
  stock_id text NOT NULL,
  trade_date date NOT NULL,
  priority smallint NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  attempts integer DEFAULT 0 NOT NULL,
  max_attempts integer DEFAULT 5 NOT NULL,
  next_run_at timestamp with time zone DEFAULT now() NOT NULL,
  last_success_at timestamp with time zone,
  last_error text,
  enqueued_by text,
  enqueued_at timestamp with time zone DEFAULT now() NOT NULL,
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  correlation_id uuid,
  post_close_only boolean DEFAULT false NOT NULL
);
CREATE TABLE public.tw_chip_fact (
  id bigint DEFAULT nextval('tw_chip_fact_id_seq'::regclass) NOT NULL,
  stock_id text NOT NULL,
  trade_date date NOT NULL,
  broker_id text NOT NULL,
  broker_name text,
  source text NOT NULL,
  buy_shares bigint DEFAULT 0 NOT NULL,
  sell_shares bigint DEFAULT 0 NOT NULL,
  net_shares bigint GENERATED ALWAYS AS ((buy_shares - sell_shares)) STORED,
  avg_buy_price numeric(12,4),
  avg_sell_price numeric(12,4),
  raw jsonb,
  ingested_at timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public.tw_market_holidays (
  trade_date date NOT NULL,
  name text,
  source text DEFAULT 'manual'::text NOT NULL,
  detected_at timestamp with time zone DEFAULT now() NOT NULL,
  note text
);
ALTER TABLE public.checkup_storage ADD CONSTRAINT checkup_storage_pkey PRIMARY KEY (user_id, key);
ALTER TABLE public.chips_prefetch_targets ADD CONSTRAINT chips_prefetch_targets_pkey PRIMARY KEY (code);
ALTER TABLE public.chips_prefetch_targets ADD CONSTRAINT chips_prefetch_targets_source_chk CHECK ((source = ANY (ARRAY['demo_seed'::text, 'manual'::text, 'ops'::text])));
ALTER TABLE public.data_source_refresh_logs ADD CONSTRAINT data_source_refresh_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.data_source_refresh_logs ADD CONSTRAINT data_source_refresh_logs_status_check CHECK ((status = ANY (ARRAY['running'::text, 'success'::text, 'error'::text, 'partial'::text, 'skipped'::text, 'done'::text, 'failed'::text])));
ALTER TABLE public.expert_signals ADD CONSTRAINT expert_signals_pkey PRIMARY KEY (id);
ALTER TABLE public.finmind_quota_pools ADD CONSTRAINT finmind_quota_pools_pkey PRIMARY KEY (pool_name);
ALTER TABLE public.stock_names ADD CONSTRAINT stock_names_asset_class_check CHECK ((asset_class = ANY (ARRAY['tw_stock'::text, 'us_stock'::text, 'crypto'::text, 'us_option'::text, 'us_future'::text])));
ALTER TABLE public.stock_names ADD CONSTRAINT stock_names_currency_check CHECK ((currency = ANY (ARRAY['TWD'::text, 'USD'::text])));
ALTER TABLE public.stock_names ADD CONSTRAINT stock_names_pkey PRIMARY KEY (symbol);
ALTER TABLE public.system_kill_switches ADD CONSTRAINT system_kill_switches_pkey PRIMARY KEY (key);
ALTER TABLE public.trade_records ADD CONSTRAINT trade_records_pkey PRIMARY KEY (id);
ALTER TABLE public.trade_records ADD CONSTRAINT trade_records_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES expert_signals(id);
ALTER TABLE public.tw_bsr_sync_config ADD CONSTRAINT tw_bsr_sync_config_pkey PRIMARY KEY (key);
ALTER TABLE public.tw_bsr_sync_queue ADD CONSTRAINT tw_bsr_sync_queue_pkey PRIMARY KEY (id);
ALTER TABLE public.tw_bsr_sync_queue ADD CONSTRAINT tw_bsr_sync_queue_priority_check CHECK ((priority = ANY (ARRAY[1, 2, 3])));
ALTER TABLE public.tw_bsr_sync_queue ADD CONSTRAINT tw_bsr_sync_queue_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'running'::text, 'done'::text, 'failed'::text, 'skipped'::text])));
ALTER TABLE public.tw_chip_fact ADD CONSTRAINT tw_chip_fact_pkey PRIMARY KEY (id);
ALTER TABLE public.tw_chip_fact ADD CONSTRAINT tw_chip_fact_unique_lane UNIQUE (stock_id, trade_date, broker_id, source);
ALTER TABLE public.tw_market_holidays ADD CONSTRAINT tw_market_holidays_pkey PRIMARY KEY (trade_date);
CREATE UNIQUE INDEX trade_records_signal_id_open_uniq ON public.trade_records USING btree (signal_id) WHERE ((signal_id IS NOT NULL) AND (exit_date IS NULL));
CREATE UNIQUE INDEX tw_bsr_sync_queue_active_uniq ON public.tw_bsr_sync_queue USING btree (stock_id, trade_date) WHERE (status = ANY (ARRAY['pending'::text, 'running'::text, 'failed'::text, 'skipped'::text]));
