-- generated by scripts/gen-bsr-e2e-fixture.sh（ephemeral-only；不可用於 production）
CREATE OR REPLACE FUNCTION public.materialize_bsr_daily_from_fact(_trade_date date)
 RETURNS TABLE(materialized_rows integer, skipped_sealed boolean)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_is_sealed boolean := false;
  v_count int := 0;
BEGIN
  SELECT (sealed_at IS NOT NULL) INTO v_is_sealed
  FROM public.tw_bsr_daily_snapshot_status
  WHERE trade_date = _trade_date;

  IF COALESCE(v_is_sealed, false) THEN
    RETURN QUERY SELECT 0, true;
    RETURN;
  END IF;

  -- Bypass immutability trigger for this authorized materializer
  PERFORM set_config('app.force_reseal', 'true', true);

  WITH ranked AS (
    SELECT
      stock_id, trade_date, broker_id, broker_name,
      buy_shares, sell_shares, net_shares,
      avg_buy_price, avg_sell_price,
      row_number() OVER (
        PARTITION BY stock_id, trade_date, broker_id
        ORDER BY
          CASE source
            WHEN 'broker_scraper' THEN 1
            WHEN 'finmind_batch' THEN 2
            WHEN 'finmind_per_stock' THEN 3
            ELSE 9
          END,
          ingested_at DESC
      ) AS rn
    FROM public.tw_chip_fact
    WHERE trade_date = _trade_date
  ),
  ins AS (
    INSERT INTO public.tw_bsr_daily (
      stock_id, trade_date, broker_id, broker_name,
      buy_shares, sell_shares, net_shares,
      avg_buy_price, avg_sell_price
    )
    SELECT
      stock_id, trade_date, broker_id, broker_name,
      buy_shares, sell_shares, net_shares,
      avg_buy_price, avg_sell_price
    FROM ranked
    WHERE rn = 1
    ON CONFLICT (stock_id, trade_date, broker_id) DO UPDATE SET
      broker_name = EXCLUDED.broker_name,
      buy_shares = EXCLUDED.buy_shares,
      sell_shares = EXCLUDED.sell_shares,
      net_shares = EXCLUDED.net_shares,
      avg_buy_price = EXCLUDED.avg_buy_price,
      avg_sell_price = EXCLUDED.avg_sell_price
    RETURNING 1
  )
  SELECT count(*) INTO v_count FROM ins;

  PERFORM set_config('app.force_reseal', 'false', true);

  RETURN QUERY SELECT v_count, false;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.materialize_bsr_daily_from_fact(_trade_date date, _stock_ids text[] DEFAULT NULL::text[])
 RETURNS TABLE(materialized_rows integer, skipped_sealed boolean)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_is_sealed boolean := false;
  v_count int := 0;
BEGIN
  SELECT (sealed_at IS NOT NULL) INTO v_is_sealed
  FROM public.tw_bsr_daily_snapshot_status
  WHERE trade_date = _trade_date;

  IF COALESCE(v_is_sealed, false) THEN
    RETURN QUERY SELECT 0, true;
    RETURN;
  END IF;

  PERFORM set_config('app.force_reseal', 'true', true);

  WITH ranked AS (
    SELECT
      stock_id, trade_date, broker_id, broker_name,
      buy_shares, sell_shares, net_shares,
      avg_buy_price, avg_sell_price,
      row_number() OVER (
        PARTITION BY stock_id, trade_date, broker_id
        ORDER BY
          CASE source
            WHEN 'broker_scraper' THEN 1
            WHEN 'finmind_batch' THEN 2
            WHEN 'finmind_per_stock' THEN 3
            ELSE 9
          END,
          ingested_at DESC
      ) AS rn
    FROM public.tw_chip_fact
    WHERE trade_date = _trade_date
      AND (_stock_ids IS NULL OR stock_id = ANY(_stock_ids))
  ),
  ins AS (
    INSERT INTO public.tw_bsr_daily (
      stock_id, trade_date, broker_id, broker_name,
      buy_shares, sell_shares, net_shares,
      avg_buy_price, avg_sell_price
    )
    SELECT
      stock_id, trade_date, broker_id, broker_name,
      buy_shares, sell_shares, net_shares,
      avg_buy_price, avg_sell_price
    FROM ranked
    WHERE rn = 1
    ON CONFLICT (stock_id, trade_date, broker_id) DO UPDATE SET
      broker_name = EXCLUDED.broker_name,
      buy_shares = EXCLUDED.buy_shares,
      sell_shares = EXCLUDED.sell_shares,
      net_shares = EXCLUDED.net_shares,
      avg_buy_price = EXCLUDED.avg_buy_price,
      avg_sell_price = EXCLUDED.avg_sell_price
    RETURNING 1
  )
  SELECT count(*) INTO v_count FROM ins;

  PERFORM set_config('app.force_reseal', 'false', true);

  RETURN QUERY SELECT v_count, false;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.rebuild_bsr_rollup(_as_of date, _stock_ids text[] DEFAULT NULL::text[], _max_stocks integer DEFAULT 400)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_sid text; v_rows int := 0; v_stocks int := 0;
  v_dates date[]; v_win int; v_use date[]; v_src date;
  v_top_buy jsonb; v_top_sell jsonb; v_conc numeric; v_broker_count int;
BEGIN
  FOR v_sid IN
    SELECT DISTINCT stock_id FROM public.tw_bsr_daily
     WHERE trade_date = _as_of
       AND (_stock_ids IS NULL OR stock_id = ANY(_stock_ids))
     ORDER BY stock_id
     LIMIT _max_stocks
  LOOP
    v_stocks := v_stocks + 1;
    SELECT array_agg(d ORDER BY d DESC) INTO v_dates
      FROM (SELECT DISTINCT trade_date d FROM public.tw_bsr_daily
             WHERE stock_id = v_sid AND trade_date <= _as_of
               AND trade_date >= _as_of - 90) t;
    IF v_dates IS NULL THEN CONTINUE; END IF;

    SELECT COUNT(DISTINCT broker_id) INTO v_broker_count
      FROM public.tw_bsr_daily WHERE stock_id = v_sid AND trade_date = _as_of;

    FOREACH v_win IN ARRAY ARRAY[1,5,10,20,60] LOOP
      v_use := v_dates[1:LEAST(v_win, array_length(v_dates,1))];
      v_src := v_use[1];

      WITH agg AS (
        SELECT broker_id,
               COALESCE(MAX(NULLIF(TRIM(broker_name),'')), '券商分點 ' || broker_id) AS nm,
               SUM(COALESCE(net_shares,0))::bigint AS net,
               SUM(COALESCE(buy_shares,0))::bigint AS buy
          FROM public.tw_bsr_daily
         WHERE stock_id = v_sid AND trade_date = ANY(v_use)
         GROUP BY broker_id
      )
      SELECT
        (SELECT jsonb_agg(jsonb_build_object('broker_id',broker_id,'name',nm,'net',net))
           FROM (SELECT * FROM agg ORDER BY net DESC LIMIT 3) x),
        (SELECT jsonb_agg(jsonb_build_object('broker_id',broker_id,'name',nm,'net',net))
           FROM (SELECT * FROM agg ORDER BY net ASC LIMIT 3) y),
        CASE WHEN (SELECT SUM(buy) FROM agg) > 0
             THEN ROUND((SELECT SUM(buy) FROM (SELECT buy FROM agg ORDER BY buy DESC LIMIT 15) z)::numeric
                        / (SELECT SUM(buy) FROM agg)::numeric * 100, 2)
             ELSE NULL END
      INTO v_top_buy, v_top_sell, v_conc;

      IF v_top_buy IS NULL THEN CONTINUE; END IF;

      INSERT INTO public.tw_chips_rollup
        (stock_id, as_of_date, window_days, source_date, fallback_used,
         foreign_net, trust_net, dealer_net, top_buy_brokers, top_sell_brokers,
         concentration_ratio, bsr_available, broker_count, low_quality, updated_at)
      VALUES (v_sid, _as_of, v_win, v_src, v_src < _as_of,
              0, 0, 0, v_top_buy, v_top_sell,
              v_conc, true,
              CASE WHEN v_win = 5 THEN v_broker_count ELSE NULL END,
              CASE WHEN v_win = 5 THEN (v_broker_count > 0 AND v_broker_count < 5) ELSE NULL END,
              now())
      ON CONFLICT (stock_id, as_of_date, window_days) DO UPDATE
        SET source_date = EXCLUDED.source_date,
            fallback_used = EXCLUDED.fallback_used,
            top_buy_brokers = EXCLUDED.top_buy_brokers,
            top_sell_brokers = EXCLUDED.top_sell_brokers,
            concentration_ratio = EXCLUDED.concentration_ratio,
            bsr_available = true,
            broker_count = COALESCE(EXCLUDED.broker_count, public.tw_chips_rollup.broker_count),
            low_quality = COALESCE(EXCLUDED.low_quality, public.tw_chips_rollup.low_quality),
            updated_at = now();
      v_rows := v_rows + 1;
    END LOOP;
  END LOOP;

  RETURN jsonb_build_object('as_of', _as_of, 'stocks', v_stocks, 'rows', v_rows);
END;
$function$
;
CREATE OR REPLACE FUNCTION public.bsr_snapshot_mark(_trade_date date, _status text, _source text, _coverage_stocks integer, _coverage_rows integer, _last_error text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  UPDATE public.tw_bsr_daily_snapshot_status
     SET status = _status,
         source = COALESCE(_source, source),
         fetched_at = CASE WHEN _status IN ('ready','partial') THEN now() ELSE fetched_at END,
         coverage_stocks = GREATEST(coverage_stocks, COALESCE(_coverage_stocks, 0)),
         coverage_rows   = GREATEST(coverage_rows,   COALESCE(_coverage_rows, 0)),
         last_error = _last_error,
         lock_expires_at = NULL
   WHERE trade_date = _trade_date;
$function$
;

CREATE OR REPLACE FUNCTION public.bsr_snapshot_mark(_trade_date date, _status text, _source text, _coverage_stocks integer, _coverage_rows integer, _last_error text DEFAULT NULL::text, _sealed_by_lane text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  UPDATE public.tw_bsr_daily_snapshot_status
     SET status = _status,
         source = COALESCE(_source, source),
         fetched_at = CASE WHEN _status IN ('ready','partial') THEN now() ELSE fetched_at END,
         coverage_stocks = GREATEST(coverage_stocks, COALESCE(_coverage_stocks, 0)),
         coverage_rows   = GREATEST(coverage_rows,   COALESCE(_coverage_rows, 0)),
         last_error = _last_error,
         lock_expires_at = NULL,
         -- 只有第一次轉 ready 時封存，避免重複更新時戳
         sealed_at = COALESCE(
           public.tw_bsr_daily_snapshot_status.sealed_at,
           CASE WHEN _status = 'ready' THEN now() ELSE NULL END
         ),
         sealed_by_lane = COALESCE(
           public.tw_bsr_daily_snapshot_status.sealed_by_lane,
           CASE WHEN _status = 'ready' THEN COALESCE(_sealed_by_lane, _source) ELSE NULL END
         )
   WHERE trade_date = _trade_date;
$function$
;
CREATE OR REPLACE FUNCTION public.bsr_snapshot_fulfill_jobs(_trade_date date, _threshold integer DEFAULT 5)
 RETURNS TABLE(fulfilled integer, still_pending integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_done integer;
  v_pending integer;
BEGIN
  WITH sufficient AS (
    SELECT stock_id
      FROM public.tw_bsr_daily
     WHERE trade_date = _trade_date
     GROUP BY stock_id
    HAVING COUNT(*) >= _threshold
  ),
  updated AS (
    UPDATE public.tw_bsr_sync_queue q
       SET status = 'done',
           finished_at = now(),
           last_success_at = now(),
           last_error = NULL,
           next_run_at = now()
      FROM sufficient s
     WHERE q.trade_date = _trade_date
       AND q.stock_id = s.stock_id
       AND q.status IN ('pending','running')
     RETURNING q.id
  )
  SELECT COUNT(*) INTO v_done FROM updated;

  SELECT COUNT(*) INTO v_pending
    FROM public.tw_bsr_sync_queue
   WHERE trade_date = _trade_date AND status IN ('pending','running');

  RETURN QUERY SELECT COALESCE(v_done, 0)::integer, COALESCE(v_pending, 0)::integer;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.bsr_snapshot_claim(_trade_date date, _correlation_id uuid, _lease_seconds integer DEFAULT 90)
 RETURNS TABLE(claimed boolean, prev_status text, attempt_count integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_prev text;
  v_new_attempts integer;
BEGIN
  INSERT INTO public.tw_bsr_daily_snapshot_status(trade_date, status)
  VALUES (_trade_date, 'pending')
  ON CONFLICT (trade_date) DO NOTHING;

  SELECT status INTO v_prev
    FROM public.tw_bsr_daily_snapshot_status WHERE trade_date = _trade_date;

  IF v_prev IN ('ready','exhausted') THEN
    RETURN QUERY SELECT false, v_prev, 0;
    RETURN;
  END IF;

  UPDATE public.tw_bsr_daily_snapshot_status
     SET status = 'fetching',
         correlation_id = _correlation_id,
         lock_expires_at = now() + make_interval(secs => _lease_seconds),
         attempt_count = attempt_count + 1
   WHERE trade_date = _trade_date
     AND (
       status IN ('pending','partial','failed')
       OR (status = 'fetching' AND (lock_expires_at IS NULL OR lock_expires_at < now()))
     )
   RETURNING attempt_count INTO v_new_attempts;

  IF FOUND THEN
    RETURN QUERY SELECT true, v_prev, v_new_attempts;
  ELSE
    RETURN QUERY SELECT false, v_prev, 0;
  END IF;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.refresh_bsr_coverage_daily(days integer DEFAULT 10)
 RETURNS TABLE(rows_upserted integer, date_from date, date_to date)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_from date := (current_date - GREATEST(days, 1))::date;
  v_to   date := current_date;
  v_count integer := 0;
BEGIN
  WITH bsr AS (
    SELECT
      stock_id,
      trade_date,
      COUNT(*)::int AS broker_count,
      COALESCE(SUM(buy_shares), 0)::bigint AS broker_sum_shares
    FROM public.tw_bsr_daily
    WHERE trade_date >= v_from
    GROUP BY stock_id, trade_date
  ),
  joined AS (
    SELECT
      b.stock_id,
      b.trade_date,
      b.broker_count,
      b.broker_sum_shares,
      s.volume_shares AS snapshot_volume_shares,
      CASE
        WHEN s.volume_shares IS NULL OR s.volume_shares = 0 THEN NULL
        ELSE ROUND((b.broker_sum_shares::numeric / s.volume_shares::numeric) * 100, 2)
      END AS coverage_pct
    FROM bsr b
    LEFT JOIN public.daily_price_snapshots s
      ON s.symbol = b.stock_id AND s.trade_date = b.trade_date
  ),
  classified AS (
    SELECT
      j.*,
      CASE
        WHEN snapshot_volume_shares IS NULL THEN 'missing_snapshot'
        WHEN coverage_pct IS NULL THEN 'missing_snapshot'
        WHEN coverage_pct > 120 THEN 'broker_over_cover'
        WHEN coverage_pct < 60 THEN 'broker_under_cover'
        ELSE 'ok'
      END AS coverage_class
    FROM joined j
  ),
  upserted AS (
    INSERT INTO public.bsr_coverage_daily AS t
      (stock_id, trade_date, broker_count, broker_sum_shares, snapshot_volume_shares, coverage_pct, coverage_class, computed_at)
    SELECT stock_id, trade_date, broker_count, broker_sum_shares, snapshot_volume_shares, coverage_pct, coverage_class, now()
    FROM classified
    ON CONFLICT (stock_id, trade_date) DO UPDATE
      SET broker_count = EXCLUDED.broker_count,
          broker_sum_shares = EXCLUDED.broker_sum_shares,
          snapshot_volume_shares = EXCLUDED.snapshot_volume_shares,
          coverage_pct = EXCLUDED.coverage_pct,
          coverage_class = EXCLUDED.coverage_class,
          computed_at = now()
    RETURNING 1
  )
  SELECT COUNT(*)::int INTO v_count FROM upserted;

  RETURN QUERY SELECT v_count, v_from, v_to;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.reconcile_snapshot(_trade_date date)
 RETURNS TABLE(trade_date date, lane_a_status text, lane_b_status text, lane_c_status text, sealed_at timestamp with time zone, sealed_by_lane text, coverage_stocks integer, coverage_brokers integer, bsr_stocks integer, inst_stocks integer, notes text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
#variable_conflict use_column
DECLARE
  v_bsr_min_stocks constant int := 500;
  v_bsr_min_brokers_per_stock constant int := 5;
  v_inst_min_stocks constant int := 800;

  v_bsr_stocks int := 0;
  v_bsr_broker_rows int := 0;
  v_bsr_stocks_with_min int := 0;

  v_inst_stocks int := 0;
  v_inst_twse int := 0;
  v_inst_tpex int := 0;
  v_inst_t86 int := 0;

  v_lane_a text := 'pending';
  v_lane_b text := 'pending';
  v_lane_c text := 'pending';
  v_sealed_at timestamptz := NULL;
  v_sealed_by_lane text := NULL;
  v_notes text := '';
BEGIN
  -- ---- Lane A: BSR coverage ----
  SELECT
    count(DISTINCT d.stock_id),
    count(*),
    count(DISTINCT d.stock_id) FILTER (
      WHERE d.stock_id IN (
        SELECT d2.stock_id FROM public.tw_bsr_daily d2
        WHERE d2.trade_date = _trade_date
        GROUP BY d2.stock_id
        HAVING count(DISTINCT d2.broker_id) >= v_bsr_min_brokers_per_stock
      )
    )
  INTO v_bsr_stocks, v_bsr_broker_rows, v_bsr_stocks_with_min
  FROM public.tw_bsr_daily d
  WHERE d.trade_date = _trade_date;

  -- ---- Lane B/C/D: Institutional coverage ----
  SELECT count(DISTINCT i.stock_id) INTO v_inst_stocks
  FROM public.tw_institutional_daily i WHERE i.trade_date = _trade_date;

  SELECT count(DISTINCT i.stock_id) INTO v_inst_twse
  FROM public.tw_institutional_daily i WHERE i.trade_date = _trade_date AND i.source = 'twse_bfi82u';

  SELECT count(DISTINCT i.stock_id) INTO v_inst_tpex
  FROM public.tw_institutional_daily i WHERE i.trade_date = _trade_date AND i.source = 'tpex_bulk';

  SELECT count(DISTINCT i.stock_id) INTO v_inst_t86
  FROM public.tw_institutional_daily i WHERE i.trade_date = _trade_date AND i.source = 't86';

  IF v_bsr_stocks_with_min >= v_bsr_min_stocks THEN
    v_lane_a := 'sealed';
  ELSIF v_bsr_stocks_with_min > 0 THEN
    v_lane_a := 'partial';
  ELSE
    v_lane_a := 'pending';
  END IF;

  IF v_inst_stocks >= v_inst_min_stocks THEN
    v_lane_b := CASE WHEN v_inst_twse > 0 OR v_inst_stocks > 0 THEN 'sealed' ELSE 'partial' END;
    v_lane_c := CASE WHEN v_inst_tpex > 0 OR v_inst_stocks > 0 THEN 'sealed' ELSE 'partial' END;
  ELSIF v_inst_stocks > 0 THEN
    v_lane_b := 'partial';
    v_lane_c := 'partial';
  END IF;

  IF v_lane_a = 'sealed' AND v_lane_b = 'sealed' AND v_lane_c = 'sealed' THEN
    v_sealed_at := now();
    v_sealed_by_lane := 'ALL';
  ELSIF v_lane_a = 'sealed' AND v_lane_b <> 'sealed' THEN
    v_sealed_by_lane := 'A_ONLY';
    v_notes := 'BSR sealed, institutional coverage insufficient';
  ELSIF v_lane_a <> 'sealed' AND v_lane_b = 'sealed' THEN
    v_sealed_by_lane := 'BC_ONLY';
    v_notes := 'Institutional sealed, BSR coverage insufficient';
  END IF;

  INSERT INTO public.tw_bsr_daily_snapshot_status AS s (
    trade_date, status,
    lane_a_status, lane_b_status, lane_c_status,
    sealed_at, sealed_by_lane,
    coverage_stocks, coverage_brokers,
    updated_at
  ) VALUES (
    _trade_date,
    CASE WHEN v_sealed_at IS NOT NULL THEN 'ready' ELSE 'partial' END,
    v_lane_a, v_lane_b, v_lane_c,
    v_sealed_at, v_sealed_by_lane,
    v_bsr_stocks_with_min, v_bsr_broker_rows,
    now()
  )
  ON CONFLICT (trade_date) DO UPDATE SET
    lane_a_status = EXCLUDED.lane_a_status,
    lane_b_status = EXCLUDED.lane_b_status,
    lane_c_status = EXCLUDED.lane_c_status,
    sealed_at = COALESCE(s.sealed_at, EXCLUDED.sealed_at),
    sealed_by_lane = COALESCE(s.sealed_by_lane, EXCLUDED.sealed_by_lane),
    coverage_stocks = GREATEST(s.coverage_stocks, EXCLUDED.coverage_stocks),
    coverage_brokers = GREATEST(s.coverage_brokers, EXCLUDED.coverage_brokers),
    status = CASE
      WHEN s.sealed_at IS NOT NULL THEN 'ready'
      WHEN EXCLUDED.sealed_at IS NOT NULL THEN 'ready'
      ELSE EXCLUDED.status
    END,
    updated_at = now();

  RETURN QUERY SELECT
    _trade_date,
    v_lane_a, v_lane_b, v_lane_c,
    v_sealed_at, v_sealed_by_lane,
    v_bsr_stocks_with_min, v_bsr_broker_rows,
    v_bsr_stocks, v_inst_stocks,
    v_notes;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.ensure_bsr_queued(p_stock_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_elig jsonb;
  v_today date;
  v_active record;
  v_done record;
  v_failure record;
  v_next timestamptz := now();
  v_reason text;
  v_inserted integer := 0;
  v_raw_rows integer := 0;
  v_done_threshold integer := 5;
  v_fake_done boolean := false;
BEGIN
  v_elig := public.tw_bsr_eligibility(p_stock_id);
  IF COALESCE((v_elig->>'eligible')::boolean, false) = false THEN
    RETURN v_elig || jsonb_build_object('created', false, 'status', 'ineligible');
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext('bsr_queue:' || p_stock_id));

  v_today := (now() AT TIME ZONE 'Asia/Taipei')::date;

  -- 已有 active job → no-op
  SELECT status, trade_date, next_run_at INTO v_active
    FROM public.tw_bsr_sync_queue
    WHERE stock_id = p_stock_id AND status IN ('pending','running')
    ORDER BY updated_at DESC
    LIMIT 1;
  IF FOUND THEN
    RETURN jsonb_build_object(
      'eligible', true,
      'created', false,
      'status', v_active.status,
      'trade_date', v_active.trade_date,
      'next_run_at', v_active.next_run_at
    );
  END IF;

  -- 今日已 done 必須同時有足夠 raw broker rows，否則視為 fake_done，允許重新排隊。
  SELECT trade_date, updated_at INTO v_done
    FROM public.tw_bsr_sync_queue
    WHERE stock_id = p_stock_id AND trade_date = v_today AND status = 'done'
    ORDER BY updated_at DESC
    LIMIT 1;
  IF FOUND THEN
    SELECT count(*) INTO v_raw_rows
      FROM public.tw_bsr_daily
      WHERE stock_id = p_stock_id AND trade_date = v_today;

    IF v_raw_rows >= v_done_threshold THEN
      RETURN jsonb_build_object(
        'eligible', true,
        'created', false,
        'status', 'completed',
        'trade_date', v_done.trade_date,
        'completed_at', v_done.updated_at,
        'raw_rows', v_raw_rows
      );
    END IF;

    v_fake_done := true;
  END IF;

  -- 尊重 fetch_failures 冷卻
  SELECT next_retry_at, reason INTO v_failure
    FROM public.tw_bsr_fetch_failures
    WHERE stock_id = p_stock_id AND resolved_at IS NULL
    ORDER BY trade_date DESC
    LIMIT 1;
  IF FOUND AND v_failure.next_retry_at IS NOT NULL AND v_failure.next_retry_at > now() THEN
    v_next := v_failure.next_retry_at;
    v_reason := v_failure.reason;
  END IF;

  INSERT INTO public.tw_bsr_sync_queue
    (stock_id, trade_date, priority, status, next_run_at, enqueued_by, correlation_id, post_close_only)
  VALUES
    (p_stock_id, v_today, 1, 'pending', v_next, 'ensure_bsr_queued', gen_random_uuid(), false)
  ON CONFLICT DO NOTHING;
  GET DIAGNOSTICS v_inserted = ROW_COUNT;

  RETURN jsonb_build_object(
    'eligible', true,
    'created', v_inserted > 0,
    'status', 'pending',
    'trade_date', v_today,
    'next_run_at', v_next,
    'respected_backoff_reason', v_reason,
    'requeued_fake_done', v_fake_done,
    'raw_rows', v_raw_rows,
    'required_raw_rows', v_done_threshold
  );
END;
$function$
;
CREATE OR REPLACE FUNCTION public.ensure_bsr_window(p_stock_id text, p_window_days integer DEFAULT 5, p_horizon_days integer DEFAULT 14)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_today date := (now() AT TIME ZONE 'Asia/Taipei')::date;
  v_valid_dates date[];
  v_existing text[] := ARRAY[]::text[];
  v_promoted text[] := ARRAY[]::text[];
  v_newly_queued text[] := ARRAY[]::text[];
  v_d date;
  v_added int := 0;
  v_target int;
  v_probe_exhausted boolean := null;
  v_existing_row record;
BEGIN
  IF p_stock_id !~ '^[1-9][0-9]{3}$' THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'invalid_stock_id', 'stock_id', p_stock_id);
  END IF;

  IF NOT COALESCE((public.tw_bsr_eligibility(p_stock_id)->>'eligible')::boolean, false) THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'ineligible', 'stock_id', p_stock_id);
  END IF;

  SELECT COALESCE(exhausted, false) INTO v_probe_exhausted
    FROM public.tw_bsr_upstream_probe WHERE stock_id = p_stock_id;

  v_target := GREATEST(1, LEAST(60, p_window_days));

  SELECT COALESCE(array_agg(trade_date), ARRAY[]::date[])
    INTO v_valid_dates
    FROM (
      SELECT trade_date
        FROM public.tw_bsr_daily
       WHERE stock_id = p_stock_id
       GROUP BY trade_date
      HAVING COUNT(DISTINCT broker_id) >= 5
    ) x;

  v_d := v_today;
  WHILE v_added < v_target AND v_d > v_today - p_horizon_days LOOP
    IF EXTRACT(ISODOW FROM v_d) < 6 THEN
      IF v_d = ANY(v_valid_dates) THEN
        v_existing := array_append(v_existing, v_d::text);
        v_added := v_added + 1;
      ELSE
        SELECT id, status, priority
          INTO v_existing_row
          FROM public.tw_bsr_sync_queue
         WHERE stock_id = p_stock_id AND trade_date = v_d
         ORDER BY CASE status
                    WHEN 'done' THEN 4
                    WHEN 'running' THEN 1
                    WHEN 'pending' THEN 2
                    WHEN 'failed' THEN 3
                    WHEN 'skipped' THEN 3
                    ELSE 5 END, updated_at DESC
         LIMIT 1;

        IF v_existing_row.id IS NULL THEN
          BEGIN
            INSERT INTO public.tw_bsr_sync_queue
              (stock_id, trade_date, priority, status, next_run_at,
               enqueued_by, correlation_id, post_close_only)
            VALUES
              (p_stock_id, v_d, 1, 'pending', now(),
               'ensure_bsr_window', gen_random_uuid(), false);
            v_newly_queued := array_append(v_newly_queued, v_d::text);
            v_added := v_added + 1;
          EXCEPTION WHEN unique_violation THEN
            -- 併發競態：其他呼叫剛剛插入，視同已排程
            v_promoted := array_append(v_promoted, v_d::text);
            v_added := v_added + 1;
          END;
        ELSIF v_existing_row.status = 'done' THEN
          -- done 但沒有效資料 → 該日視為缺料，插入新一筆
          BEGIN
            INSERT INTO public.tw_bsr_sync_queue
              (stock_id, trade_date, priority, status, next_run_at,
               enqueued_by, correlation_id, post_close_only)
            VALUES
              (p_stock_id, v_d, 1, 'pending', now(),
               'ensure_bsr_window', gen_random_uuid(), false);
            v_newly_queued := array_append(v_newly_queued, v_d::text);
            v_added := v_added + 1;
          EXCEPTION WHEN unique_violation THEN
            v_promoted := array_append(v_promoted, v_d::text);
            v_added := v_added + 1;
          END;
        ELSE
          -- pending / running / failed / skipped → 提到最高優先、重排
          UPDATE public.tw_bsr_sync_queue
             SET priority = LEAST(priority, 1),
                 status = CASE WHEN status IN ('failed','skipped') THEN 'pending' ELSE status END,
                 next_run_at = LEAST(COALESCE(next_run_at, now()), now()),
                 updated_at = now()
           WHERE id = v_existing_row.id;
          v_promoted := array_append(v_promoted, v_d::text);
          v_added := v_added + 1;
        END IF;
      END IF;
    END IF;
    v_d := v_d - 1;
  END LOOP;

  RETURN jsonb_build_object(
    'ok', true,
    'stock_id', p_stock_id,
    'window_days', v_target,
    'today', v_today,
    'have_valid_days', array_length(v_valid_dates, 1),
    'existing_in_window', v_existing,
    'newly_queued', v_newly_queued,
    'promoted', v_promoted,
    'upstream_exhausted', COALESCE(v_probe_exhausted, false)
  );
END;
$function$
;
CREATE OR REPLACE FUNCTION public.is_tw_trading_day(_d date)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXTRACT(DOW FROM _d) NOT IN (0, 6)
     AND NOT EXISTS (SELECT 1 FROM public.tw_market_holidays h WHERE h.trade_date = _d);
$function$
;

