#!/usr/bin/env python3
"""R0-C/D: build clone cutover script.
Ownership rule: app_ledger objects -> ledger_owner; DDL/ACL on pre-existing public.* -> migration runner (postgres)."""
import re, sys
src = ''
for f in ['db/e0/01_ledger.sql','db/e0/02_canonical.sql','db/e0/03_projection.sql']:
    src += open(f).read() + '\n'
# statement split on ';' at line ends outside $$ blocks
stmts, buf, dollar = [], [], False
for line in src.split('\n'):
    if line.count('$$') % 2 == 1: dollar = not dollar
    buf.append(line)
    if not dollar and line.rstrip().endswith(';'):
        stmts.append('\n'.join(buf)); buf = []
if buf: stmts.append('\n'.join(buf))

RUNNER = re.compile(r'^\s*(CREATE\s+TRIGGER|REVOKE|GRANT|ALTER\s+TABLE\s+public\.)', re.I|re.M)
out = ['-- R0 clone cutover (generated by db/r0/build_cutover.py)', 'SET ROLE ledger_owner;']
mode = 'owner'
for s in stmts:
    if not s.strip(): continue
    head = s.strip()
    needs_runner = bool(RUNNER.match(head)) and ('public.' in head or 'IN SCHEMA' in head.upper())
    want = 'runner' if needs_runner else 'owner'
    if want != mode:
        out.append('RESET ROLE;' if want=='runner' else 'SET ROLE ledger_owner;')
        mode = want
    out.append(s)
out.append('RESET ROLE;')
open('/tmp/r0clone/cutover.sql','w').write('\n'.join(out)+'\n')
print('statements:', len(stmts))
