// M-3c: End-to-End Auth Contract for every classified edge function.
//
// Reads docs/security/edge-function-auth-matrix.md at test time (single source
// of truth generated by scripts/audit-edge-fn-auth.mjs) and asserts:
//
//   - class = user   → POST without Authorization must return 401
//   - class = cron   → POST without X-Cron-Key must return 403
//   - class = webhook/public → not covered here (provider-specific)
//
// This is a live contract test hitting the deployed functions. It relies on
// _shared/test_utils.ts loading VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY
// from .env. Set SKIP_AUTH_CONTRACT_E2E=1 to skip locally.
//
// Run:
//   deno test --allow-net --allow-env --allow-read --no-check \
//     supabase/functions/_shared/authContract_e2e_test.ts

import { assert } from 'https://deno.land/std@0.224.0/assert/mod.ts';
import { SUPABASE_URL, SUPABASE_ANON_KEY, fnUrl, drain } from './test_utils.ts';

const SKIP = Deno.env.get('SKIP_AUTH_CONTRACT_E2E') === '1';
const CONCURRENCY = 8;
const MATRIX_PATH = new URL('../../../docs/security/edge-function-auth-matrix.md', import.meta.url);

type Row = { name: string; klass: 'user' | 'cron' | 'webhook' | 'public' };

async function loadMatrix(): Promise<Row[]> {
  const txt = await Deno.readTextFile(MATRIX_PATH);
  const rows: Row[] = [];
  for (const line of txt.split('\n')) {
    // rows look like:  | `fn-name` | user | ✅ |
    const m = line.match(/^\|\s*`([a-z0-9-]+)`\s*\|\s*(user|cron|webhook|public)\s*\|/i);
    if (m) rows.push({ name: m[1], klass: m[2].toLowerCase() as Row['klass'] });
  }
  return rows;
}

async function poke(url: string, headers: HeadersInit): Promise<number> {
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'content-type': 'application/json', ...headers },
    body: '{}',
  });
  await drain(res);
  return res.status;
}

async function runBatch<T>(items: T[], size: number, fn: (t: T) => Promise<void>) {
  for (let i = 0; i < items.length; i += size) {
    await Promise.all(items.slice(i, i + size).map(fn));
  }
}

Deno.test({
  name: 'e2e auth contract — every user function rejects missing bearer with 401',
  ignore: SKIP,
  sanitizeOps: false,
  sanitizeResources: false,
  async fn() {
    assert(SUPABASE_URL && SUPABASE_ANON_KEY, 'missing supabase env');
    const rows = (await loadMatrix()).filter((r) => r.klass === 'user');
    assert(rows.length > 0, 'matrix had no user rows');

    const failures: string[] = [];
    await runBatch(rows, CONCURRENCY, async ({ name }) => {
      // Only apikey, no Authorization — guard must respond 401.
      const status = await poke(fnUrl(name), { apikey: SUPABASE_ANON_KEY });
      if (status !== 401) failures.push(`${name} → ${status} (expected 401)`);
    });

    if (failures.length) {
      throw new Error(
        `user-class contract violations (${failures.length}/${rows.length}):\n  ` +
          failures.join('\n  '),
      );
    }
  },
});

Deno.test({
  name: 'e2e auth contract — every cron function rejects missing X-Cron-Key with 403',
  ignore: SKIP,
  sanitizeOps: false,
  sanitizeResources: false,
  async fn() {
    const rows = (await loadMatrix()).filter((r) => r.klass === 'cron');
    assert(rows.length > 0, 'matrix had no cron rows');

    const failures: string[] = [];
    await runBatch(rows, CONCURRENCY, async ({ name }) => {
      // Send an anon Authorization so the platform accepts the request,
      // but no X-Cron-Key → guard must respond 403 (or 503 if secret missing,
      // which itself is a valid guard signal).
      const status = await poke(fnUrl(name), {
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
      });
      if (status !== 403 && status !== 503) {
        failures.push(`${name} → ${status} (expected 403 or 503)`);
      }
    });

    if (failures.length) {
      throw new Error(
        `cron-class contract violations (${failures.length}/${rows.length}):\n  ` +
          failures.join('\n  '),
      );
    }
  },
});

Deno.test({
  name: 'e2e auth contract — bogus X-Cron-Key still rejected with 403',
  ignore: SKIP,
  sanitizeOps: false,
  sanitizeResources: false,
  async fn() {
    const rows = (await loadMatrix()).filter((r) => r.klass === 'cron');
    // Sample first 5 to keep this fast; the exhaustive check above already
    // covers the "missing key" branch — this one just proves that a wrong
    // value doesn't sneak through on any handler.
    const sample = rows.slice(0, 5);
    const failures: string[] = [];
    await runBatch(sample, CONCURRENCY, async ({ name }) => {
      const status = await poke(fnUrl(name), {
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
        'X-Cron-Key': 'definitely-not-the-secret',
      });
      if (status !== 403 && status !== 503) {
        failures.push(`${name} → ${status} (expected 403 or 503)`);
      }
    });
    if (failures.length) {
      throw new Error(`bogus-key contract violations:\n  ` + failures.join('\n  '));
    }
  },
});
