-- auth schema surface referenced by public objects
-- generated by s0_backup_bundle.py from production catalog (read-only, schema only)

CREATE SCHEMA IF NOT EXISTS auth;
GRANT USAGE ON SCHEMA auth TO anon, authenticated, service_role;
DO $$ BEGIN CREATE TYPE auth.aal_level AS ENUM ('aal1','aal2','aal3'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE auth.code_challenge_method AS ENUM ('s256','plain'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE auth.factor_status AS ENUM ('unverified','verified'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE auth.factor_type AS ENUM ('totp','webauthn','phone'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE auth.oauth_authorization_status AS ENUM ('pending','approved','denied','expired'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE auth.oauth_client_type AS ENUM ('public','confidential'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE auth.oauth_registration_type AS ENUM ('dynamic','manual'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE auth.oauth_response_type AS ENUM ('code'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE auth.one_time_token_type AS ENUM ('confirmation_token','reauthentication_token','recovery_token','email_change_token_new','email_change_token_current','phone_change_token'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS auth.audit_log_entries (instance_id uuid, id uuid NOT NULL, payload json, created_at timestamp with time zone, ip_address character varying(64) NOT NULL);
CREATE TABLE IF NOT EXISTS auth.custom_oauth_providers (id uuid NOT NULL, provider_type text NOT NULL, identifier text NOT NULL, name text NOT NULL, client_id text NOT NULL, client_secret text NOT NULL, acceptable_client_ids text[] NOT NULL, scopes text[] NOT NULL, pkce_enabled boolean NOT NULL, attribute_mapping jsonb NOT NULL, authorization_params jsonb NOT NULL, enabled boolean NOT NULL, email_optional boolean NOT NULL, issuer text, discovery_url text, skip_nonce_check boolean NOT NULL, cached_discovery jsonb, discovery_cached_at timestamp with time zone, authorization_url text, token_url text, userinfo_url text, jwks_uri text, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL, custom_claims_allowlist text[] NOT NULL);
CREATE TABLE IF NOT EXISTS auth.flow_state (id uuid NOT NULL, user_id uuid, auth_code text, code_challenge_method auth.code_challenge_method, code_challenge text, provider_type text NOT NULL, provider_access_token text, provider_refresh_token text, created_at timestamp with time zone, updated_at timestamp with time zone, authentication_method text NOT NULL, auth_code_issued_at timestamp with time zone, invite_token text, referrer text, oauth_client_state_id uuid, linking_target_id uuid, email_optional boolean NOT NULL);
CREATE TABLE IF NOT EXISTS auth.identities (provider_id text NOT NULL, user_id uuid NOT NULL, identity_data jsonb NOT NULL, provider text NOT NULL, last_sign_in_at timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone, email text, id uuid NOT NULL);
CREATE TABLE IF NOT EXISTS auth.instances (id uuid NOT NULL, uuid uuid, raw_base_config text, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS auth.mfa_amr_claims (session_id uuid NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL, authentication_method text NOT NULL, id uuid NOT NULL);
CREATE TABLE IF NOT EXISTS auth.mfa_challenges (id uuid NOT NULL, factor_id uuid NOT NULL, created_at timestamp with time zone NOT NULL, verified_at timestamp with time zone, ip_address inet NOT NULL, otp_code text, web_authn_session_data jsonb);
CREATE TABLE IF NOT EXISTS auth.mfa_factors (id uuid NOT NULL, user_id uuid NOT NULL, friendly_name text, factor_type auth.factor_type NOT NULL, status auth.factor_status NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL, secret text, phone text, last_challenged_at timestamp with time zone, web_authn_credential jsonb, web_authn_aaguid uuid, last_webauthn_challenge_data jsonb);
CREATE TABLE IF NOT EXISTS auth.oauth_authorizations (id uuid NOT NULL, authorization_id text NOT NULL, client_id uuid NOT NULL, user_id uuid, redirect_uri text NOT NULL, scope text NOT NULL, state text, resource text, code_challenge text, code_challenge_method auth.code_challenge_method, response_type auth.oauth_response_type NOT NULL, status auth.oauth_authorization_status NOT NULL, authorization_code text, created_at timestamp with time zone NOT NULL, expires_at timestamp with time zone NOT NULL, approved_at timestamp with time zone, nonce text);
CREATE TABLE IF NOT EXISTS auth.oauth_client_states (id uuid NOT NULL, provider_type text NOT NULL, code_verifier text, created_at timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS auth.oauth_clients (id uuid NOT NULL, client_secret_hash text, registration_type auth.oauth_registration_type NOT NULL, redirect_uris text NOT NULL, grant_types text NOT NULL, client_name text, client_uri text, logo_uri text, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL, deleted_at timestamp with time zone, client_type auth.oauth_client_type NOT NULL, token_endpoint_auth_method text NOT NULL);
CREATE TABLE IF NOT EXISTS auth.oauth_consents (id uuid NOT NULL, user_id uuid NOT NULL, client_id uuid NOT NULL, scopes text NOT NULL, granted_at timestamp with time zone NOT NULL, revoked_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS auth.one_time_tokens (id uuid NOT NULL, user_id uuid NOT NULL, token_type auth.one_time_token_type NOT NULL, token_hash text NOT NULL, relates_to text NOT NULL, created_at timestamp without time zone NOT NULL, updated_at timestamp without time zone NOT NULL);
CREATE TABLE IF NOT EXISTS auth.refresh_tokens (instance_id uuid, id bigint NOT NULL, token character varying(255), user_id character varying(255), revoked boolean, created_at timestamp with time zone, updated_at timestamp with time zone, parent character varying(255), session_id uuid);
CREATE TABLE IF NOT EXISTS auth.saml_providers (id uuid NOT NULL, sso_provider_id uuid NOT NULL, entity_id text NOT NULL, metadata_xml text NOT NULL, metadata_url text, attribute_mapping jsonb, created_at timestamp with time zone, updated_at timestamp with time zone, name_id_format text);
CREATE TABLE IF NOT EXISTS auth.saml_relay_states (id uuid NOT NULL, sso_provider_id uuid NOT NULL, request_id text NOT NULL, for_email text, redirect_to text, created_at timestamp with time zone, updated_at timestamp with time zone, flow_state_id uuid);
CREATE TABLE IF NOT EXISTS auth.schema_migrations (version character varying(255) NOT NULL);
CREATE TABLE IF NOT EXISTS auth.sessions (id uuid NOT NULL, user_id uuid NOT NULL, created_at timestamp with time zone, updated_at timestamp with time zone, factor_id uuid, aal auth.aal_level, not_after timestamp with time zone, refreshed_at timestamp without time zone, user_agent text, ip inet, tag text, oauth_client_id uuid, refresh_token_hmac_key text, refresh_token_counter bigint, scopes text);
CREATE TABLE IF NOT EXISTS auth.sso_domains (id uuid NOT NULL, sso_provider_id uuid NOT NULL, domain text NOT NULL, created_at timestamp with time zone, updated_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS auth.sso_providers (id uuid NOT NULL, resource_id text, created_at timestamp with time zone, updated_at timestamp with time zone, disabled boolean);
CREATE TABLE IF NOT EXISTS auth.users (instance_id uuid, id uuid NOT NULL, aud character varying(255), role character varying(255), email character varying(255), encrypted_password character varying(255), email_confirmed_at timestamp with time zone, invited_at timestamp with time zone, confirmation_token character varying(255), confirmation_sent_at timestamp with time zone, recovery_token character varying(255), recovery_sent_at timestamp with time zone, email_change_token_new character varying(255), email_change character varying(255), email_change_sent_at timestamp with time zone, last_sign_in_at timestamp with time zone, raw_app_meta_data jsonb, raw_user_meta_data jsonb, is_super_admin boolean, created_at timestamp with time zone, updated_at timestamp with time zone, phone text, phone_confirmed_at timestamp with time zone, phone_change text, phone_change_token character varying(255), phone_change_sent_at timestamp with time zone, confirmed_at timestamp with time zone, email_change_token_current character varying(255), email_change_confirm_status smallint, banned_until timestamp with time zone, reauthentication_token character varying(255), reauthentication_sent_at timestamp with time zone, is_sso_user boolean NOT NULL, deleted_at timestamp with time zone, is_anonymous boolean NOT NULL);
CREATE TABLE IF NOT EXISTS auth.webauthn_challenges (id uuid NOT NULL, user_id uuid, challenge_type text NOT NULL, session_data jsonb NOT NULL, created_at timestamp with time zone NOT NULL, expires_at timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS auth.webauthn_credentials (id uuid NOT NULL, user_id uuid NOT NULL, credential_id bytea NOT NULL, public_key bytea NOT NULL, attestation_type text NOT NULL, aaguid uuid, sign_count bigint NOT NULL, transports jsonb NOT NULL, backup_eligible boolean NOT NULL, backed_up boolean NOT NULL, friendly_name text NOT NULL, created_at timestamp with time zone NOT NULL, updated_at timestamp with time zone NOT NULL, last_used_at timestamp with time zone);
ALTER TABLE auth.audit_log_entries ADD CONSTRAINT audit_log_entries_pkey PRIMARY KEY (id);
ALTER TABLE auth.custom_oauth_providers ADD CONSTRAINT custom_oauth_providers_identifier_key UNIQUE (identifier);
ALTER TABLE auth.custom_oauth_providers ADD CONSTRAINT custom_oauth_providers_pkey PRIMARY KEY (id);
ALTER TABLE auth.flow_state ADD CONSTRAINT flow_state_pkey PRIMARY KEY (id);
ALTER TABLE auth.identities ADD CONSTRAINT identities_pkey PRIMARY KEY (id);
ALTER TABLE auth.identities ADD CONSTRAINT identities_provider_id_provider_unique UNIQUE (provider_id, provider);
ALTER TABLE auth.instances ADD CONSTRAINT instances_pkey PRIMARY KEY (id);
ALTER TABLE auth.mfa_amr_claims ADD CONSTRAINT amr_id_pk PRIMARY KEY (id);
ALTER TABLE auth.mfa_amr_claims ADD CONSTRAINT mfa_amr_claims_session_id_authentication_method_pkey UNIQUE (session_id, authentication_method);
ALTER TABLE auth.mfa_challenges ADD CONSTRAINT mfa_challenges_pkey PRIMARY KEY (id);
ALTER TABLE auth.mfa_factors ADD CONSTRAINT mfa_factors_last_challenged_at_key UNIQUE (last_challenged_at);
ALTER TABLE auth.mfa_factors ADD CONSTRAINT mfa_factors_pkey PRIMARY KEY (id);
ALTER TABLE auth.oauth_authorizations ADD CONSTRAINT oauth_authorizations_authorization_code_key UNIQUE (authorization_code);
ALTER TABLE auth.oauth_authorizations ADD CONSTRAINT oauth_authorizations_authorization_id_key UNIQUE (authorization_id);
ALTER TABLE auth.oauth_authorizations ADD CONSTRAINT oauth_authorizations_pkey PRIMARY KEY (id);
ALTER TABLE auth.oauth_client_states ADD CONSTRAINT oauth_client_states_pkey PRIMARY KEY (id);
ALTER TABLE auth.oauth_clients ADD CONSTRAINT oauth_clients_pkey PRIMARY KEY (id);
ALTER TABLE auth.oauth_consents ADD CONSTRAINT oauth_consents_pkey PRIMARY KEY (id);
ALTER TABLE auth.oauth_consents ADD CONSTRAINT oauth_consents_user_client_unique UNIQUE (user_id, client_id);
ALTER TABLE auth.one_time_tokens ADD CONSTRAINT one_time_tokens_pkey PRIMARY KEY (id);
ALTER TABLE auth.refresh_tokens ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);
ALTER TABLE auth.refresh_tokens ADD CONSTRAINT refresh_tokens_token_unique UNIQUE (token);
ALTER TABLE auth.saml_providers ADD CONSTRAINT saml_providers_entity_id_key UNIQUE (entity_id);
ALTER TABLE auth.saml_providers ADD CONSTRAINT saml_providers_pkey PRIMARY KEY (id);
ALTER TABLE auth.saml_relay_states ADD CONSTRAINT saml_relay_states_pkey PRIMARY KEY (id);
ALTER TABLE auth.schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);
ALTER TABLE auth.sessions ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);
ALTER TABLE auth.sso_domains ADD CONSTRAINT sso_domains_pkey PRIMARY KEY (id);
ALTER TABLE auth.sso_providers ADD CONSTRAINT sso_providers_pkey PRIMARY KEY (id);
ALTER TABLE auth.users ADD CONSTRAINT users_phone_key UNIQUE (phone);
ALTER TABLE auth.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE auth.webauthn_challenges ADD CONSTRAINT webauthn_challenges_pkey PRIMARY KEY (id);
ALTER TABLE auth.webauthn_credentials ADD CONSTRAINT webauthn_credentials_pkey PRIMARY KEY (id);
CREATE OR REPLACE FUNCTION auth.email()
 RETURNS text
 LANGUAGE sql
 STABLE
AS $function$
  select 
  coalesce(
    nullif(current_setting('request.jwt.claim.email', true), ''),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'email')
  )::text
$function$
;
CREATE OR REPLACE FUNCTION auth.jwt()
 RETURNS jsonb
 LANGUAGE sql
 STABLE
AS $function$
  select 
    coalesce(
        nullif(current_setting('request.jwt.claim', true), ''),
        nullif(current_setting('request.jwt.claims', true), '')
    )::jsonb
$function$
;
CREATE OR REPLACE FUNCTION auth.role()
 RETURNS text
 LANGUAGE sql
 STABLE
AS $function$
  select 
  coalesce(
    nullif(current_setting('request.jwt.claim.role', true), ''),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role')
  )::text
$function$
;
CREATE OR REPLACE FUNCTION auth.uid()
 RETURNS uuid
 LANGUAGE sql
 STABLE
AS $function$
  select 
  coalesce(
    nullif(current_setting('request.jwt.claim.sub', true), ''),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub')
  )::uuid
$function$
;
GRANT SELECT ON ALL TABLES IN SCHEMA auth TO service_role;
