-- public tables (schema only, no row data) + views
-- generated by s0_backup_bundle.py from production catalog (read-only, schema only)

CREATE TABLE IF NOT EXISTS public.account_link_codes (id uuid DEFAULT gen_random_uuid() NOT NULL, code text NOT NULL, initiator_user_id uuid NOT NULL, initiator_identity text NOT NULL, initiator_email text, initiator_line_user_id text, expires_at timestamp with time zone NOT NULL, consumed_at timestamp with time zone, consumed_by_user_id uuid, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.account_merges (id uuid DEFAULT gen_random_uuid() NOT NULL, primary_user_id uuid NOT NULL, secondary_user_id uuid NOT NULL, primary_identity text, secondary_identity text, primary_email text, secondary_email text, moved_counts jsonb DEFAULT '{}'::jsonb NOT NULL, performed_by uuid, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.ad_spend (id uuid DEFAULT gen_random_uuid() NOT NULL, utm_source text, utm_medium text, utm_campaign text NOT NULL, yyyymm text NOT NULL, spend_amount integer DEFAULT 0 NOT NULL, note text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.admin_view_as_sessions (id uuid DEFAULT gen_random_uuid() NOT NULL, admin_user_id uuid NOT NULL, target_user_id uuid NOT NULL, token text NOT NULL, expires_at timestamp with time zone NOT NULL, revoked_at timestamp with time zone, consumed_at timestamp with time zone, ip text, user_agent text, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.ai_gateway_usage_logs (id uuid DEFAULT gen_random_uuid() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, user_id uuid, expert_id uuid, expert_slug text, endpoint text NOT NULL, model text NOT NULL, run_id text, log_id text, correlation_id text, prompt_tokens integer, completion_tokens integer, total_tokens integer, duration_ms integer, finish_reason text, cost_usd numeric(12,6), meta jsonb);
CREATE TABLE IF NOT EXISTS public.announcements (id uuid DEFAULT gen_random_uuid() NOT NULL, title text NOT NULL, content text NOT NULL, status announcement_status DEFAULT 'draft'::announcement_status NOT NULL, published_at timestamp with time zone, created_by uuid, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.audit_logs (id uuid DEFAULT gen_random_uuid() NOT NULL, actor_id uuid, action text NOT NULL, target_type text, target_id uuid, detail jsonb DEFAULT '{}'::jsonb, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.backfill_job_queue (id bigint DEFAULT nextval('backfill_job_queue_id_seq'::regclass) NOT NULL, dataset text NOT NULL, stock_id text NOT NULL, start_date date NOT NULL, end_date date NOT NULL, priority_score integer DEFAULT 0 NOT NULL, status text DEFAULT 'pending'::text NOT NULL, source_hint text DEFAULT 'finmind'::text NOT NULL, attempts integer DEFAULT 0 NOT NULL, max_attempts integer DEFAULT 3 NOT NULL, next_run_at timestamp with time zone DEFAULT now() NOT NULL, correlation_id text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, last_error text, payload jsonb, fulfilled_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS public.bsr_coverage_daily (stock_id text NOT NULL, trade_date date NOT NULL, broker_count integer DEFAULT 0 NOT NULL, broker_sum_shares bigint DEFAULT 0 NOT NULL, snapshot_volume_shares bigint, coverage_pct numeric(8,2), coverage_class text DEFAULT 'unknown'::text NOT NULL, computed_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.checkup_analysis_jobs (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, status text DEFAULT 'queued'::text NOT NULL, holdings_snapshot jsonb, result_summary jsonb, error_text text, started_at timestamp with time zone, finished_at timestamp with time zone, notified_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, prompts_payload jsonb, raw_responses jsonb);
CREATE TABLE IF NOT EXISTS public.checkup_daily_reminders (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, reminded_on date NOT NULL, channels jsonb DEFAULT '{}'::jsonb NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.checkup_entitlements (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, amount integer NOT NULL, reason text NOT NULL, source text, expires_at timestamp with time zone, is_active boolean DEFAULT true NOT NULL, granted_by uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.checkup_knowledge_candidates (id uuid DEFAULT gen_random_uuid() NOT NULL, category text NOT NULL, item_id text, title text NOT NULL, fact text NOT NULL, interpretation text, action text, lessons text, return_pct numeric, outcome text, confidence numeric DEFAULT 0.6, tags text[] DEFAULT '{}'::text[], trigger_condition jsonb, expected_outcome jsonb, industry_tags text[] DEFAULT '{}'::text[], time_horizon text, source_type text DEFAULT 'ai_draft'::text NOT NULL, source_meta jsonb DEFAULT '{}'::jsonb, status text DEFAULT 'pending'::text NOT NULL, reviewer_note text, reviewed_by uuid, reviewed_at timestamp with time zone, created_by uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.checkup_knowledge_hits (id uuid DEFAULT gen_random_uuid() NOT NULL, knowledge_item_id uuid NOT NULL, user_id uuid, stock_code text, context text, confidence numeric, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.checkup_knowledge_items (id uuid DEFAULT gen_random_uuid() NOT NULL, category text NOT NULL, item_id text NOT NULL, title text NOT NULL, fact text NOT NULL, interpretation text, action text, lessons text, return_pct numeric, outcome text, confidence numeric DEFAULT 0.75, tags text[] DEFAULT '{}'::text[], is_active boolean DEFAULT true, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), version integer DEFAULT 1 NOT NULL, trigger_condition jsonb, expected_outcome jsonb, win_rate numeric, sample_size integer DEFAULT 0 NOT NULL, last_validated_at timestamp with time zone, source_type text DEFAULT 'editorial'::text NOT NULL, industry_tags text[] DEFAULT '{}'::text[] NOT NULL, time_horizon text, backtestable boolean DEFAULT false NOT NULL, archived_at timestamp with time zone, parent_item_id uuid, backtest_stats jsonb DEFAULT '{}'::jsonb, backtest_run_at timestamp with time zone, universe_size integer, lifecycle_status text DEFAULT 'active'::text NOT NULL, rescue_started_at timestamp with time zone, rescue_attempts integer DEFAULT 0 NOT NULL, candidate_observed_since timestamp with time zone, archived_reason text);
CREATE TABLE IF NOT EXISTS public.checkup_knowledge_validations (id uuid DEFAULT gen_random_uuid() NOT NULL, knowledge_item_id uuid NOT NULL, hit_id uuid, stock_code text, evaluated_at timestamp with time zone DEFAULT now() NOT NULL, horizon_days integer, expected_direction text, actual_change_pct numeric, is_correct boolean, details jsonb DEFAULT '{}'::jsonb, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.checkup_plans (id uuid DEFAULT gen_random_uuid() NOT NULL, tier text NOT NULL, name text NOT NULL, description text, price_monthly integer NOT NULL, price_yearly integer NOT NULL, monthly_quota integer NOT NULL, features jsonb DEFAULT '[]'::jsonb NOT NULL, is_active boolean DEFAULT true NOT NULL, sort_order integer DEFAULT 0 NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, quota_period text DEFAULT 'month'::text NOT NULL);
CREATE TABLE IF NOT EXISTS public.checkup_prediction_accuracy (id uuid DEFAULT gen_random_uuid() NOT NULL, event_id text NOT NULL, event_type text, pred text NOT NULL, actual text NOT NULL, was_correct boolean DEFAULT false NOT NULL, reviewed_at timestamp with time zone DEFAULT now() NOT NULL, user_id uuid);
CREATE TABLE IF NOT EXISTS public.checkup_price_misses (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid, symbol text NOT NULL, reason text NOT NULL, attempts integer DEFAULT 1 NOT NULL, last_error text, first_seen_at timestamp with time zone DEFAULT now() NOT NULL, last_seen_at timestamp with time zone DEFAULT now() NOT NULL, resolved_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS public.checkup_storage (key text NOT NULL, data jsonb DEFAULT '{}'::jsonb NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, user_id uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL);
CREATE TABLE IF NOT EXISTS public.checkup_subscriptions (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, plan_id uuid NOT NULL, billing_cycle text NOT NULL, status subscription_status DEFAULT 'active'::subscription_status NOT NULL, auto_renew boolean DEFAULT false NOT NULL, started_at timestamp with time zone DEFAULT now() NOT NULL, expires_at timestamp with time zone, canceled_at timestamp with time zone, provider_id uuid, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.checkup_trade_memos (id uuid DEFAULT gen_random_uuid() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, trade_date text, trade_time text, action text, code text, name text, qty numeric, price numeric, qa jsonb DEFAULT '[]'::jsonb, user_id uuid NOT NULL);
CREATE TABLE IF NOT EXISTS public.checkup_usage (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, used_at timestamp with time zone DEFAULT now() NOT NULL, kind text DEFAULT 'analysis'::text NOT NULL);
CREATE TABLE IF NOT EXISTS public.chips_prefetch_targets (code text NOT NULL, source text DEFAULT 'manual'::text NOT NULL, active boolean DEFAULT true NOT NULL, supported boolean DEFAULT true NOT NULL, reason text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.conversions (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, visitor_id text, order_kind text NOT NULL, order_id uuid, utm_source text, utm_medium text, utm_campaign text, utm_content text, ref_code text, channel text DEFAULT 'direct'::text NOT NULL, gross_amount integer DEFAULT 0 NOT NULL, platform_amount integer DEFAULT 0 NOT NULL, expert_amount integer DEFAULT 0 NOT NULL, occurred_at timestamp with time zone DEFAULT now() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.cron_dispatch_log (id bigint DEFAULT nextval('cron_dispatch_log_id_seq'::regclass) NOT NULL, jobname text NOT NULL, request_id bigint, dispatched_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.crypto_symbol_map (symbol text NOT NULL, coingecko_id text NOT NULL, binance_pair text, display_name text NOT NULL, is_active boolean DEFAULT true NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.current_prices (symbol text NOT NULL, name text, price numeric, change_value numeric, change_percent numeric, yesterday_close numeric, open_price numeric, high_price numeric, low_price numeric, limit_up numeric, limit_down numeric, volume integer, tick_volume integer, best_bid numeric, best_ask numeric, pushed_at timestamp with time zone DEFAULT now(), currency text DEFAULT 'TWD'::text NOT NULL, market text DEFAULT 'TW'::text NOT NULL, asset_class text DEFAULT 'tw_stock'::text NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, writer text);
CREATE TABLE IF NOT EXISTS public.daily_price_snapshots (id uuid DEFAULT gen_random_uuid() NOT NULL, symbol text NOT NULL, trade_date date NOT NULL, close_price numeric, yesterday_close numeric, change_percent numeric, is_limit_up boolean DEFAULT false NOT NULL, limit_up_price numeric, volume bigint, created_at timestamp with time zone DEFAULT now() NOT NULL, open_price numeric, high_price numeric, low_price numeric, volume_ma5 numeric, market text DEFAULT 'TW'::text NOT NULL, volume_unit text, volume_shares bigint);
CREATE TABLE IF NOT EXISTS public.data_source_health (source text NOT NULL, ok_count_10m integer DEFAULT 0 NOT NULL, fail_count_10m integer DEFAULT 0 NOT NULL, p95_latency_ms integer, consecutive_failures integer DEFAULT 0 NOT NULL, circuit_state text DEFAULT 'closed'::text NOT NULL, disabled_until timestamp with time zone, last_error_code text, last_success_at timestamp with time zone, last_failure_at timestamp with time zone, updated_at timestamp with time zone DEFAULT now() NOT NULL, upstream_quota_remaining integer, upstream_quota_limit integer, upstream_quota_reset_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS public.data_source_refresh_logs (id uuid DEFAULT gen_random_uuid() NOT NULL, source_key text NOT NULL, triggered_by uuid, status text NOT NULL, started_at timestamp with time zone DEFAULT now() NOT NULL, finished_at timestamp with time zone, duration_ms integer, row_count integer, error_message text, metadata jsonb, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.edge_boot_events (id bigint NOT NULL, fn text NOT NULL, boot_at timestamp with time zone DEFAULT now() NOT NULL, region text, deployment_id text);
CREATE TABLE IF NOT EXISTS public.edge_function_auth_events (id bigint DEFAULT nextval('edge_function_auth_events_id_seq'::regclass) NOT NULL, fn_name text NOT NULL, auth_class text NOT NULL, outcome integer NOT NULL, code text, reason text, caller_ip text, correlation_id text, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.expert_ai_access_logs (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid, expert_id uuid, expert_slug text, decision text NOT NULL, rule text NOT NULL, subscription_status text, plan_id uuid, plan_type text, quota_used integer, quota_limit integer, meta jsonb, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.expert_ai_conversations (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, expert_id uuid NOT NULL, title text, last_message_at timestamp with time zone DEFAULT now() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.expert_ai_fewshots (id uuid DEFAULT gen_random_uuid() NOT NULL, expert_id uuid NOT NULL, question text NOT NULL, answer text NOT NULL, status text DEFAULT 'pending'::text NOT NULL, sort_order integer DEFAULT 0 NOT NULL, created_by uuid, reviewed_by uuid, reviewed_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.expert_ai_index_runs (id uuid DEFAULT gen_random_uuid() NOT NULL, expert_id uuid NOT NULL, status text DEFAULT 'running'::text NOT NULL, trigger_source text DEFAULT 'manual'::text NOT NULL, total_chunks integer, indexed_chunks integer DEFAULT 0 NOT NULL, embed_failures integer DEFAULT 0 NOT NULL, error_message text, started_at timestamp with time zone DEFAULT now() NOT NULL, finished_at timestamp with time zone, duration_ms integer, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.expert_ai_messages (id uuid DEFAULT gen_random_uuid() NOT NULL, conversation_id uuid NOT NULL, role text NOT NULL, content text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.expert_ai_personas (expert_id uuid NOT NULL, system_prompt text, tone text[] DEFAULT '{}'::text[], forbidden_topics text[] DEFAULT '{}'::text[], disclaimer text, model text DEFAULT 'openai/gpt-5'::text NOT NULL, updated_by uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.expert_ai_training_sessions (id uuid DEFAULT gen_random_uuid() NOT NULL, expert_id uuid NOT NULL, signal_id uuid, week_start date, status text DEFAULT 'open'::text NOT NULL, ai_questions jsonb DEFAULT '[]'::jsonb NOT NULL, answers jsonb DEFAULT '[]'::jsonb NOT NULL, suggested_knowledge jsonb DEFAULT '[]'::jsonb NOT NULL, suggested_journal_edits jsonb DEFAULT '[]'::jsonb NOT NULL, started_at timestamp with time zone DEFAULT now() NOT NULL, completed_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, revisions jsonb DEFAULT '[]'::jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS public.expert_knowledge_chunks (id uuid DEFAULT gen_random_uuid() NOT NULL, expert_id uuid NOT NULL, source_type text NOT NULL, source_id uuid, content text NOT NULL, embedding vector(1536) NOT NULL, metadata jsonb DEFAULT '{}'::jsonb NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, is_manual boolean DEFAULT false NOT NULL, status text DEFAULT 'approved'::text NOT NULL, title text, created_by uuid, reviewed_by uuid, reviewed_at timestamp with time zone, training_session_id uuid, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.expert_limit_up_hits (id uuid DEFAULT gen_random_uuid() NOT NULL, expert_id uuid NOT NULL, symbol text NOT NULL, instrument text, trade_date date NOT NULL, close_price numeric, entry_price numeric, trade_record_id uuid, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.expert_line_channels (id uuid DEFAULT gen_random_uuid() NOT NULL, expert_id uuid NOT NULL, channel_id text NOT NULL, channel_access_token text NOT NULL, channel_name text, is_active boolean DEFAULT true NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, line_oa_id text, qr_code_url text);
CREATE TABLE IF NOT EXISTS public.expert_plans (id uuid DEFAULT gen_random_uuid() NOT NULL, expert_id uuid NOT NULL, name text NOT NULL, description text, plan_type plan_type NOT NULL, price_monthly integer DEFAULT 0 NOT NULL, price_yearly integer, features jsonb DEFAULT '[]'::jsonb, is_active boolean DEFAULT false NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, review_status plan_review_status DEFAULT 'draft'::plan_review_status NOT NULL, review_note text, reviewed_by uuid, reviewed_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS public.expert_reason_templates (id uuid DEFAULT gen_random_uuid() NOT NULL, expert_id uuid NOT NULL, title text NOT NULL, content text NOT NULL, sort_order integer DEFAULT 0 NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.expert_signal_legs (id uuid DEFAULT gen_random_uuid() NOT NULL, signal_id uuid NOT NULL, leg_index integer DEFAULT 0 NOT NULL, occ_symbol text, underlying text NOT NULL, expiry date, right_type text, strike numeric, side text DEFAULT 'long'::text NOT NULL, ratio integer DEFAULT 1 NOT NULL, leg_price numeric, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.expert_signal_templates (id uuid DEFAULT gen_random_uuid() NOT NULL, expert_id uuid NOT NULL, title text NOT NULL, action text NOT NULL, reason text DEFAULT ''::text NOT NULL, risk_note text DEFAULT ''::text NOT NULL, strategy_note text DEFAULT ''::text NOT NULL, sort_order integer DEFAULT 0 NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.expert_signals (id uuid DEFAULT gen_random_uuid() NOT NULL, expert_id uuid NOT NULL, plan_id uuid, instrument text NOT NULL, action signal_action NOT NULL, price_hint numeric, reason_summary text, reason_detail text, risk_notes text, learning_points text, status signal_status DEFAULT 'published'::signal_status NOT NULL, taken_down_reason text, taken_down_by uuid, published_at timestamp with time zone DEFAULT now(), created_at timestamp with time zone DEFAULT now() NOT NULL, line_pushed_at timestamp with time zone, quantity integer, quantity_unit text DEFAULT '張'::text, teaching_topic text, overall_summary text, batch_id uuid, executed_at timestamp with time zone, market text NOT NULL, is_combo boolean DEFAULT false NOT NULL, combo_strategy text, net_premium numeric, max_loss_per_unit numeric, max_profit_per_unit numeric);
CREATE TABLE IF NOT EXISTS public.experts (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, slug text NOT NULL, name text NOT NULL, role expert_role NOT NULL, bio text, description text, style_tags text[], markets text[], avatar_url text, status text DEFAULT 'active'::text NOT NULL, created_by uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, strategy_summary text, backtest_1y_return numeric, backtest_max_drawdown numeric, backtest_annual_return numeric, starting_capital integer, risk_preference text, operation_cycle text, strategy_name text, currency text DEFAULT 'TWD'::text NOT NULL, asset_class text DEFAULT 'tw_stock'::text NOT NULL);
CREATE TABLE IF NOT EXISTS public.finmind_inflight_requests (key text NOT NULL, stock_id text, kind text NOT NULL, started_at timestamp with time zone DEFAULT now() NOT NULL, expires_at timestamp with time zone DEFAULT (now() + '00:00:30'::interval) NOT NULL);
CREATE TABLE IF NOT EXISTS public.finmind_quota_ledger (id bigint DEFAULT nextval('finmind_quota_ledger_id_seq'::regclass) NOT NULL, pool_name text NOT NULL, request_kind text NOT NULL, stock_id text, granted boolean NOT NULL, reason text, created_at timestamp with time zone DEFAULT now() NOT NULL, borrowed_from text, root_cause_hint text);
CREATE TABLE IF NOT EXISTS public.finmind_quota_pools (pool_name text NOT NULL, daily_budget integer DEFAULT 100 NOT NULL, used_today integer DEFAULT 0 NOT NULL, reset_at date DEFAULT ((now() AT TIME ZONE 'Asia/Taipei'::text))::date NOT NULL, priority integer DEFAULT 5 NOT NULL, last_reject_at timestamp with time zone, last_reject_reason text, updated_at timestamp with time zone DEFAULT now() NOT NULL, capacity integer, tokens numeric, refill_per_min numeric DEFAULT 0 NOT NULL, last_refill_at timestamp with time zone DEFAULT now() NOT NULL, borrow_enabled boolean DEFAULT true NOT NULL, slo_boost_until timestamp with time zone, manual_override boolean DEFAULT false NOT NULL, base_daily_budget integer);
CREATE TABLE IF NOT EXISTS public.finmind_upstream_quota (source text NOT NULL, remaining integer, quota_limit integer, reset_at timestamp with time zone, observed_at timestamp with time zone DEFAULT now() NOT NULL, raw jsonb);
CREATE TABLE IF NOT EXISTS public.function_run_logs (id uuid DEFAULT gen_random_uuid() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, fn text NOT NULL, run_id text NOT NULL, level text DEFAULT 'info'::text NOT NULL, stage text, msg text, expert_id uuid, signal_id uuid, payload jsonb DEFAULT '{}'::jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS public.fx_rates (currency_pair text NOT NULL, rate numeric NOT NULL, source text NOT NULL, fetched_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.holding_meta_override_history (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, code text NOT NULL, industry text, strategy text, leader text, "position" text, source text, action text DEFAULT 'snapshot'::text NOT NULL, recorded_at timestamp with time zone DEFAULT now() NOT NULL, recorded_by uuid, industries text[], themes text[], revenue_mix jsonb);
CREATE TABLE IF NOT EXISTS public.holding_meta_overrides (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, code text NOT NULL, industry text, strategy text, leader text, "position" text, source text DEFAULT 'ai_enrich'::text NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, industries text[], themes text[], revenue_mix jsonb);
CREATE TABLE IF NOT EXISTS public.holdings_fix_proposals (id uuid DEFAULT gen_random_uuid() NOT NULL, drift_category text NOT NULL, expert_id uuid, expert_slug text, expert_name text, symbol text, instrument text, severity text DEFAULT 'medium'::text NOT NULL, summary text NOT NULL, proposed_action text NOT NULL, payload jsonb DEFAULT '{}'::jsonb NOT NULL, preview jsonb DEFAULT '{}'::jsonb NOT NULL, status text DEFAULT 'pending'::text NOT NULL, signature text NOT NULL, generated_by uuid, generated_at timestamp with time zone DEFAULT now() NOT NULL, reviewed_by uuid, reviewed_at timestamp with time zone, review_note text, applied_by uuid, applied_at timestamp with time zone, apply_result jsonb, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.institutional_new_stock_queue (id uuid DEFAULT gen_random_uuid() NOT NULL, stock_id text NOT NULL, requested_at timestamp with time zone DEFAULT now() NOT NULL, attempts integer DEFAULT 0 NOT NULL, next_attempt_at timestamp with time zone DEFAULT now() NOT NULL, status text DEFAULT 'pending'::text NOT NULL, last_error text, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.internal_cron_secrets (id integer DEFAULT 1 NOT NULL, cron_key text NOT NULL, rotated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.knowledge_auto_rules (id uuid DEFAULT gen_random_uuid() NOT NULL, enabled boolean DEFAULT false NOT NULL, archive_below_win_rate numeric DEFAULT 0.40 NOT NULL, promote_above_win_rate numeric DEFAULT 0.70 NOT NULL, min_sample_size integer DEFAULT 30 NOT NULL, auto_grid_search_below numeric DEFAULT 0.55 NOT NULL, promote_min_improvement_pct numeric DEFAULT 5 NOT NULL, updated_by uuid, updated_at timestamp with time zone DEFAULT now() NOT NULL, daily_grid_search_quota integer DEFAULT 5 NOT NULL, rescue_max_weeks integer DEFAULT 3 NOT NULL, candidate_observe_days integer DEFAULT 14 NOT NULL);
CREATE TABLE IF NOT EXISTS public.knowledge_backfill_progress (id uuid DEFAULT gen_random_uuid() NOT NULL, symbol text NOT NULL, yyyymm text NOT NULL, status text DEFAULT 'pending'::text NOT NULL, rows_inserted integer DEFAULT 0 NOT NULL, attempted_at timestamp with time zone, completed_at timestamp with time zone, error_message text, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.knowledge_backtest_runs (id uuid DEFAULT gen_random_uuid() NOT NULL, knowledge_item_id uuid, run_mode text DEFAULT 'full'::text NOT NULL, date_range_start date, date_range_end date, universe_size integer, total_hits integer DEFAULT 0 NOT NULL, win_count integer DEFAULT 0 NOT NULL, loss_count integer DEFAULT 0 NOT NULL, win_rate numeric, avg_return_pct numeric, median_return_pct numeric, max_drawdown numeric, parameters jsonb DEFAULT '{}'::jsonb, details jsonb DEFAULT '{}'::jsonb, status text DEFAULT 'completed'::text NOT NULL, error_message text, created_at timestamp with time zone DEFAULT now() NOT NULL, completed_at timestamp with time zone, auto_action text, auto_action_reason text);
CREATE TABLE IF NOT EXISTS public.knowledge_grid_search_results (id uuid DEFAULT gen_random_uuid() NOT NULL, run_id uuid NOT NULL, knowledge_item_id uuid NOT NULL, parameters jsonb NOT NULL, total_hits integer DEFAULT 0 NOT NULL, win_rate numeric, avg_return_pct numeric, score numeric, is_best boolean DEFAULT false NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.line_binding_codes (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, expert_id uuid NOT NULL, code text NOT NULL, expires_at timestamp with time zone NOT NULL, used boolean DEFAULT false NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.line_login_nonces (nonce uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, access_token text NOT NULL, refresh_token text NOT NULL, expires_at timestamp with time zone NOT NULL, consumed_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.line_oauth_states (state text NOT NULL, payload jsonb DEFAULT '{}'::jsonb NOT NULL, expires_at timestamp with time zone NOT NULL, consumed_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.line_push_jobs (id uuid DEFAULT gen_random_uuid() NOT NULL, created_by uuid NOT NULL, recipient_user_ids uuid[] NOT NULL, message_kind text NOT NULL, text text, action_label text, action_url text, image_url text, scheduled_at timestamp with time zone, status text DEFAULT 'pending'::text NOT NULL, sent_count integer DEFAULT 0 NOT NULL, skipped_count integer DEFAULT 0 NOT NULL, failed_count integer DEFAULT 0 NOT NULL, result jsonb, error text, started_at timestamp with time zone, finished_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.line_push_receipts (id uuid DEFAULT gen_random_uuid() NOT NULL, dedupe_key text NOT NULL, recipient text NOT NULL, expert_id uuid, kind text NOT NULL, sent_at timestamp with time zone DEFAULT now() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.member_line_bindings (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, expert_id uuid NOT NULL, line_user_id text NOT NULL, display_name text, is_active boolean DEFAULT true NOT NULL, bound_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.member_subscriptions (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, plan_id uuid NOT NULL, status subscription_status DEFAULT 'active'::subscription_status NOT NULL, auto_renew boolean DEFAULT false NOT NULL, started_at timestamp with time zone DEFAULT now() NOT NULL, expires_at timestamp with time zone, canceled_at timestamp with time zone, provider_id uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, billing_cycle text DEFAULT 'monthly'::text NOT NULL);
CREATE TABLE IF NOT EXISTS public.notification_preferences (user_id uuid NOT NULL, target_price_new boolean DEFAULT true NOT NULL, target_price_updated boolean DEFAULT true NOT NULL, target_price_weekly boolean DEFAULT true NOT NULL, meta_override_changed boolean DEFAULT true NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, renewal_email boolean DEFAULT true NOT NULL, checkup_complete_line boolean DEFAULT true NOT NULL, checkup_complete_email boolean DEFAULT true NOT NULL);
CREATE TABLE IF NOT EXISTS public.notifications (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, title text NOT NULL, body text, type text DEFAULT 'info'::text NOT NULL, is_read boolean DEFAULT false NOT NULL, link text, created_at timestamp with time zone DEFAULT now() NOT NULL, download_url text);
CREATE TABLE IF NOT EXISTS public.payment_intents (id uuid DEFAULT gen_random_uuid() NOT NULL, trade_no text NOT NULL, user_id uuid, product_kind text DEFAULT 'expert_plan'::text NOT NULL, plan_id uuid, checkup_plan_id uuid, expert_id uuid, billing_cycle text NOT NULL, original_amount integer NOT NULL, discount_amount integer DEFAULT 0 NOT NULL, discount_reason text, amount integer NOT NULL, attribution jsonb, upgrade_from_subscription_id uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, status text DEFAULT 'pending'::text NOT NULL, completed_at timestamp with time zone, recovery_notified_at timestamp with time zone, final_recovery_notified_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS public.payment_providers (id uuid DEFAULT gen_random_uuid() NOT NULL, provider_type provider_type NOT NULL, display_name text NOT NULL, config jsonb DEFAULT '{}'::jsonb, is_active boolean DEFAULT false NOT NULL, is_default boolean DEFAULT false NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.payment_settings (id uuid DEFAULT gen_random_uuid() NOT NULL, key text NOT NULL, value jsonb DEFAULT '{}'::jsonb NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, updated_by uuid);
CREATE TABLE IF NOT EXISTS public.payment_transactions (id uuid DEFAULT gen_random_uuid() NOT NULL, subscription_id uuid, provider_id uuid, amount integer DEFAULT 0 NOT NULL, currency text DEFAULT 'TWD'::text NOT NULL, status payment_status DEFAULT 'pending'::payment_status NOT NULL, provider_tx_id text, paid_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL, attribution jsonb, original_amount integer, discount_amount integer DEFAULT 0 NOT NULL, discount_reason text);
CREATE TABLE IF NOT EXISTS public.paywall_events (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid, visitor_id text, event_kind text NOT NULL, surface text NOT NULL, variant text, context jsonb, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.perf_metrics (id uuid DEFAULT gen_random_uuid() NOT NULL, route text NOT NULL, fcp_ms integer, lcp_ms integer, user_id uuid, session_id text, viewport_w integer, ua_kind text, created_at timestamp with time zone DEFAULT now() NOT NULL, inp_ms integer, cls_score numeric(6,4));
CREATE TABLE IF NOT EXISTS public.plan_split_overrides (id uuid DEFAULT gen_random_uuid() NOT NULL, plan_id uuid NOT NULL, pct_platform integer NOT NULL, pct_expert integer NOT NULL, is_active boolean DEFAULT true NOT NULL, notes text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.price_parity_events (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid, symbol text NOT NULL, market text NOT NULL, db_price numeric, cache_price numeric, diff_pct numeric NOT NULL, source text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.price_quota_ledger (id bigint DEFAULT nextval('price_quota_ledger_id_seq'::regclass) NOT NULL, market text NOT NULL, requested integer NOT NULL, admitted integer NOT NULL, tokens_after double precision NOT NULL, writer text, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.price_quota_pools (market text NOT NULL, api_name text NOT NULL, per_min_cap integer NOT NULL, per_day_cap integer, tokens double precision DEFAULT 0 NOT NULL, last_refill timestamp with time zone DEFAULT now() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.processed_webhook_events (id uuid DEFAULT gen_random_uuid() NOT NULL, source text NOT NULL, delivery_id text NOT NULL, processed_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.profiles (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, display_name text, avatar_url text, expert_slug text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, line_user_id text, is_line_friend boolean DEFAULT false, is_tester boolean DEFAULT false NOT NULL, merged_into_user_id uuid);
CREATE TABLE IF NOT EXISTS public.publish_batch_attempts (id uuid DEFAULT gen_random_uuid() NOT NULL, market text NOT NULL, attempt_no integer DEFAULT 1 NOT NULL, max_attempts integer DEFAULT 5 NOT NULL, status text DEFAULT 'pending_retry'::text NOT NULL, scheduled_at timestamp with time zone DEFAULT now() NOT NULL, next_retry_at timestamp with time zone, started_at timestamp with time zone, finished_at timestamp with time zone, run_id text, parent_attempt_id uuid, root_attempt_id uuid, error_message text, response jsonb, trigger_source text DEFAULT 'cron'::text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.referral_attributions (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid, visitor_id text, utm_source text, utm_medium text, utm_campaign text, utm_content text, ref_code text, landing_path text, locked_until timestamp with time zone DEFAULT (now() + '30 days'::interval) NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.referral_channels (id uuid DEFAULT gen_random_uuid() NOT NULL, source text NOT NULL, display_name text NOT NULL, notes text, is_active boolean DEFAULT true NOT NULL, pct_platform integer, pct_expert integer, pct_channel integer, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.remittance_orders (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, plan_id uuid, billing_cycle text NOT NULL, amount integer NOT NULL, original_amount integer, discount_amount integer DEFAULT 0 NOT NULL, discount_reason text, last5 text, payer_name text, attribution jsonb, status text DEFAULT 'pending'::text NOT NULL, reject_reason text, confirmed_by uuid, confirmed_at timestamp with time zone, subscription_id uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, product_kind text DEFAULT 'expert_plan'::text NOT NULL, checkup_plan_id uuid, client_request_id uuid);
CREATE TABLE IF NOT EXISTS public.revenue_splits (id uuid DEFAULT gen_random_uuid() NOT NULL, transaction_id uuid NOT NULL, expert_id uuid, plan_id uuid, gross integer NOT NULL, discount integer DEFAULT 0 NOT NULL, discount_source text, net integer NOT NULL, platform_amount integer NOT NULL, expert_amount integer DEFAULT 0 NOT NULL, channel_reserve integer DEFAULT 0 NOT NULL, rule_source text NOT NULL, rule_snapshot jsonb NOT NULL, utm_snapshot jsonb, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.signal_trade_applications (signal_id uuid NOT NULL, expert_id uuid NOT NULL, action text NOT NULL, applied_quantity integer, tg_op text, applied_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.stock_fundamentals (id bigint DEFAULT nextval('stock_fundamentals_id_seq'::regclass) NOT NULL, stock_id text NOT NULL, report_date date NOT NULL, dataset text NOT NULL, data jsonb NOT NULL, source text NOT NULL, fetched_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.stock_names (symbol text NOT NULL, name text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, currency text DEFAULT 'TWD'::text NOT NULL, market text, asset_class text DEFAULT 'tw_stock'::text NOT NULL);
CREATE TABLE IF NOT EXISTS public.system_alerts (id uuid DEFAULT gen_random_uuid() NOT NULL, kind text NOT NULL, level text DEFAULT 'warning'::text NOT NULL, title text NOT NULL, message text, metric_value numeric, threshold numeric, detail jsonb DEFAULT '{}'::jsonb NOT NULL, fired_at timestamp with time zone DEFAULT now() NOT NULL, resolved_at timestamp with time zone, notified_at timestamp with time zone, notify_error text);
CREATE TABLE IF NOT EXISTS public.system_jobs_log (id uuid DEFAULT gen_random_uuid() NOT NULL, job_name text NOT NULL, status text DEFAULT 'success'::text NOT NULL, detail jsonb DEFAULT '{}'::jsonb, duration_ms integer, ran_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.system_kill_switches (key text NOT NULL, enabled boolean DEFAULT true NOT NULL, disabled_reason text, auto_trigger_metric text, disabled_at timestamp with time zone, disabled_by uuid, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.target_price_history (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, code text NOT NULL, firm text DEFAULT ''::text NOT NULL, target numeric NOT NULL, prev_target numeric, report_date text, change_type text DEFAULT 'new'::text NOT NULL, source text DEFAULT 'refresh-reports'::text NOT NULL, batch_id uuid, detail jsonb DEFAULT '{}'::jsonb NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.trade_records (id uuid DEFAULT gen_random_uuid() NOT NULL, expert_id uuid NOT NULL, signal_id uuid, instrument text NOT NULL, entry_price numeric, exit_price numeric, entry_date timestamp with time zone, exit_date timestamp with time zone, pnl_percent numeric, status trade_status DEFAULT 'open'::trade_status NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, current_price numeric, price_updated_at timestamp with time zone, quantity integer DEFAULT 1 NOT NULL, quantity_unit text DEFAULT '張'::text NOT NULL, market text, currency text, is_combo boolean DEFAULT false NOT NULL, combo_strategy text, net_premium numeric, max_loss_per_unit numeric, max_profit_per_unit numeric);
CREATE TABLE IF NOT EXISTS public.trade_signals (id integer DEFAULT nextval('trade_signals_id_seq'::regclass) NOT NULL, user_id uuid NOT NULL, symbol text NOT NULL, name text, entry_price numeric NOT NULL, status text DEFAULT 'open'::text, created_at timestamp with time zone DEFAULT now(), exit_price double precision, pnl double precision, pnl_percent double precision, closed_at timestamp with time zone);
CREATE TABLE IF NOT EXISTS public.traffic_events (id uuid DEFAULT gen_random_uuid() NOT NULL, visitor_id text NOT NULL, user_id uuid, route text NOT NULL, referrer_host text, occurred_at timestamp with time zone DEFAULT now() NOT NULL, event_name text, event_props jsonb, is_internal boolean DEFAULT false NOT NULL);
CREATE TABLE IF NOT EXISTS public.traffic_visits (id uuid DEFAULT gen_random_uuid() NOT NULL, visitor_id text NOT NULL, user_id uuid, first_landing_path text, first_referrer text, first_referrer_host text, utm_source text, utm_medium text, utm_campaign text, utm_content text, utm_term text, ref_code text, channel text DEFAULT 'direct'::text NOT NULL, device_kind text, country text, page_views integer DEFAULT 1 NOT NULL, first_seen_at timestamp with time zone DEFAULT now() NOT NULL, last_seen_at timestamp with time zone DEFAULT now() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.tw_bsr_api_reservations (id bigint DEFAULT nextval('tw_bsr_api_reservations_id_seq'::regclass) NOT NULL, api_name text DEFAULT 'finmind'::text NOT NULL, reserved_at timestamp with time zone DEFAULT now() NOT NULL, expires_at timestamp with time zone NOT NULL, settled_at timestamp with time zone, success boolean, rate_limited boolean DEFAULT false NOT NULL, released boolean DEFAULT false NOT NULL, correlation_id uuid, recycle_reason text, tier smallint);
CREATE TABLE IF NOT EXISTS public.tw_bsr_api_usage (bucket_start timestamp with time zone NOT NULL, api_name text DEFAULT 'finmind'::text NOT NULL, call_count integer DEFAULT 0 NOT NULL, success_count integer DEFAULT 0 NOT NULL, error_count integer DEFAULT 0 NOT NULL, rate_limited_count integer DEFAULT 0 NOT NULL);
CREATE TABLE IF NOT EXISTS public.tw_bsr_attempt_logs (id bigint DEFAULT nextval('tw_bsr_attempt_logs_id_seq'::regclass) NOT NULL, stock_id text NOT NULL, trade_date date NOT NULL, attempted_at timestamp with time zone DEFAULT now() NOT NULL, ua_label text NOT NULL, ua_hash text NOT NULL, backoff_seconds_before integer DEFAULT 0 NOT NULL, consecutive_failures_before integer DEFAULT 0 NOT NULL, ocr_mode text DEFAULT 'standard'::text NOT NULL, latency_ms integer DEFAULT 0 NOT NULL, outcome text NOT NULL, attempt_step smallint DEFAULT 0 NOT NULL, config_version text, created_at timestamp with time zone DEFAULT now() NOT NULL, http_status integer, error text, fallback_used boolean DEFAULT false NOT NULL, fallback_as_of_date date, next_retry_at timestamp with time zone, next_retry_source text, error_class text, ocr_trace jsonb, adaptive_strategy jsonb, correlation_id uuid);
CREATE TABLE IF NOT EXISTS public.tw_bsr_daily (id bigint DEFAULT nextval('tw_bsr_daily_id_seq'::regclass) NOT NULL, stock_id text NOT NULL, trade_date date NOT NULL, broker_id text NOT NULL, broker_name text NOT NULL, buy_shares bigint DEFAULT 0 NOT NULL, sell_shares bigint DEFAULT 0 NOT NULL, net_shares bigint DEFAULT 0 NOT NULL, avg_buy_price numeric(12,4), avg_sell_price numeric(12,4), created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.tw_bsr_daily_snapshot_status (trade_date date NOT NULL, status text DEFAULT 'pending'::text NOT NULL, source text, fetched_at timestamp with time zone, coverage_stocks integer DEFAULT 0 NOT NULL, coverage_rows integer DEFAULT 0 NOT NULL, attempt_count integer DEFAULT 0 NOT NULL, last_error text, correlation_id uuid, lock_expires_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, sealed_at timestamp with time zone, sealed_by_lane text, coverage_brokers integer DEFAULT 0 NOT NULL, lane_a_status text DEFAULT 'pending'::text NOT NULL, lane_b_status text DEFAULT 'pending'::text NOT NULL, lane_c_status text DEFAULT 'pending'::text NOT NULL, partial_lanes text[] DEFAULT '{}'::text[] NOT NULL);
CREATE TABLE IF NOT EXISTS public.tw_bsr_degrade_events (id bigint DEFAULT nextval('tw_bsr_degrade_events_id_seq'::regclass) NOT NULL, api_name text DEFAULT 'finmind'::text NOT NULL, from_mode text NOT NULL, to_mode text NOT NULL, reason text NOT NULL, trigger_metric text, trigger_value numeric, threshold numeric, correlation_id uuid, detail jsonb DEFAULT '{}'::jsonb NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.tw_bsr_fetch_failures (id bigint DEFAULT nextval('tw_bsr_fetch_failures_id_seq'::regclass) NOT NULL, stock_id text NOT NULL, trade_date date NOT NULL, reason text NOT NULL, attempts smallint DEFAULT 1 NOT NULL, last_error text, resolved_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, next_retry_at timestamp with time zone, backoff_seconds integer DEFAULT 60 NOT NULL, consecutive_failures integer DEFAULT 1 NOT NULL, error_class text, correlation_id uuid);
CREATE TABLE IF NOT EXISTS public.tw_bsr_keepwarm_metrics (id uuid DEFAULT gen_random_uuid() NOT NULL, trade_date date NOT NULL, wave smallint DEFAULT 0 NOT NULL, status text NOT NULL, sealed boolean DEFAULT false NOT NULL, sealed_by_lane text, coverage_stocks integer DEFAULT 0 NOT NULL, coverage_brokers integer DEFAULT 0 NOT NULL, fallback_used_count integer DEFAULT 0 NOT NULL, duration_ms integer DEFAULT 0 NOT NULL, error text, started_at timestamp with time zone DEFAULT now() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.tw_bsr_sync_config (key text NOT NULL, config jsonb NOT NULL, version integer DEFAULT 1 NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, updated_by uuid, note text);
CREATE TABLE IF NOT EXISTS public.tw_bsr_sync_config_history (id uuid DEFAULT gen_random_uuid() NOT NULL, key text NOT NULL, version integer NOT NULL, config jsonb NOT NULL, changed_at timestamp with time zone DEFAULT now() NOT NULL, changed_by uuid, note text);
CREATE TABLE IF NOT EXISTS public.tw_bsr_sync_locks (lock_key text NOT NULL, acquired_at timestamp with time zone DEFAULT now() NOT NULL, expires_at timestamp with time zone NOT NULL);
CREATE TABLE IF NOT EXISTS public.tw_bsr_sync_metrics (bucket_at timestamp with time zone NOT NULL, total integer DEFAULT 0 NOT NULL, success integer DEFAULT 0 NOT NULL, ocr_fail integer DEFAULT 0 NOT NULL, http_block integer DEFAULT 0 NOT NULL, empty integer DEFAULT 0 NOT NULL, avg_latency_ms integer DEFAULT 0 NOT NULL);
CREATE TABLE IF NOT EXISTS public.tw_bsr_sync_queue (id bigint DEFAULT nextval('tw_bsr_sync_queue_id_seq'::regclass) NOT NULL, stock_id text NOT NULL, trade_date date NOT NULL, priority smallint NOT NULL, status text DEFAULT 'pending'::text NOT NULL, attempts integer DEFAULT 0 NOT NULL, max_attempts integer DEFAULT 5 NOT NULL, next_run_at timestamp with time zone DEFAULT now() NOT NULL, last_success_at timestamp with time zone, last_error text, enqueued_by text, enqueued_at timestamp with time zone DEFAULT now() NOT NULL, started_at timestamp with time zone, finished_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, correlation_id uuid, post_close_only boolean DEFAULT false NOT NULL);
CREATE TABLE IF NOT EXISTS public.tw_bsr_upstream_probe (stock_id text NOT NULL, earliest_data date, probed_back_to date, empty_streak integer DEFAULT 0 NOT NULL, exhausted boolean DEFAULT false NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.tw_chip_fact (id bigint DEFAULT nextval('tw_chip_fact_id_seq'::regclass) NOT NULL, stock_id text NOT NULL, trade_date date NOT NULL, broker_id text NOT NULL, broker_name text, source text NOT NULL, buy_shares bigint DEFAULT 0 NOT NULL, sell_shares bigint DEFAULT 0 NOT NULL, net_shares bigint GENERATED ALWAYS AS (buy_shares - sell_shares) STORED, avg_buy_price numeric(12,4), avg_sell_price numeric(12,4), raw jsonb, ingested_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS public.tw_chips_rollup (id bigint DEFAULT nextval('tw_chips_rollup_id_seq'::regclass) NOT NULL, stock_id text NOT NULL, as_of_date date NOT NULL, window_days smallint NOT NULL, foreign_net bigint DEFAULT 0 NOT NULL, trust_net bigint DEFAULT 0 NOT NULL, dealer_net bigint DEFAULT 0 NOT NULL, top_buy_brokers jsonb DEFAULT '[]'::jsonb NOT NULL, top_sell_brokers jsonb DEFAULT '[]'::jsonb NOT NULL, concentration_ratio numeric(5,2), bsr_available boolean DEFAULT false NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, broker_count integer, low_quality boolean, source_date date DEFAULT CURRENT_DATE NOT NULL, fallback_used boolean DEFAULT false NOT NULL);
CREATE TABLE IF NOT EXISTS public.tw_institutional_daily (id bigint DEFAULT nextval('tw_institutional_daily_id_seq'::regclass) NOT NULL, stock_id text NOT NULL, trade_date date NOT NULL, foreign_net bigint DEFAULT 0 NOT NULL, trust_net bigint DEFAULT 0 NOT NULL, dealer_net bigint DEFAULT 0 NOT NULL, total_net bigint DEFAULT 0 NOT NULL, raw jsonb, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, source text DEFAULT 'unknown'::text NOT NULL);
CREATE TABLE IF NOT EXISTS public.tw_market_holidays (trade_date date NOT NULL, name text, source text DEFAULT 'manual'::text NOT NULL, detected_at timestamp with time zone DEFAULT now() NOT NULL, note text);
CREATE TABLE IF NOT EXISTS public.user_performances (user_id uuid NOT NULL, symbol text NOT NULL, name text, current_price numeric, pnl numeric, pnl_percent numeric, updated_at timestamp with time zone DEFAULT now(), signal_id integer NOT NULL, entry_price double precision);
CREATE TABLE IF NOT EXISTS public.user_roles (id uuid DEFAULT gen_random_uuid() NOT NULL, user_id uuid NOT NULL, role app_role NOT NULL);
CREATE TABLE IF NOT EXISTS public.user_summaries (user_id uuid NOT NULL, total_pnl_percent double precision DEFAULT 0, avg_pnl_percent double precision DEFAULT 0, updated_at timestamp with time zone DEFAULT now());
CREATE TABLE IF NOT EXISTS public.warrant_expiry (symbol text NOT NULL, name text, parent_code text, expire_date date, fetched_at timestamp with time zone DEFAULT now() NOT NULL, exercise_ratio numeric(12,6), strike_price numeric(14,4), call_put text, ratio_source text, ratio_updated_at timestamp with time zone);
CREATE OR REPLACE VIEW public.checkup_knowledge_usage_stats AS  SELECT ki.id AS knowledge_item_id,
    count(kh.id) AS hit_count,
    count(kh.id) FILTER (WHERE kh.created_at > (now() - '7 days'::interval)) AS hit_count_7d,
    max(kh.created_at) AS last_hit_at
   FROM checkup_knowledge_items ki
     LEFT JOIN checkup_knowledge_hits kh ON kh.knowledge_item_id = ki.id
  GROUP BY ki.id;
CREATE OR REPLACE VIEW public.chip_fact_conflicts AS  WITH grp AS (
         SELECT tw_chip_fact.trade_date,
            tw_chip_fact.stock_id,
            tw_chip_fact.broker_id,
            count(DISTINCT tw_chip_fact.source) AS lane_count,
            max(tw_chip_fact.net_shares) AS max_net,
            min(tw_chip_fact.net_shares) AS min_net,
            array_agg(DISTINCT tw_chip_fact.source ORDER BY tw_chip_fact.source) AS lanes
           FROM tw_chip_fact
          WHERE tw_chip_fact.trade_date >= (CURRENT_DATE - '30 days'::interval)::date
          GROUP BY tw_chip_fact.trade_date, tw_chip_fact.stock_id, tw_chip_fact.broker_id
        )
 SELECT trade_date,
    stock_id,
    broker_id,
    lanes,
    lane_count,
    max_net,
    min_net,
    max_net - min_net AS net_diff
   FROM grp
  WHERE lane_count >= 2 AND abs(max_net - min_net) >= 1000
  ORDER BY trade_date DESC, (abs(max_net - min_net)) DESC;
CREATE OR REPLACE VIEW public.chip_fact_health AS  WITH recent_dates AS (
         SELECT DISTINCT tw_chip_fact.trade_date
           FROM tw_chip_fact
          ORDER BY tw_chip_fact.trade_date DESC
         LIMIT 30
        )
 SELECT f.trade_date,
    f.source AS lane,
    count(*) AS row_count,
    count(DISTINCT f.stock_id) AS stock_count,
    count(DISTINCT f.broker_id) AS broker_count,
    max(f.ingested_at) AS last_ingested_at,
    COALESCE(s.sealed_at IS NOT NULL, false) AS sealed,
    s.sealed_by_lane
   FROM tw_chip_fact f
     JOIN recent_dates rd ON rd.trade_date = f.trade_date
     LEFT JOIN tw_bsr_daily_snapshot_status s ON s.trade_date = f.trade_date
  GROUP BY f.trade_date, f.source, s.sealed_at, s.sealed_by_lane
  ORDER BY f.trade_date DESC, f.source;
CREATE OR REPLACE VIEW public.chips_state_hourly AS  SELECT date_trunc('hour'::text, created_at) AS hour,
    pool_name,
    count(*)::integer AS total,
    count(*) FILTER (WHERE granted)::integer AS granted,
    count(*) FILTER (WHERE NOT granted)::integer AS rejected,
    round(count(*) FILTER (WHERE granted)::numeric / NULLIF(count(*), 0)::numeric, 4) AS ready_ratio,
    count(*) FILTER (WHERE borrowed_from IS NOT NULL)::integer AS borrowed
   FROM finmind_quota_ledger
  WHERE created_at > (now() - '48:00:00'::interval)
  GROUP BY (date_trunc('hour'::text, created_at)), pool_name;
CREATE OR REPLACE VIEW public.expert_line_channels_public AS  SELECT id,
    expert_id,
    channel_id,
    channel_name,
    line_oa_id,
    qr_code_url,
    is_active,
    created_at,
    updated_at
   FROM expert_line_channels;
CREATE OR REPLACE VIEW public.experts_public AS  SELECT id,
    name,
    slug,
    role,
    status,
    bio,
    description,
    avatar_url,
    markets,
    style_tags,
    created_at
   FROM experts;
CREATE OR REPLACE VIEW public.finmind_pool_daily_equiv AS  SELECT pool_name,
    daily_budget,
    used_today,
    GREATEST(0, daily_budget - used_today) AS remaining_today,
    tokens,
    capacity,
    refill_per_min,
    round(refill_per_min * 60::numeric, 2) AS refill_per_hour,
        CASE
            WHEN refill_per_min > 0::numeric THEN now() + make_interval(mins => (tokens / refill_per_min)::integer)
            ELSE NULL::timestamp with time zone
        END AS estimated_full_at,
    slo_boost_until,
    manual_override
   FROM finmind_quota_pools;
CREATE OR REPLACE VIEW public.member_line_bindings_analyst AS  SELECT id,
    user_id,
    expert_id,
    display_name,
    is_active,
    bound_at
   FROM member_line_bindings;
CREATE OR REPLACE VIEW public.payment_providers_safe AS  SELECT id,
    provider_type,
    display_name,
    is_active,
    is_default,
    COALESCE(NULLIF(config ->> 'env'::text, ''::text), NULLIF(config ->> 'mode'::text, ''::text), 'production'::text) AS env,
    created_at
   FROM payment_providers
  WHERE is_active = true;
CREATE OR REPLACE VIEW public.payment_settings_safe AS  SELECT id,
    key,
    updated_by,
    updated_at,
        CASE
            WHEN key = 'ecpay_credentials'::text THEN jsonb_strip_nulls(jsonb_build_object('merchant_id', value ->> 'merchant_id'::text, 'api_url', value ->> 'api_url'::text, 'credit_action_url', value ->> 'credit_action_url'::text, 'env', value ->> 'env'::text, 'has_hash_key', value ? 'hash_key'::text AND length(COALESCE(value ->> 'hash_key'::text, ''::text)) > 0, 'has_hash_iv', value ? 'hash_iv'::text AND length(COALESCE(value ->> 'hash_iv'::text, ''::text)) > 0, 'hash_key_last4',
            CASE
                WHEN length(COALESCE(value ->> 'hash_key'::text, ''::text)) >= 4 THEN '***'::text || "right"(value ->> 'hash_key'::text, 4)
                ELSE NULL::text
            END, 'hash_iv_last4',
            CASE
                WHEN length(COALESCE(value ->> 'hash_iv'::text, ''::text)) >= 4 THEN '***'::text || "right"(value ->> 'hash_iv'::text, 4)
                ELSE NULL::text
            END))
            ELSE value
        END AS value
   FROM payment_settings ps;
CREATE OR REPLACE VIEW public.profiles_analyst AS  SELECT user_id,
    display_name,
    avatar_url,
    created_at
   FROM profiles;
CREATE OR REPLACE VIEW public.v_active_tw_holdings AS  SELECT DISTINCT "substring"(instrument, '^([1-9][0-9]{3})(?:\s|$)'::text) AS stock_id
   FROM trade_records tr
  WHERE market = 'TW'::text AND status::text = 'open'::text AND instrument ~ '^[1-9][0-9]{3}(?:\s|$)'::text;
CREATE OR REPLACE VIEW public.v_price_sync_universe AS  WITH raw_symbols AS (
         SELECT TRIM(BOTH FROM split_part(trade_records.instrument, ' '::text, 1)) AS symbol
           FROM trade_records
          WHERE trade_records.status = 'open'::trade_status AND trade_records.instrument IS NOT NULL
        UNION
         SELECT TRIM(BOTH FROM split_part(expert_signals.instrument, ' '::text, 1)) AS symbol
           FROM expert_signals
          WHERE expert_signals.instrument IS NOT NULL AND expert_signals.created_at >= (now() - '180 days'::interval)
        UNION
         SELECT upper(crypto_symbol_map.symbol) AS symbol
           FROM crypto_symbol_map
          WHERE crypto_symbol_map.is_active = true
        UNION
         SELECT upper(TRIM(BOTH FROM elem.value ->> 'code'::text)) AS symbol
           FROM checkup_storage,
            LATERAL jsonb_array_elements(
                CASE
                    WHEN jsonb_typeof(checkup_storage.data) = 'array'::text THEN checkup_storage.data
                    ELSE '[]'::jsonb
                END) elem(value)
          WHERE checkup_storage.key = 'pf-holdings-v2'::text AND elem.value ? 'code'::text
        ), crypto_set AS (
         SELECT upper(crypto_symbol_map.symbol) AS symbol
           FROM crypto_symbol_map
          WHERE crypto_symbol_map.is_active = true
        ), classified AS (
         SELECT r.symbol,
                CASE
                    WHEN (r.symbol IN ( SELECT crypto_set.symbol
                       FROM crypto_set)) THEN 'CRYPTO'::text
                    WHEN r.symbol ~ '^\d{4}$'::text THEN 'TW'::text
                    WHEN r.symbol ~ '^[03567]\d{5}$'::text THEN 'TW'::text
                    WHEN r.symbol ~ '^[A-Z]{1,5}(\.[A-Z])?$'::text THEN 'US'::text
                    ELSE NULL::text
                END AS market,
                CASE
                    WHEN r.symbol ~ '^[03567]\d{5}$'::text THEN 20
                    WHEN r.symbol ~ '^\d{4}$'::text THEN 10
                    WHEN r.symbol ~ '^[A-Z]{1,5}$'::text THEN 10
                    ELSE 30
                END AS priority
           FROM raw_symbols r
          WHERE r.symbol IS NOT NULL AND r.symbol <> ''::text
        )
 SELECT DISTINCT symbol,
    market,
    priority
   FROM classified
  WHERE market IS NOT NULL;

CREATE OR REPLACE VIEW public.v_price_freshness AS  WITH universe AS (
         SELECT v_price_sync_universe.market,
            count(*) AS universe_count
           FROM v_price_sync_universe
          GROUP BY v_price_sync_universe.market
        ), prices AS (
         SELECT u_1.market,
            count(cp.symbol) AS covered_count,
            percentile_disc(0.5::double precision) WITHIN GROUP (ORDER BY (EXTRACT(epoch FROM now() - cp.updated_at)::integer)) AS p50_age_s,
            percentile_disc(0.95::double precision) WITHIN GROUP (ORDER BY (EXTRACT(epoch FROM now() - cp.updated_at)::integer)) AS p95_age_s,
            max(EXTRACT(epoch FROM now() - cp.updated_at))::integer AS max_age_s,
            min(cp.updated_at) AS oldest_updated_at,
            max(cp.updated_at) AS newest_updated_at
           FROM v_price_sync_universe u_1
             LEFT JOIN current_prices cp ON cp.symbol = u_1.symbol AND cp.market = u_1.market
          GROUP BY u_1.market
        )
 SELECT u.market,
    u.universe_count,
    COALESCE(p.covered_count, 0::bigint) AS covered_count,
    round(COALESCE(p.covered_count, 0::bigint)::numeric / NULLIF(u.universe_count, 0)::numeric, 4) AS coverage_ratio,
    p.p50_age_s,
    p.p95_age_s,
    p.max_age_s,
    p.oldest_updated_at,
    p.newest_updated_at
   FROM universe u
     LEFT JOIN prices p USING (market);