-- R0 clone cutover (generated by db/r0/build_cutover.py)
SET ROLE ledger_owner;
-- E0: app_ledger core (economic_effect, mutation tokens, guards, invariants)

CREATE TYPE public.effect_provenance AS ENUM (
  'signal_execution','external_capital_flow','historical_fill',
  'equity_bridge','quantity_adjustment','break_glass');

CREATE SEQUENCE app_ledger.projection_version_seq;
CREATE SEQUENCE app_ledger.effect_no_seq;

-- ---------------------------------------------------------------- economic_effect
CREATE TABLE app_ledger.economic_effect (
  event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  logical_effect_id uuid NOT NULL,
  event_version int NOT NULL DEFAULT 1,
  supersedes_event_id uuid NULL REFERENCES app_ledger.economic_effect(event_id),
  expert_id uuid NOT NULL,
  origin_signal_id uuid NULL,
  market text NULL,
  instrument text NULL,
  instrument_key text NULL,
  action text NOT NULL,
  qty_delta integer NOT NULL,
  qty_unit text NOT NULL DEFAULT 'share',
  currency text NOT NULL CHECK (currency IN ('TWD','USD')),
  cash_delta numeric NULL,
  price numeric NULL,
  fees numeric NOT NULL DEFAULT 0,
  fee_model text NOT NULL DEFAULT 'none',
  effective_at timestamptz NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  provenance public.effect_provenance NOT NULL,
  actor_user_id uuid NULL,
  actor_via text NOT NULL,
  reason text NOT NULL,
  expected_mutation_count int NOT NULL CHECK (expected_mutation_count >= 0),
  calc_model_version text NOT NULL DEFAULT 'v1',
  effect_no bigint NOT NULL DEFAULT nextval('app_ledger.effect_no_seq'),
  generation int NOT NULL DEFAULT 1,
  state text NOT NULL DEFAULT 'reserved'
    CHECK (state IN ('reserved','applied','failed','superseded')),
  visible_at timestamptz NULL,
  state_changed_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- mutation tokens (F3: all NOT NULL)
CREATE TABLE app_ledger.effect_projection_mutation (
  mutation_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES app_ledger.economic_effect(event_id),
  mutation_seq int NOT NULL,
  target_table text NOT NULL,
  target_row_id uuid NOT NULL,
  op text NOT NULL CHECK (op IN ('insert','update','delete')),
  row_role text NOT NULL,
  expert_id uuid NOT NULL,
  currency text NOT NULL,
  market text NULL,
  instrument_key text NULL,
  qty_delta integer NOT NULL,
  cash_delta numeric NULL,
  cost_delta numeric NOT NULL DEFAULT 0,
  realized_delta numeric NOT NULL DEFAULT 0,
  before_hash text NULL,
  after_hash text NULL,
  consumed boolean NOT NULL DEFAULT false,
  UNIQUE (event_id, mutation_seq),
  CONSTRAINT epm_seq_pos      CHECK (mutation_seq >= 1),
  CONSTRAINT epm_target_ck    CHECK (target_table IN ('trade_records','portfolio_cash_ledger')),
  CONSTRAINT epm_role_ck      CHECK (row_role IN ('open_position','closed_lot','cash_leg')),
  CONSTRAINT epm_cash_ck      CHECK ((row_role='cash_leg') = (target_table='portfolio_cash_ledger')),
  CONSTRAINT epm_cashdelta_ck CHECK ((row_role='cash_leg') = (cash_delta IS NOT NULL)),
  CONSTRAINT epm_cash_qty_ck  CHECK (row_role <> 'cash_leg' OR qty_delta = 0),
  CONSTRAINT epm_market_ck    CHECK ((row_role = 'cash_leg') = (market IS NULL)),
  CONSTRAINT epm_ikey_ck      CHECK ((row_role = 'cash_leg') = (instrument_key IS NULL)),
  CONSTRAINT epm_before_ck    CHECK ((op='insert') = (before_hash IS NULL)),
  CONSTRAINT epm_after_ck     CHECK ((op='delete') = (after_hash IS NULL))
);

-- ---------------------------------------------------------------- internal cash ledger
CREATE TABLE app_ledger.portfolio_cash_ledger (
  cash_entry_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  expert_id uuid NOT NULL,
  currency text NOT NULL CHECK (currency IN ('TWD','USD')),
  entry_kind text NOT NULL CHECK (entry_kind IN
    ('trade_settlement','external_capital_flow','data_correction_adjustment')),
  amount numeric NOT NULL,
  effective_at timestamptz NOT NULL,
  event_id uuid NOT NULL REFERENCES app_ledger.economic_effect(event_id),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- review chain (F3)
CREATE TABLE app_ledger.effect_review_event (
  review_event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  logical_effect_id uuid NOT NULL,
  review_no bigint NOT NULL,
  review_state text NOT NULL CHECK (review_state IN ('manual_review','cleared','quarantined')),
  reason text NOT NULL,
  actor_user_id uuid NULL,
  actor_via text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ere_unique UNIQUE (logical_effect_id, review_no),
  CONSTRAINT ere_no_pos CHECK (review_no >= 1)
);

CREATE VIEW app_ledger.effect_review_current AS
  SELECT DISTINCT ON (logical_effect_id) *
  FROM app_ledger.effect_review_event
  ORDER BY logical_effect_id, review_no DESC;

CREATE OR REPLACE FUNCTION app_ledger.review_append_only() RETURNS trigger
LANGUAGE plpgsql SET search_path = '' AS $$
BEGIN
  RAISE EXCEPTION 'review_event_append_only' USING ERRCODE='P0001';
END $$;
CREATE TRIGGER trg_review_append_only
  BEFORE UPDATE OR DELETE ON app_ledger.effect_review_event
  FOR EACH ROW EXECUTE FUNCTION app_ledger.review_append_only();

CREATE OR REPLACE FUNCTION app_ledger.canonical_review(
  p_logical uuid, p_state text, p_reason text, p_actor uuid, p_via text)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_cur text; v_no bigint;
BEGIN
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('review:'||p_logical::text, 0));
  SELECT review_state INTO v_cur FROM app_ledger.effect_review_current
   WHERE logical_effect_id = p_logical;
  v_cur := coalesce(v_cur, '(none)');
  IF NOT (
      (v_cur = '(none)'        AND p_state IN ('manual_review','quarantined'))
   OR (v_cur = 'manual_review' AND p_state IN ('cleared','quarantined'))
   OR (v_cur = 'cleared'       AND p_state IN ('manual_review','quarantined'))
   OR (v_cur = 'quarantined'   AND p_state = 'manual_review'))
  THEN RAISE EXCEPTION 'illegal_review_transition: % -> %', v_cur, p_state
       USING ERRCODE='P0001'; END IF;

  SELECT coalesce(pg_catalog.max(review_no),0)+1 INTO v_no
    FROM app_ledger.effect_review_event WHERE logical_effect_id = p_logical;
  INSERT INTO app_ledger.effect_review_event
    (logical_effect_id, review_no, review_state, reason, actor_user_id, actor_via)
  VALUES (p_logical, v_no, p_state, p_reason, p_actor, p_via);
  RETURN v_no;
END $$;

-- ---------------------------------------------------------------- canonical hashes
CREATE OR REPLACE FUNCTION app_ledger.tr_econ_hash(r public.trade_records)
RETURNS text LANGUAGE sql IMMUTABLE SET search_path = '' AS $$
  SELECT pg_catalog.md5((pg_catalog.to_jsonb(r)
    - 'current_price' - 'price_updated_at'
    - 'last_event_id' - 'last_projection_mutation_id')::text)
$$;

CREATE OR REPLACE FUNCTION app_ledger.cash_econ_hash(r app_ledger.portfolio_cash_ledger)
RETURNS text LANGUAGE sql IMMUTABLE SET search_path = '' AS $$
  SELECT pg_catalog.md5((pg_catalog.to_jsonb(r) - 'created_at')::text)
$$;

-- ---------------------------------------------------------------- trade_records guard (E3/F3)
CREATE OR REPLACE FUNCTION app_ledger.trade_records_economic_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_o jsonb; v_n jsonb; v_before text; v_after text; tok record; v_rowid uuid;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    v_o := pg_catalog.to_jsonb(OLD) - 'current_price' - 'price_updated_at';
    v_n := pg_catalog.to_jsonb(NEW) - 'current_price' - 'price_updated_at';
    IF v_o = v_n THEN RETURN NEW; END IF;   -- only whitelisted price fast path
    v_before := app_ledger.tr_econ_hash(OLD);
    v_rowid  := OLD.id;
  ELSIF TG_OP = 'INSERT' THEN
    v_before := NULL; v_rowid := NEW.id;
  ELSE
    v_before := app_ledger.tr_econ_hash(OLD); v_rowid := OLD.id;
  END IF;

  IF TG_OP <> 'DELETE' THEN
    -- guard owns provenance columns: client values are always overwritten
    NEW.last_event_id := NULL; NEW.last_projection_mutation_id := NULL;
    v_after := app_ledger.tr_econ_hash(NEW);
  END IF;

  SELECT * INTO tok FROM app_ledger.effect_projection_mutation m
   WHERE m.consumed = false
     AND m.target_table = 'trade_records'
     AND m.op = pg_catalog.lower(TG_OP)
     AND m.target_row_id = v_rowid
     AND m.before_hash IS NOT DISTINCT FROM v_before
     AND m.after_hash  IS NOT DISTINCT FROM v_after
   ORDER BY m.mutation_seq
   FOR UPDATE
   LIMIT 1;

  IF tok IS NULL THEN
    RAISE EXCEPTION 'unauthorized_trade_records_mutation: op=% row=%', TG_OP, v_rowid
      USING ERRCODE='P0001';
  END IF;
  IF TG_OP = 'INSERT' AND NEW.id IS DISTINCT FROM tok.target_row_id THEN
    RAISE EXCEPTION 'insert_token_row_mismatch' USING ERRCODE='P0001';
  END IF;

  UPDATE app_ledger.effect_projection_mutation SET consumed = true
   WHERE mutation_id = tok.mutation_id;

  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  NEW.last_event_id := tok.event_id;
  NEW.last_projection_mutation_id := tok.mutation_id;
  RETURN NEW;
END $$;
RESET ROLE;

CREATE TRIGGER trg_trade_records_guard
  BEFORE INSERT OR UPDATE OR DELETE ON public.trade_records
  FOR EACH ROW EXECUTE FUNCTION app_ledger.trade_records_economic_guard();
SET ROLE ledger_owner;

-- ---------------------------------------------------------------- cash ledger guard + append-only
CREATE OR REPLACE FUNCTION app_ledger.cash_ledger_guard() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE tok record; v_after text;
BEGIN
  IF TG_OP <> 'INSERT' THEN
    RAISE EXCEPTION 'cash_ledger_append_only' USING ERRCODE='P0001';
  END IF;
  v_after := app_ledger.cash_econ_hash(NEW);
  SELECT * INTO tok FROM app_ledger.effect_projection_mutation m
   WHERE m.consumed = false AND m.target_table='portfolio_cash_ledger'
     AND m.op='insert' AND m.target_row_id = NEW.cash_entry_id
     AND m.after_hash IS NOT DISTINCT FROM v_after
   FOR UPDATE LIMIT 1;
  IF tok IS NULL THEN
    RAISE EXCEPTION 'unauthorized_cash_ledger_mutation' USING ERRCODE='P0001';
  END IF;
  UPDATE app_ledger.effect_projection_mutation SET consumed=true WHERE mutation_id=tok.mutation_id;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_cash_ledger_guard
  BEFORE INSERT OR UPDATE OR DELETE ON app_ledger.portfolio_cash_ledger
  FOR EACH ROW EXECUTE FUNCTION app_ledger.cash_ledger_guard();

-- ---------------------------------------------------------------- effect append-only (E4)
CREATE OR REPLACE FUNCTION app_ledger.effect_append_only() RETURNS trigger
LANGUAGE plpgsql SET search_path = '' AS $$
DECLARE o jsonb; n jsonb;
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'effect_delete_forbidden' USING ERRCODE='P0001'; END IF;
  o := pg_catalog.to_jsonb(OLD) - 'state' - 'visible_at' - 'state_changed_at';
  n := pg_catalog.to_jsonb(NEW) - 'state' - 'visible_at' - 'state_changed_at';
  IF o <> n THEN
    RAISE EXCEPTION 'effect_payload_immutable' USING ERRCODE='P0001'; END IF;
  IF NEW.state IS DISTINCT FROM OLD.state
     AND NOT ((OLD.state='reserved' AND NEW.state IN ('applied','failed'))
           OR (OLD.state='applied'  AND NEW.state='superseded'))
  THEN RAISE EXCEPTION 'effect_illegal_state_transition: % -> %', OLD.state, NEW.state
       USING ERRCODE='P0001'; END IF;
  IF NEW.visible_at IS DISTINCT FROM OLD.visible_at THEN
    IF OLD.visible_at IS NOT NULL THEN
      RAISE EXCEPTION 'visible_at_immutable_once_set' USING ERRCODE='P0001'; END IF;
    IF NEW.state <> 'applied' THEN
      RAISE EXCEPTION 'publish_requires_applied_state' USING ERRCODE='P0001'; END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_effect_append_only
  BEFORE UPDATE OR DELETE ON app_ledger.economic_effect
  FOR EACH ROW EXECUTE FUNCTION app_ledger.effect_append_only();

-- ---------------------------------------------------------------- closed lot conservation (E1 d)
CREATE OR REPLACE FUNCTION app_ledger.assert_closed_lot_conservation(p_event uuid)
RETURNS void LANGUAGE plpgsql SET search_path = '' AS $$
DECLARE e record; v_realized numeric; v_cash numeric; v_cost numeric;
BEGIN
  SELECT * INTO e FROM app_ledger.economic_effect WHERE event_id = p_event;
  SELECT coalesce(pg_catalog.sum(realized_delta),0) INTO v_realized
    FROM app_ledger.effect_projection_mutation WHERE event_id=p_event AND row_role='closed_lot';
  SELECT coalesce(pg_catalog.sum(cost_delta),0) INTO v_cost
    FROM app_ledger.effect_projection_mutation
    WHERE event_id=p_event AND row_role IN ('open_position','closed_lot');
  SELECT coalesce(pg_catalog.sum(cash_delta),0) INTO v_cash
    FROM app_ledger.effect_projection_mutation WHERE event_id=p_event AND row_role='cash_leg';
  -- trade settlement identity: cash = -cost_delta + realized  (fees folded into cash & realized)
  IF e.provenance IN ('signal_execution','historical_fill')
     AND v_cash <> (-1)*v_cost + v_realized THEN
    RAISE EXCEPTION 'closed_lot_conservation_violation: cash=% cost=% realized=%',
      v_cash, v_cost, v_realized USING ERRCODE='P0001';
  END IF;
END $$;

-- ---------------------------------------------------------------- deferred semantic invariant (E1/F3)
CREATE OR REPLACE FUNCTION app_ledger.assert_effect_semantics() RETURNS trigger
LANGUAGE plpgsql SET search_path = '' AS $$
DECLARE e record; n int; c int; q_open int; q_closed int; cash_sum numeric;
BEGIN
  SELECT * INTO e FROM app_ledger.economic_effect WHERE event_id = NEW.event_id;
  IF e IS NULL THEN RETURN NULL; END IF;

  SELECT pg_catalog.count(*), pg_catalog.count(*) FILTER (WHERE consumed) INTO n, c
    FROM app_ledger.effect_projection_mutation WHERE event_id = e.event_id;
  IF n <> e.expected_mutation_count OR c <> n THEN
    RAISE EXCEPTION 'effect_mutation_set_mismatch: expected=% actual=% consumed=%',
      e.expected_mutation_count, n, c USING ERRCODE='P0001'; END IF;

  IF EXISTS (SELECT 1 FROM pg_catalog.generate_series(1, n) g
              WHERE NOT EXISTS (SELECT 1 FROM app_ledger.effect_projection_mutation m
                                 WHERE m.event_id=e.event_id AND m.mutation_seq=g))
  THEN RAISE EXCEPTION 'effect_mutation_seq_gap' USING ERRCODE='P0001'; END IF;

  -- (a) context binding, NULL-safe
  IF EXISTS (SELECT 1 FROM app_ledger.effect_projection_mutation m
              WHERE m.event_id = e.event_id
                AND (m.expert_id IS DISTINCT FROM e.expert_id
                  OR m.currency  IS DISTINCT FROM e.currency
                  OR (m.row_role <> 'cash_leg' AND
                      (m.market IS DISTINCT FROM e.market
                    OR m.instrument_key IS DISTINCT FROM e.instrument_key))))
  THEN RAISE EXCEPTION 'effect_token_context_mismatch' USING ERRCODE='P0001'; END IF;

  -- (b) quantity conservation
  SELECT coalesce(pg_catalog.sum(qty_delta) FILTER (WHERE row_role='open_position'),0),
         coalesce(pg_catalog.sum(qty_delta) FILTER (WHERE row_role='closed_lot'),0)
    INTO q_open, q_closed
    FROM app_ledger.effect_projection_mutation WHERE event_id=e.event_id;
  IF q_open <> e.qty_delta THEN
    RAISE EXCEPTION 'open_qty_delta_mismatch: tokens=% event=%', q_open, e.qty_delta
      USING ERRCODE='P0001'; END IF;
  IF e.action IN ('trim','sell','exit') AND q_closed <> 0 AND q_closed <> -q_open THEN
    RAISE EXCEPTION 'closed_lot_reclass_mismatch' USING ERRCODE='P0001'; END IF;

  -- (c) cash conservation
  SELECT coalesce(pg_catalog.sum(cash_delta) FILTER (WHERE row_role='cash_leg'),0) INTO cash_sum
    FROM app_ledger.effect_projection_mutation WHERE event_id=e.event_id;
  IF e.cash_delta IS NULL THEN
    IF cash_sum <> 0 THEN RAISE EXCEPTION 'unexpected_cash_leg' USING ERRCODE='P0001'; END IF;
  ELSIF cash_sum <> e.cash_delta THEN
    RAISE EXCEPTION 'cash_delta_mismatch: tokens=% event=%', cash_sum, e.cash_delta
      USING ERRCODE='P0001'; END IF;

  -- (d) F2 correction semantics: a quantity_adjustment is cash- and P&L-neutral
  IF e.provenance = 'quantity_adjustment' THEN
    IF coalesce(e.cash_delta,0) <> 0 OR cash_sum <> 0 THEN
      RAISE EXCEPTION 'quantity_adjustment_must_be_cash_neutral: event=% tokens=%',
        coalesce(e.cash_delta,0), cash_sum USING ERRCODE='P0001'; END IF;
    IF coalesce((SELECT pg_catalog.sum(realized_delta)
                      FROM app_ledger.effect_projection_mutation
                     WHERE event_id=e.event_id),0) <> 0 THEN
      RAISE EXCEPTION 'quantity_adjustment_must_not_create_pnl' USING ERRCODE='P0001'; END IF;
  END IF;
  -- (e) F2 equity_bridge: cash-only, never a quantity or P&L event
  IF e.provenance = 'equity_bridge' THEN
    IF coalesce(e.qty_delta,0) <> 0 OR q_open <> 0 OR q_closed <> 0 THEN
      RAISE EXCEPTION 'equity_bridge_must_not_move_quantity' USING ERRCODE='P0001'; END IF;
    IF coalesce(e.cash_delta,0) = 0 THEN
      RAISE EXCEPTION 'equity_bridge_requires_cash_delta' USING ERRCODE='P0001'; END IF;
  END IF;

  PERFORM app_ledger.assert_closed_lot_conservation(e.event_id);
  RETURN NULL;
END $$;

CREATE CONSTRAINT TRIGGER trg_effect_semantics
  AFTER INSERT ON app_ledger.economic_effect
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
  EXECUTE FUNCTION app_ledger.assert_effect_semantics();

-- ---------------------------------------------------------------- signal delete guard (E5)
CREATE OR REPLACE FUNCTION app_ledger.forbid_delete_applied_signal() RETURNS trigger
LANGUAGE plpgsql SET search_path = '' AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM app_ledger.economic_effect e
              WHERE e.logical_effect_id = OLD.logical_effect_id
                AND e.state IN ('applied','superseded'))
  THEN RAISE EXCEPTION 'signal_delete_forbidden_after_effect' USING ERRCODE='P0001'; END IF;
  RETURN OLD;
END $$;
RESET ROLE;
CREATE TRIGGER trg_forbid_delete_applied_signal
  BEFORE DELETE ON public.expert_signals
  FOR EACH ROW EXECUTE FUNCTION app_ledger.forbid_delete_applied_signal();
SET ROLE ledger_owner;

-- ---------------------------------------------------------------- privilege containment (E6)
REVOKE ALL ON ALL TABLES IN SCHEMA app_ledger FROM anon, authenticated, service_role, PUBLIC;
REVOKE ALL ON SCHEMA app_ledger FROM anon, authenticated, service_role, PUBLIC;
RESET ROLE;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.trade_records
  FROM anon, authenticated, service_role, PUBLIC;
GRANT SELECT ON public.trade_records TO authenticated, service_role;
GRANT UPDATE (current_price, price_updated_at) ON public.trade_records TO service_role;
SET ROLE ledger_owner;

-- E0: canonical writers (only path allowed to mutate economics)

CREATE OR REPLACE FUNCTION app_ledger.canonical_apply_effect(p jsonb)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  v_event uuid := pg_catalog.gen_random_uuid();
  v_action text := p->>'action';
  v_expert uuid := (p->>'expert_id')::uuid;
  v_ikey text := p->>'instrument_key';
  v_market text := p->>'market';
  v_cur text := coalesce(p->>'currency','TWD');
  v_qty int := coalesce((p->>'qty')::int, 0);
  v_price numeric := (p->>'price')::numeric;
  v_fees numeric := coalesce((p->>'fees')::numeric, 0);
  v_eff timestamptz := coalesce((p->>'effective_at')::timestamptz, pg_catalog.now());
  v_prov public.effect_provenance := coalesce((p->>'provenance')::public.effect_provenance,'signal_execution');
  v_reason text := coalesce(p->>'reason','');
  v_logical uuid := pg_catalog.gen_random_uuid();  -- D5: never trust client-supplied logical id
  v_signal uuid := (p->>'signal_id')::uuid;
  v_open public.trade_records;
  v_openid uuid; v_closedid uuid; v_cashid uuid;
  v_cash numeric; v_cost numeric; v_realized numeric := 0;
  v_expected int; v_qdelta int;
  v_newopen public.trade_records; v_newclosed public.trade_records;
  v_cashrow app_ledger.portfolio_cash_ledger;
  v_avg numeric;
BEGIN
  -- D5: a logical id may only be reused via an explicit restore of an existing chain
  IF p ? 'restore_logical_effect_id' THEN
    SELECT e.logical_effect_id INTO v_logical
      FROM app_ledger.economic_effect e
     WHERE e.logical_effect_id = (p->>'restore_logical_effect_id')::uuid
       AND e.expert_id = (p->>'expert_id')::uuid
     LIMIT 1;
    IF v_logical IS NULL THEN
      RAISE EXCEPTION 'unknown_restore_logical_effect_id: %', p->>'restore_logical_effect_id'
        USING ERRCODE = '23514';
    END IF;
  END IF;
  IF v_ikey IS NOT NULL THEN
    SELECT * INTO v_open FROM public.trade_records t
     WHERE t.expert_id=v_expert AND t.instrument_key=v_ikey
       AND t.status='open' AND t.quantity > 0
     FOR UPDATE;
  END IF;

  IF v_action IN ('buy','add') THEN
    v_cost := v_qty * v_price; v_cash := -(v_cost) - v_fees; v_qdelta := v_qty;
    v_expected := 2;
  ELSIF v_action IN ('trim','exit') THEN
    IF v_open IS NULL THEN RAISE EXCEPTION 'no_open_position' USING ERRCODE='P0001'; END IF;
    IF v_qty > v_open.quantity THEN RAISE EXCEPTION 'oversell' USING ERRCODE='P0001'; END IF;
    v_avg := v_open.entry_price;
    v_cost := -(v_qty * v_avg);
    v_realized := v_qty * (v_price - v_avg) - v_fees;
    v_cash := v_qty * v_price - v_fees;
    v_qdelta := -v_qty; v_expected := 3;
  ELSIF v_action = 'capital_flow' THEN
    v_cash := (p->>'amount')::numeric; v_cost := 0; v_qdelta := 0; v_expected := 1;
  ELSIF v_action = 'equity_bridge' THEN
    v_cash := (p->>'amount')::numeric; v_cost := 0; v_qdelta := 0; v_expected := 1;
  ELSIF v_action = 'quantity_adjustment' THEN
    IF v_open IS NULL THEN RAISE EXCEPTION 'no_open_position' USING ERRCODE='P0001'; END IF;
    v_cash := NULL; v_qdelta := v_qty;                       -- qty may be +/-
    v_cost := coalesce((p->>'cost_delta')::numeric, v_qty * v_open.entry_price);
    v_expected := 1;
  ELSE
    RAISE EXCEPTION 'unsupported_action: %', v_action USING ERRCODE='P0001';
  END IF;

  INSERT INTO app_ledger.economic_effect(
    event_id, logical_effect_id, expert_id, origin_signal_id, market, instrument,
    instrument_key, action, qty_delta, currency, cash_delta, price, fees, effective_at,
    provenance, actor_via, reason, expected_mutation_count, state)
  VALUES (v_event, v_logical, v_expert, v_signal, v_market, coalesce(p->>'instrument', v_ikey),
    v_ikey, v_action, v_qdelta, v_cur, v_cash, v_price, v_fees, v_eff,
    v_prov, coalesce(p->>'actor_via','canonical'), v_reason, v_expected, 'reserved');

  ------------------------------------------------------------------ position mutations
  IF v_action = 'buy' OR (v_action='add' AND v_open IS NULL) THEN
    v_openid := pg_catalog.gen_random_uuid();
    v_newopen := ROW(v_openid, v_expert, v_market, coalesce(p->>'instrument', v_ikey), v_ikey,
      v_cur, v_qty, v_price, NULL, 'open', v_eff, NULL, v_signal, NULL, NULL, NULL, NULL, NULL);
    INSERT INTO app_ledger.effect_projection_mutation(
      event_id, mutation_seq, target_table, target_row_id, op, row_role, expert_id, currency,
      market, instrument_key, qty_delta, cost_delta, after_hash)
    VALUES (v_event, 1, 'trade_records', v_openid, 'insert', 'open_position', v_expert, v_cur,
      v_market, v_ikey, v_qty, v_cost, app_ledger.tr_econ_hash(v_newopen));
    INSERT INTO public.trade_records VALUES (v_newopen.*);

  ELSIF v_action = 'add' THEN
    v_openid := v_open.id;
    v_avg := (v_open.quantity * v_open.entry_price + v_qty * v_price) / (v_open.quantity + v_qty);
    v_newopen := v_open;
    v_newopen.quantity := v_open.quantity + v_qty;
    v_newopen.entry_price := v_avg;
    INSERT INTO app_ledger.effect_projection_mutation(
      event_id, mutation_seq, target_table, target_row_id, op, row_role, expert_id, currency,
      market, instrument_key, qty_delta, cost_delta, before_hash, after_hash)
    VALUES (v_event, 1, 'trade_records', v_openid, 'update', 'open_position', v_expert, v_cur,
      v_market, v_ikey, v_qty, v_cost,
      app_ledger.tr_econ_hash(v_open), app_ledger.tr_econ_hash(v_newopen));
    UPDATE public.trade_records SET quantity=v_newopen.quantity, entry_price=v_newopen.entry_price
      WHERE id=v_openid;

  ELSIF v_action IN ('trim','exit') THEN
    v_openid := v_open.id;
    v_newopen := v_open;
    v_newopen.quantity := v_open.quantity - v_qty;
    IF v_newopen.quantity = 0 THEN v_newopen.status := 'closed'; v_newopen.exit_date := v_eff; END IF;
    INSERT INTO app_ledger.effect_projection_mutation(
      event_id, mutation_seq, target_table, target_row_id, op, row_role, expert_id, currency,
      market, instrument_key, qty_delta, cost_delta, before_hash, after_hash)
    VALUES (v_event, 1, 'trade_records', v_openid, 'update', 'open_position', v_expert, v_cur,
      v_market, v_ikey, -v_qty, v_cost,
      app_ledger.tr_econ_hash(v_open), app_ledger.tr_econ_hash(v_newopen));
    UPDATE public.trade_records SET quantity=v_newopen.quantity, status=v_newopen.status,
      exit_date=v_newopen.exit_date WHERE id=v_openid;

    v_closedid := pg_catalog.gen_random_uuid();
    v_newclosed := ROW(v_closedid, v_expert, v_market, v_open.instrument, v_ikey, v_cur,
      v_qty, v_avg, v_price, 'closed', v_open.entry_date, v_eff, v_signal, NULL,
      NULL, NULL, NULL, NULL);
    INSERT INTO app_ledger.effect_projection_mutation(
      event_id, mutation_seq, target_table, target_row_id, op, row_role, expert_id, currency,
      market, instrument_key, qty_delta, cost_delta, realized_delta, after_hash)
    VALUES (v_event, 2, 'trade_records', v_closedid, 'insert', 'closed_lot', v_expert, v_cur,
      v_market, v_ikey, v_qty, 0, v_realized, app_ledger.tr_econ_hash(v_newclosed));
    INSERT INTO public.trade_records VALUES (v_newclosed.*);

  ELSIF v_action = 'quantity_adjustment' THEN
    v_openid := v_open.id;
    v_newopen := v_open;
    v_newopen.quantity := v_open.quantity + v_qty;
    INSERT INTO app_ledger.effect_projection_mutation(
      event_id, mutation_seq, target_table, target_row_id, op, row_role, expert_id, currency,
      market, instrument_key, qty_delta, cost_delta, before_hash, after_hash)
    VALUES (v_event, 1, 'trade_records', v_openid, 'update', 'open_position', v_expert, v_cur,
      v_market, v_ikey, v_qty, v_cost,
      app_ledger.tr_econ_hash(v_open), app_ledger.tr_econ_hash(v_newopen));
    UPDATE public.trade_records SET quantity=v_newopen.quantity WHERE id=v_openid;
  END IF;

  ------------------------------------------------------------------ cash leg
  IF v_cash IS NOT NULL THEN
    v_cashid := pg_catalog.gen_random_uuid();
    v_cashrow := ROW(v_cashid, v_expert, v_cur,
      CASE WHEN v_action='capital_flow' THEN 'external_capital_flow'
           WHEN v_action='equity_bridge' THEN 'data_correction_adjustment'
           ELSE 'trade_settlement' END,
      v_cash, v_eff, v_event, pg_catalog.now());
    INSERT INTO app_ledger.effect_projection_mutation(
      event_id, mutation_seq, target_table, target_row_id, op, row_role, expert_id, currency,
      qty_delta, cash_delta, realized_delta, after_hash)
    VALUES (v_event, CASE WHEN v_action IN ('trim','exit') THEN 3 ELSE
                          CASE WHEN v_action IN ('capital_flow','equity_bridge') THEN 1 ELSE 2 END END,
      'portfolio_cash_ledger', v_cashid, 'insert', 'cash_leg', v_expert, v_cur,
      0, v_cash, 0, app_ledger.cash_econ_hash(v_cashrow));
    INSERT INTO app_ledger.portfolio_cash_ledger VALUES (v_cashrow.*);
  END IF;

  UPDATE app_ledger.economic_effect SET state='applied', state_changed_at=pg_catalog.now()
    WHERE event_id=v_event;
  RETURN v_event;
END $$;

REVOKE EXECUTE ON FUNCTION app_ledger.canonical_apply_effect(jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION app_ledger.canonical_review(uuid,text,text,uuid,text) FROM PUBLIC;

-- E0: public projection (F1 per-expert active pointer, F2 correction/return semantics)

CREATE TABLE public.public_position_projection (
  projection_version bigint NOT NULL,
  expert_id uuid NOT NULL,
  instrument_key text NOT NULL,
  instrument text NOT NULL,
  market text NOT NULL,
  currency text NOT NULL,
  quantity integer NOT NULL,
  quantity_unit text NOT NULL DEFAULT 'share',
  avg_cost numeric NOT NULL,
  cost_value numeric NOT NULL,
  valuation_price numeric NULL,
  price_as_of date NULL,
  price_source text NULL,
  valuation_status text NOT NULL
    CHECK (valuation_status IN ('valued','stale','unpriced','unsupported')),
  market_value numeric NULL,
  -- E7 fail-closed: a money number may exist only for an actually priced status
  CONSTRAINT ppp_valuation_ck CHECK
    ((market_value IS NOT NULL) = (valuation_status IN ('valued','stale'))),
  fx_rate numeric NULL,
  fx_as_of date NULL,
  fx_source text NULL,
  PRIMARY KEY (projection_version, expert_id, instrument_key)
);

CREATE TABLE public.public_portfolio_state (
  projection_version bigint NOT NULL,
  expert_id uuid NOT NULL,
  currency text NOT NULL,
  starting_capital numeric NOT NULL,
  external_capital_flow_total numeric NOT NULL DEFAULT 0,
  data_correction_adjustment_total numeric NOT NULL DEFAULT 0,
  realized_pnl numeric NOT NULL DEFAULT 0,
  open_cost numeric NOT NULL,
  cash numeric NOT NULL,
  market_value numeric NULL,
  equity numeric NULL,
  incomplete_reason text NULL,
  -- E7 fail-closed: equity is published only when nothing is missing
  CONSTRAINT pps_equity_ck CHECK ((equity IS NULL) = (incomplete_reason IS NOT NULL)),
  PRIMARY KEY (projection_version, expert_id, currency)
);

CREATE TABLE public.public_nav_daily (
  projection_version bigint NOT NULL,
  expert_id uuid NOT NULL,
  currency text NOT NULL,
  trade_date date NOT NULL,
  cash numeric NOT NULL,
  market_value numeric NULL,
  equity numeric NULL,
  external_capital_flow numeric NOT NULL DEFAULT 0,
  data_correction_adjustment numeric NOT NULL DEFAULT 0,
  daily_return numeric NULL,
  price_as_of date NULL,
  fx_as_of date NULL,
  completeness text NOT NULL CHECK (completeness IN ('complete','partial','unavailable')),
  correction_flag boolean NOT NULL DEFAULT false,
  correction_kind text NULL,
  reporting_basis text NOT NULL CHECK (reporting_basis IN ('as_reported','restated')),
  PRIMARY KEY (projection_version, expert_id, currency, trade_date, reporting_basis)
);

-- F1: per-expert active pointer
CREATE TABLE public.public_projection_active (
  expert_id uuid PRIMARY KEY,
  active_version bigint NOT NULL,
  activated_at timestamptz NOT NULL DEFAULT now()
);

-- F1: the pointer is monotonic per expert and may only point at a materialised version
CREATE OR REPLACE FUNCTION app_ledger.projection_pointer_guard()
RETURNS trigger LANGUAGE plpgsql SET search_path = '' AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.active_version <= OLD.active_version THEN
    RAISE EXCEPTION 'projection_pointer_regression: % -> %', OLD.active_version, NEW.active_version
      USING ERRCODE = 'P0001';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.public_position_projection p
                  WHERE p.expert_id = NEW.expert_id AND p.projection_version = NEW.active_version)
     AND NOT EXISTS (SELECT 1 FROM public.public_portfolio_state s
                  WHERE s.expert_id = NEW.expert_id AND s.projection_version = NEW.active_version)
  THEN
    RAISE EXCEPTION 'projection_pointer_unmaterialised: expert=% version=%',
      NEW.expert_id, NEW.active_version USING ERRCODE = 'P0001';
  END IF;
  RETURN NEW;
END $$;
RESET ROLE;

CREATE TRIGGER trg_projection_pointer_guard
  BEFORE INSERT OR UPDATE ON public.public_projection_active
  FOR EACH ROW EXECUTE FUNCTION app_ledger.projection_pointer_guard();
SET ROLE ledger_owner;

CREATE VIEW public.public_position_active AS
  SELECT p.* FROM public.public_position_projection p
  JOIN public.public_projection_active a
    ON a.expert_id = p.expert_id AND a.active_version = p.projection_version;

CREATE VIEW public.public_portfolio_active AS
  SELECT s.* FROM public.public_portfolio_state s
  JOIN public.public_projection_active a
    ON a.expert_id = s.expert_id AND a.active_version = s.projection_version;

CREATE VIEW public.public_nav_active AS
  SELECT n.* FROM public.public_nav_daily n
  JOIN public.public_projection_active a
    ON a.expert_id = n.expert_id AND a.active_version = n.projection_version;
RESET ROLE;

GRANT SELECT ON public.public_position_active, public.public_portfolio_active,
                public.public_nav_active, public.public_projection_active
  TO anon, authenticated, service_role;
REVOKE ALL ON public.public_position_projection, public.public_portfolio_state,
              public.public_nav_daily
  FROM anon, authenticated, service_role, PUBLIC;
SET ROLE ledger_owner;

-- ---------------------------------------------------------------- valuation helper
CREATE OR REPLACE FUNCTION app_ledger.value_instrument(
  p_ikey text, p_market text, p_as_of date,
  OUT price numeric, OUT price_as_of date, OUT status text)
LANGUAGE plpgsql SET search_path = '' AS $$
DECLARE v_lag int;
BEGIN
  IF p_ikey LIKE '%/%' OR p_ikey LIKE '%+%' THEN     -- US native combo: unsupported
    price := NULL; price_as_of := NULL; status := 'unsupported'; RETURN;
  END IF;
  SELECT d.close_price, d.trade_date INTO price, price_as_of
    FROM public.daily_price_snapshots d
   WHERE d.symbol = pg_catalog.split_part(p_ikey,':',1) AND d.trade_date <= p_as_of
   ORDER BY d.trade_date DESC LIMIT 1;
  IF price IS NULL THEN status := 'unpriced'; RETURN; END IF;
  SELECT pg_catalog.count(*) INTO v_lag
    FROM public.daily_price_snapshots d
   WHERE d.market = p_market AND d.trade_date > price_as_of AND d.trade_date <= p_as_of;
  status := CASE WHEN v_lag > 20 THEN 'unpriced' WHEN v_lag > 5 THEN 'stale' ELSE 'valued' END;
  IF status = 'unpriced' THEN price := NULL; END IF;
END $$;

-- ---------------------------------------------------------------- rebuild + atomic activate
CREATE OR REPLACE FUNCTION app_ledger.canonical_publish(
  p_expert uuid, p_as_of date DEFAULT NULL, p_basis text DEFAULT 'as_reported',
  p_fail boolean DEFAULT false)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  v_ver bigint; v_asof date := coalesce(p_as_of, (pg_catalog.now())::date);
  r record; v_prev numeric; v_prev_eq numeric;
BEGIN
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('proj:'||p_expert::text, 0));
  v_ver := pg_catalog.nextval('app_ledger.projection_version_seq');

  ------------------------------------------------------------------ positions
  INSERT INTO public.public_position_projection(
    projection_version, expert_id, instrument_key, instrument, market, currency,
    quantity, avg_cost, cost_value, valuation_price, price_as_of, price_source,
    valuation_status, market_value)
  SELECT v_ver, t.expert_id, t.instrument_key, t.instrument, t.market, t.currency,
         t.quantity, t.entry_price, t.quantity*t.entry_price,
         v.price, v.price_as_of, CASE WHEN v.price IS NULL THEN NULL ELSE 'daily_snapshot' END,
         v.status,
         CASE WHEN v.price IS NULL THEN NULL ELSE t.quantity*v.price END
    FROM public.trade_records t
    CROSS JOIN LATERAL app_ledger.value_instrument(t.instrument_key, t.market, v_asof) v
   WHERE t.expert_id = p_expert AND t.status='open' AND t.quantity > 0;

  ------------------------------------------------------------------ portfolio state per currency
  INSERT INTO public.public_portfolio_state(
    projection_version, expert_id, currency, starting_capital,
    external_capital_flow_total, data_correction_adjustment_total, realized_pnl,
    open_cost, cash, market_value, equity, incomplete_reason)
  SELECT v_ver, p_expert, c.currency,
         (SELECT e.starting_capital FROM public.experts e WHERE e.id=p_expert),
         c.ext, c.corr, c.realized, c.open_cost,
         (SELECT e.starting_capital FROM public.experts e WHERE e.id=p_expert) + c.cash_sum,
         c.mv, CASE WHEN c.mv IS NULL THEN NULL ELSE
           (SELECT e.starting_capital FROM public.experts e WHERE e.id=p_expert) + c.cash_sum + c.mv END,
         CASE WHEN c.mv IS NULL THEN 'unpriced_or_unsupported_position' ELSE NULL END
    FROM (
      SELECT cur AS currency,
        coalesce(sum(amount) FILTER (WHERE entry_kind='external_capital_flow'),0) ext,
        coalesce(sum(amount) FILTER (WHERE entry_kind='data_correction_adjustment'),0) corr,
        coalesce(sum(amount),0) cash_sum,
        (SELECT coalesce(sum(m.realized_delta),0) FROM app_ledger.effect_projection_mutation m
          WHERE m.expert_id=p_expert AND m.currency=x.cur) realized,
        (SELECT coalesce(sum(t.quantity*t.entry_price),0) FROM public.trade_records t
          WHERE t.expert_id=p_expert AND t.currency=x.cur AND t.status='open' AND t.quantity>0) open_cost,
        (SELECT CASE WHEN bool_or(pp.market_value IS NULL) THEN NULL ELSE coalesce(sum(pp.market_value),0) END
           FROM public.public_position_projection pp
          WHERE pp.projection_version=v_ver AND pp.expert_id=p_expert AND pp.currency=x.cur) mv
      FROM (SELECT DISTINCT currency cur FROM app_ledger.portfolio_cash_ledger
             WHERE expert_id=p_expert
            UNION SELECT DISTINCT currency FROM public.trade_records
             WHERE expert_id=p_expert) x
      LEFT JOIN app_ledger.portfolio_cash_ledger l
        ON l.expert_id=p_expert AND l.currency=x.cur
      GROUP BY x.cur
    ) c;

  ------------------------------------------------------------------ NAV daily (per currency, per date)
  FOR r IN
    SELECT d.trade_date, cur.currency
      FROM (SELECT DISTINCT effective_at::date trade_date
              FROM app_ledger.economic_effect WHERE expert_id=p_expert
            UNION SELECT DISTINCT trade_date FROM public.daily_price_snapshots
             WHERE trade_date <= v_asof
               AND trade_date >= (SELECT min(effective_at)::date FROM app_ledger.economic_effect
                                   WHERE expert_id=p_expert)) d
      CROSS JOIN (SELECT DISTINCT currency FROM app_ledger.portfolio_cash_ledger
                   WHERE expert_id=p_expert) cur
     WHERE d.trade_date <= v_asof
     ORDER BY d.trade_date
  LOOP
    DECLARE
      v_cash numeric; v_mv numeric; v_eq numeric; v_ext numeric; v_corr numeric;
      v_qadj boolean; v_ret numeric; v_complete text; v_kind text; v_unpriced boolean;
    BEGIN
      SELECT coalesce(sum(amount),0),
             coalesce(sum(amount) FILTER (WHERE entry_kind='external_capital_flow'
                       AND effective_at::date=r.trade_date),0),
             coalesce(sum(amount) FILTER (WHERE entry_kind='data_correction_adjustment'
                       AND effective_at::date=r.trade_date),0)
        INTO v_cash, v_ext, v_corr
        FROM app_ledger.portfolio_cash_ledger
       WHERE expert_id=p_expert AND currency=r.currency AND effective_at::date <= r.trade_date;
      v_cash := v_cash + (SELECT starting_capital FROM public.experts WHERE id=p_expert);

      SELECT coalesce(sum(q.qty * v.price),0),
             bool_or(v.price IS NULL)
        INTO v_mv, v_unpriced
        FROM (SELECT m.instrument_key ikey, m.market mk, sum(m.qty_delta) qty
                FROM app_ledger.effect_projection_mutation m
                JOIN app_ledger.economic_effect e ON e.event_id=m.event_id
               WHERE m.expert_id=p_expert AND m.currency=r.currency
                 AND m.row_role='open_position' AND e.effective_at::date <= r.trade_date
               GROUP BY 1,2 HAVING sum(m.qty_delta) <> 0) q
        CROSS JOIN LATERAL app_ledger.value_instrument(q.ikey, q.mk, r.trade_date) v;
      IF coalesce(v_unpriced,false) THEN v_mv := NULL; END IF;
      v_eq := CASE WHEN v_mv IS NULL THEN NULL ELSE v_cash + v_mv END;

      SELECT EXISTS (SELECT 1 FROM app_ledger.economic_effect e
                      WHERE e.expert_id=p_expert AND e.currency=r.currency
                        AND e.effective_at::date=r.trade_date
                        AND e.provenance='quantity_adjustment')
        INTO v_qadj;

      SELECT n.equity INTO v_prev_eq FROM public.public_nav_daily n
       WHERE n.projection_version=v_ver AND n.expert_id=p_expert AND n.currency=r.currency
         AND n.trade_date < r.trade_date AND n.reporting_basis=p_basis
       ORDER BY n.trade_date DESC LIMIT 1;

      IF p_basis='as_reported' AND v_qadj THEN
        v_ret := NULL; v_complete := 'partial'; v_kind := 'quantity_adjustment';
      ELSIF v_eq IS NULL OR v_prev_eq IS NULL OR v_prev_eq = 0 THEN
        v_ret := NULL;
        v_complete := CASE WHEN v_eq IS NULL THEN 'unavailable' ELSE 'complete' END;
        v_kind := CASE WHEN v_corr <> 0 THEN 'equity_bridge' ELSE NULL END;
      ELSE
        v_ret := (v_eq - v_prev_eq - v_ext
                  - CASE WHEN p_basis='as_reported' THEN v_corr ELSE 0 END) / v_prev_eq;
        v_complete := 'complete';
        v_kind := CASE WHEN v_corr <> 0 THEN 'equity_bridge' ELSE NULL END;
      END IF;

      INSERT INTO public.public_nav_daily(
        projection_version, expert_id, currency, trade_date, cash, market_value, equity,
        external_capital_flow, data_correction_adjustment, daily_return, price_as_of,
        completeness, correction_flag, correction_kind, reporting_basis)
      VALUES (v_ver, p_expert, r.currency, r.trade_date, v_cash, v_mv, v_eq,
        v_ext, v_corr, v_ret, r.trade_date, v_complete,
        (v_qadj OR v_corr <> 0), v_kind, p_basis);
    END;
  END LOOP;

  IF p_fail THEN RAISE EXCEPTION 'simulated_replay_failure' USING ERRCODE='P0001'; END IF;

  INSERT INTO public.public_projection_active(expert_id, active_version)
  VALUES (p_expert, v_ver)
  ON CONFLICT (expert_id) DO UPDATE
    SET active_version = EXCLUDED.active_version, activated_at = pg_catalog.now()
    WHERE public.public_projection_active.active_version < EXCLUDED.active_version;

  RETURN v_ver;
END $$;

REVOKE EXECUTE ON FUNCTION app_ledger.canonical_publish(uuid,date,text,boolean) FROM PUBLIC;
RESET ROLE;
