#!/usr/bin/env python3
"""Generate db/r1/c/S0/lineage.sql from the repo migration filenames.

`supabase_migrations` is not readable by the sandbox psql role, so the S0-1
gate runs this generated SQL through the read-only database query tool and the
single JSON row it returns is stored verbatim as db/r1/c/S0/lineage.json.
Read-only: the generated statement is a single SELECT.
"""
import hashlib
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
MIG = os.path.join(ROOT, "supabase", "migrations")
OUT = os.path.join(ROOT, "db", "r1", "c", "S0", "lineage.sql")

KNOWN_PRE_REPO = ['20260227131741', '20260227155729', '20260308110124', '20260316122524', '20260408065758']
DUPLICATE_RECORDS = {
    '20260721135648': '20260721135623',
    '20260722023140': '20260722023118',
    '20260724071600': '20260724071542',
    '20260725213324': '20260725213311',
    '20260729132638': '20260729132621',
}
APPLIED_NOT_RECORDED = ['20260812211500']

repo = sorted(re.match(r"^(\d{14})_", f).group(1)
              for f in os.listdir(MIG) if re.match(r"^\d{14}_.+\.sql$", f))
assert len(repo) == len(set(repo)), "duplicate repo migration timestamps"

repo_list = ",".join(repo)
known = ",".join(KNOWN_PRE_REPO)
dups = ",".join(DUPLICATE_RECORDS)
applied = ",".join(APPLIED_NOT_RECORDED)

sql = f"""-- S0-1 migration lineage (read-only). Generated by gen_lineage_sql.py.
-- repo_version_list_sha256 = {hashlib.sha256(repo_list.encode()).hexdigest()}
with repo as (
  select v, to_timestamp(v,'YYYYMMDDHH24MISS') ts
    from unnest(string_to_array('{repo_list}',',')) v
), rm as (
  select version,
         coalesce(name,'') name,
         case when name ~ '^[0-9]{{14}}_' then split_part(name,'_',1) else version end as k,
         to_timestamp(case when name ~ '^[0-9]{{14}}_' then split_part(name,'_',1) else version end,
                      'YYYYMMDDHH24MISS') ts
    from supabase_migrations.schema_migrations
), cls as (
  select rm.*,
         case
           when rm.version = any(string_to_array('{dups}',',')) then 'duplicate_record'
           when rm.version = any(string_to_array('{known}',',')) then 'known_pre_repo'
           when exists (select 1 from repo where abs(extract(epoch from rm.ts - repo.ts)) <= 60) then 'matched'
           else 'unknown_remote'
         end as class
    from rm
), repo_unmatched as (
  select repo.v
    from repo
   where not exists (select 1 from rm where abs(extract(epoch from rm.ts - repo.ts)) <= 60)
)
select jsonb_build_object(
  'rule', 'key = case when name ~ ''^[0-9]{{14}}_'' then split_part(name,''_'',1) else version end; then +-60s tolerance vs repo filename prefix',
  'remote_total', (select count(*) from rm),
  'repo_total', (select count(*) from repo),
  'matched', (select count(*) from cls where class='matched'),
  'known_pre_repo', (select coalesce(jsonb_agg(version order by version),'[]') from cls where class='known_pre_repo'),
  'duplicate_records', (select coalesce(jsonb_agg(jsonb_build_object('version',version,'name',name) order by version),'[]')
                          from cls where class='duplicate_record'),
  'unknown_remote', (select coalesce(jsonb_agg(jsonb_build_object('version',version,'name',name) order by version),'[]')
                       from cls where class='unknown_remote'),
  'repo_only', (select coalesce(jsonb_agg(v order by v),'[]') from repo_unmatched),
  'repo_only_expected_applied_not_recorded', string_to_array('{applied}',','),
  'duplicate_target_check', (select coalesce(jsonb_agg(jsonb_build_object(
        'version', version, 'maps_to', k) order by version),'[]') from cls where class='duplicate_record'),
  'known_pre_repo_proofs', jsonb_build_object(
     '20260227131741_line_binding_codes', (to_regclass('public.line_binding_codes') is not null),
     '20260308110124_trade_signals_recorded', exists (select 1 from rm where version='20260308110124'),
     '20260316122524_quantity_unit_cols', (select count(*) from information_schema.columns
        where table_schema='public' and column_name='quantity_unit'
          and table_name in ('expert_signals','trade_records')),
     '20260408065758_stock_names', (to_regclass('public.stock_names') is not null),
     '20260227155729_recorded', exists (select 1 from rm where version='20260227155729')),
  'applied_not_recorded_proof', jsonb_build_object(
     'claim_bsr_queue_jobs_has_token_slot',
     (select bool_or(prosrc like '%token_slot%') from pg_proc where proname='claim_bsr_queue_jobs'),
     'claim_bsr_queue_jobs_prosrc_md5',
     (select md5(string_agg(prosrc,'')) from pg_proc where proname='claim_bsr_queue_jobs')),
  'remote_version_list_sha256', encode(digest((select string_agg(version,',' order by version) from rm),'sha256'),'hex'),
  'repo_version_list_sha256', '{hashlib.sha256(repo_list.encode()).hexdigest()}'
) as lineage;
"""

open(OUT, "w").write(sql)
print(json.dumps({"repo_total": len(repo),
                  "repo_version_list_sha256": hashlib.sha256(repo_list.encode()).hexdigest(),
                  "sql_bytes": len(sql), "out": OUT}, indent=2))
