#!/usr/bin/env python3
"""S0-2b+ — make the backup artifact *restorable*, not just descriptive.

The first cut of the artifact captured catalog descriptions. A restore
rehearsal (S0-2c) cannot be honest against descriptions, so this generator
emits an ordered, self-contained DDL bundle that can rebuild the S1 blast
radius on an empty cluster with no access to the live catalog:

  restore/000_prereqs.sql   roles, extensions, enum types, domains, sequences
  restore/010_tables.sql    every public table (schema only — NO row data)
  restore/020_constraints.sql  PK/UK/FK/CHECK + indexes
  restore/030_functions.sql    every public function definition
  restore/040_triggers.sql     every non-internal public trigger
  restore/050_security.sql     RLS enable + policies + table/function grants
  restore/060_cron.sql         cron job configuration (redacted secrets)

Production access here is strictly read-only catalog SELECTs. No row data of
any table is exported.
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from s0_lib import OUT, cli_q, psql, psql_json, sha256_text, write_json  # noqa: E402

BK = os.path.join(OUT, "backup")
RS = os.path.join(BK, "restore")
SECRET = re.compile(r"(bearer\s+[A-Za-z0-9._\-]+|eyJ[A-Za-z0-9._\-]{20,}|(?i:(secret|token|key|password)\s*=\s*)'[^']*')", re.I)


def one(sql):
    r = psql(sql)
    return r[0][0] if r else ""


def lines(sql):
    return [v for v in psql_json(sql) if v is not None]


def main():
    os.makedirs(RS, exist_ok=True)
    files = {}

    def emit(name, header, body_lines):
        body = "-- %s\n-- generated by s0_backup_bundle.py from production catalog (read-only, schema only)\n\n" % header
        body += "\n".join(body_lines) + "\n"
        open(os.path.join(RS, name), "w").write(body)
        files[name] = {"sha256": sha256_text(body), "statements": len(body_lines)}

    # ------------------------------------------------------------ 000 prereqs
    roles = lines("select 'DO $$ BEGIN CREATE ROLE '||quote_ident(rolname)||' NOLOGIN; "
                  "EXCEPTION WHEN duplicate_object THEN NULL; END $$;' from pg_roles "
                  "where rolname in ('anon','authenticated','service_role','authenticator',"
                  "'supabase_admin','supabase_auth_admin','supabase_storage_admin','ledger_owner') order by rolname")
    exts = lines("select 'CREATE EXTENSION IF NOT EXISTS '||quote_ident(extname)||';' from pg_extension "
                 "where extname not in ('plpgsql') order by extname")
    exts = ["DO $$ BEGIN %s EXCEPTION WHEN others THEN RAISE NOTICE 'ext skipped: %%', SQLERRM; END $$;" % e
            for e in exts]
    schemas = lines("select 'CREATE SCHEMA IF NOT EXISTS '||quote_ident(nspname)||';' from pg_namespace "
                    "where nspname in ('public','extensions','app_ledger','cron','auth') order by nspname")
    enums = lines("""select 'CREATE TYPE public.'||quote_ident(t.typname)||' AS ENUM ('||
        (select string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder)
           from pg_enum e where e.enumtypid=t.oid)||');'
        from pg_type t join pg_namespace n on n.oid=t.typnamespace
        where n.nspname='public' and t.typtype='e' order by t.typname""")
    comps = lines("""select 'CREATE TYPE public.'||quote_ident(t.typname)||' AS ('||
        (select string_agg(quote_ident(a.attname)||' '||format_type(a.atttypid,a.atttypmod), ', ' order by a.attnum)
           from pg_attribute a where a.attrelid=t.typrelid and a.attnum>0 and not a.attisdropped)||');'
        from pg_type t join pg_namespace n on n.oid=t.typnamespace
        join pg_class c on c.oid=t.typrelid
        where n.nspname='public' and t.typtype='c' and c.relkind='c' order by t.typname""")
    seqs = lines("""select 'CREATE SEQUENCE IF NOT EXISTS public.'||quote_ident(c.relname)||';'
        from pg_class c join pg_namespace n on n.oid=c.relnamespace
        where n.nspname='public' and c.relkind='S' order by c.relname""")
    emit("000_prereqs.sql", "roles / schemas / extensions / types / sequences",
         ["SET check_function_bodies = off;"] + roles + schemas + exts + enums + comps + seqs)

    # ---------------------------------------------------------- 005 auth shim
    # auth.* is Supabase-managed but public objects reference auth.users and
    # auth.uid()/role()/jwt(). A restore that omits it cannot be validated, so
    # the backup captures the auth surface the public schema depends on.
    auth_tables = lines("""select 'CREATE TABLE IF NOT EXISTS auth.'||quote_ident(c.relname)||' ('||
        (select string_agg(quote_ident(a.attname)||' '||format_type(a.atttypid,a.atttypmod)||
            coalesce(' DEFAULT '||pg_get_expr(d.adbin, d.adrelid), '')||
            case when a.attnotnull then ' NOT NULL' else '' end, ', ' order by a.attnum)
         from pg_attribute a
         left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum
         where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped)||');'
        from pg_class c join pg_namespace n on n.oid=c.relnamespace
        where n.nspname='auth' and c.relkind='r' order by c.relname""")
    auth_pk = lines("""select 'ALTER TABLE auth.'||quote_ident(c.relname)||' ADD CONSTRAINT '||
        quote_ident(con.conname)||' '||pg_get_constraintdef(con.oid)||';'
        from pg_constraint con join pg_class c on c.oid=con.conrelid
        join pg_namespace n on n.oid=c.relnamespace
        where n.nspname='auth' and con.contype in ('p','u') order by c.relname, con.conname""")
    auth_fns = lines("""select pg_get_functiondef(p.oid)||';'
        from pg_proc p join pg_namespace n on n.oid=p.pronamespace
        where n.nspname='auth' order by p.proname""")
    emit("005_auth.sql", "auth schema surface referenced by public objects",
         ["CREATE SCHEMA IF NOT EXISTS auth;",
          "GRANT USAGE ON SCHEMA auth TO anon, authenticated, service_role;"]
         + auth_tables + auth_pk + auth_fns
         + ["GRANT SELECT ON ALL TABLES IN SCHEMA auth TO service_role;"])

    # ------------------------------------------------------------- 010 tables
    tables = lines("""select 'CREATE TABLE IF NOT EXISTS public.'||quote_ident(c.relname)||' ('||
        (select string_agg(quote_ident(a.attname)||' '||format_type(a.atttypid,a.atttypmod)||
            coalesce(' DEFAULT '||pg_get_expr(d.adbin,d.adrelid),'')||
            case when a.attnotnull then ' NOT NULL' else '' end, ', ' order by a.attnum)
           from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum
          where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped)||');'
        from pg_class c join pg_namespace n on n.oid=c.relnamespace
        where n.nspname='public' and c.relkind='r' order by c.relname""")
    views = lines("""select 'CREATE OR REPLACE VIEW public.'||quote_ident(c.relname)||' AS '||
        pg_get_viewdef(c.oid, true)
        from pg_class c join pg_namespace n on n.oid=c.relnamespace
        where n.nspname='public' and c.relkind='v' order by c.relname""")
    emit("010_tables.sql", "public tables (schema only, no row data) + views", tables + views)

    # -------------------------------------------------- 020 constraints / indexes
    pk_uk_ck = lines("""select 'ALTER TABLE public.'||quote_ident(c.relname)||' ADD CONSTRAINT '||
        quote_ident(con.conname)||' '||pg_get_constraintdef(con.oid)||';'
        from pg_constraint con join pg_class c on c.oid=con.conrelid
        join pg_namespace n on n.oid=c.relnamespace
        where n.nspname='public' and con.contype in ('p','u','c') order by c.relname, con.conname""")
    fks = lines("""select 'ALTER TABLE public.'||quote_ident(c.relname)||' ADD CONSTRAINT '||
        quote_ident(con.conname)||' '||pg_get_constraintdef(con.oid)||';'
        from pg_constraint con join pg_class c on c.oid=con.conrelid
        join pg_namespace n on n.oid=c.relnamespace
        where n.nspname='public' and con.contype='f' order by c.relname, con.conname""")
    idx = lines("""select indexdef||';' from pg_indexes where schemaname='public'
        and indexname not in (select con.conname from pg_constraint con join pg_class c on c.oid=con.conrelid
        join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and con.contype in ('p','u'))
        order by indexname""")
    emit("020_constraints.sql", "primary/unique/check constraints, foreign keys, indexes",
         ["-- constraints are wrapped so a partially restorable object cannot abort the whole rehearsal"] +
         ["DO $$ BEGIN %s EXCEPTION WHEN others THEN RAISE NOTICE 'skip: %%', SQLERRM; END $$;" % s
          for s in pk_uk_ck + fks + idx])

    # ---------------------------------------------------------- 030 functions
    fndefs = lines("""select pg_get_functiondef(p.oid) from pg_proc p
        join pg_namespace n on n.oid=p.pronamespace
        where n.nspname='public' and p.prokind in ('f','p') order by p.proname,
        pg_get_function_identity_arguments(p.oid)""")
    emit("030_functions.sql", "all public function definitions",
         ["SET check_function_bodies = off;"] +
         ["DO $__r$ BEGIN EXECUTE $__f$%s$__f$; EXCEPTION WHEN others THEN "
          "RAISE NOTICE 'fn skipped: %%', SQLERRM; END $__r$;" % d.replace("\\n", "\n") for d in fndefs])

    # ----------------------------------------------------------- 040 triggers
    trgs = lines("""select pg_get_triggerdef(t.oid)||';' from pg_trigger t
        join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace
        where n.nspname='public' and not t.tgisinternal order by c.relname, t.tgname""")
    emit("040_triggers.sql", "all non-internal public triggers",
         ["DO $$ BEGIN %s EXCEPTION WHEN others THEN RAISE NOTICE 'trg skipped: %%', SQLERRM; END $$;" % s
          for s in trgs])

    # ----------------------------------------------------------- 050 security
    rls = lines("""select 'ALTER TABLE public.'||quote_ident(relname)||' ENABLE ROW LEVEL SECURITY;'
        from pg_class c join pg_namespace n on n.oid=c.relnamespace
        where n.nspname='public' and c.relkind='r' and c.relrowsecurity order by relname""")
    pols = lines("""select 'CREATE POLICY '||quote_ident(policyname)||' ON public.'||quote_ident(tablename)||
        ' AS '||permissive||' FOR '||cmd||' TO '||array_to_string(roles,', ')||
        coalesce(' USING ('||qual||')','')||coalesce(' WITH CHECK ('||with_check||')','')||';'
        from pg_policies where schemaname='public' order by tablename, policyname""")
    tgrants = lines("""select 'GRANT '||a.privilege_type||' ON public.'||quote_ident(c.relname)||
        ' TO '||quote_ident(coalesce(r.rolname,'PUBLIC'))||';'
        from pg_class c join pg_namespace n on n.oid=c.relnamespace
        cross join lateral aclexplode(coalesce(c.relacl,'{}')) a
        left join pg_roles r on r.oid=a.grantee
        where n.nspname='public' and c.relkind in ('r','v')
          and coalesce(r.rolname,'PUBLIC') in ('anon','authenticated','service_role','postgres','ledger_owner')
        order by c.relname, coalesce(r.rolname,'PUBLIC'), a.privilege_type""")
    # CREATE FUNCTION implicitly grants EXECUTE to PUBLIC. Production has that
    # grant revoked on every function that carries an explicit ACL, so the
    # backup must reproduce the revoke or a restore silently re-opens them.
    frevokes = lines("""select 'REVOKE ALL ON FUNCTION public.'||quote_ident(p.proname)||'('||
        pg_get_function_identity_arguments(p.oid)||') FROM PUBLIC;'
        from pg_proc p join pg_namespace n on n.oid=p.pronamespace
        where n.nspname='public' and p.proacl is not null
          and not exists (select 1 from aclexplode(p.proacl) a where a.grantee = 0)
        order by p.proname, pg_get_function_identity_arguments(p.oid)""")
    frevokes = ["DO $$ BEGIN %s EXCEPTION WHEN others THEN NULL; END $$;" % r for r in frevokes]
    fgrants = lines("""select 'GRANT EXECUTE ON FUNCTION public.'||p.proname||'('||
        pg_get_function_identity_arguments(p.oid)||') TO '||quote_ident(g.grantee)||';'
        from pg_proc p join pg_namespace n on n.oid=p.pronamespace
        cross join lateral aclexplode(coalesce(p.proacl,'{}')) a
        join lateral (select coalesce(r.rolname,'PUBLIC') as grantee from pg_roles r
                      where r.oid=a.grantee union all select 'PUBLIC' where a.grantee=0) g on true
        where n.nspname='public' and a.privilege_type='EXECUTE' and g.grantee<>'PUBLIC'
        order by p.proname, g.grantee""")
    emit("050_security.sql", "RLS + policies + table grants + function EXECUTE grants",
         ["DO $$ BEGIN %s EXCEPTION WHEN others THEN RAISE NOTICE 'sec skipped: %%', SQLERRM; END $$;" % s
          for s in rls + pols + tgrants + frevokes + fgrants])

    # --------------------------------------------------------------- 060 cron
    jobs = cli_q("select jobid, jobname, schedule, active, username, command from cron.job order by jobid")
    redacted = 0
    for j in jobs:
        c = j.get("command") or ""
        if SECRET.search(c):
            j["command"] = SECRET.sub("<REDACTED>", c)
            j["redacted"] = True
            redacted += 1
        j["command_sha256"] = sha256_text(c)
    body = ["-- cron configuration is restored as data, not as scheduled jobs:",
            "-- a rehearsal clone must never dispatch real jobs.",
            "CREATE SCHEMA IF NOT EXISTS cron_backup;",
            "CREATE TABLE IF NOT EXISTS cron_backup.job (jobid bigint primary key, jobname text, "
            "schedule text, active boolean, username text, command text, command_sha256 text);",
            "TRUNCATE cron_backup.job;"]
    for j in jobs:
        body.append("INSERT INTO cron_backup.job VALUES (%d, %s, %s, %s, %s, %s, %s);" % (
            j["jobid"],
            "'" + (j["jobname"] or "").replace("'", "''") + "'",
            "'" + (j["schedule"] or "").replace("'", "''") + "'",
            "true" if j["active"] else "false",
            "'" + (j["username"] or "").replace("'", "''") + "'",
            "$cmd$" + (j["command"] or "") + "$cmd$",
            "'" + j["command_sha256"] + "'"))
    emit("060_cron.sql", "cron job configuration (%d jobs, %d redacted)" % (len(jobs), redacted), body)

    # ------------------------------------------------------------- manifest++
    mpath = os.path.join(BK, "MANIFEST.json")
    man = json.load(open(mpath))
    man["restore_bundle"] = {
        "order": ["000_prereqs.sql", "005_auth.sql", "010_tables.sql", "020_constraints.sql", "030_functions.sql",
                  "040_triggers.sql", "050_security.sql", "060_cron.sql"],
        "files": files,
        "row_data_included": False,
        "cron_commands_redacted": redacted,
        "counts": {"tables": len(tables), "views": len(views), "functions": len(fndefs),
                   "triggers": len(trgs), "policies": len(pols), "enums": len(enums),
                   "sequences": len(seqs), "cron_jobs": len(jobs),
                   "table_grants": len(tgrants), "function_grants": len(fgrants)},
    }
    man.pop("manifest_sha256", None)
    man["manifest_sha256"] = sha256_text(json.dumps(man, sort_keys=True))
    write_json(mpath, man)
    print(json.dumps(man["restore_bundle"]["counts"], indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
