// @ts-check
import {
  composeAppRuntimeCoreLifecycleArgs,
  composeAppRuntimeWorkflowsArgs,
} from './useAppRuntimeComposer.js'
import { assertNoStoreSetters } from './runtimeArgs.types.js'

export function useAppRuntimeCoreArgs({ state, setters, ui, runtime, refs, helpers }) {
  return {
    ...composeAppRuntimeCoreLifecycleArgs({
      data: {
        ready: state.ready,
        holdings: state.holdings,
        watchlist: state.watchlist,
        newsEvents: state.newsEvents,
        tradeLog: state.tradeLog,
        targets: state.targets,
        fundamentals: state.fundamentals,
        analystReports: state.analystReports,
        reportRefreshMeta: state.reportRefreshMeta,
        holdingDossiers: state.holdingDossiers,
        analysisHistory: state.analysisHistory,
        dailyReport: state.dailyReport,
        reversalConditions: state.reversalConditions,
        strategyBrain: state.strategyBrain,
        brainValidation: state.brainValidation,
        researchHistory: state.researchHistory,
        portfolioNotes: state.portfolioNotes,
        tab: ui.tab,
      },
      setters: assertNoStoreSetters({
        // Phase 3A.4 Step 2/3: store-backed setters 已從 hook 內部直接走 store，
        // 不需從 args 傳入。assertNoStoreSetters 會在 TS 層阻擋任何
        // setHoldings/setTradeLog/... 等已遷移到 store 的 setter 被傳入。
        setReady: setters.setReady,
        setCloudSync: setters.setCloudSync,
        setPortfolioNotes: setters.setPortfolioNotes,
      }),
      ui: {
        resetTransientUiState: ui.resetTransientUiState,
        setReviewingEvent: ui.setReviewingEvent,
        setReviewForm: ui.setReviewForm,
      },
      runtime: {
        flashSaved: runtime.flashSaved,
        requestAppConfirmation: runtime.requestAppConfirmation,
      },
      helpers,
    }),
    activePortfolioIdRef: refs.activePortfolioIdRef,
    viewModeRef: refs.viewModeRef,
    portfoliosRef: refs.portfoliosRef,
    portfolioSetterRef: refs.portfolioSetterRef,
    bootRuntimeRef: refs.bootRuntimeRef,
    cloudSyncStateRef: refs.cloudSyncStateRef,
    cloudSaveTimersRef: refs.cloudSaveTimersRef,
  }
}

export function useAppRuntimeWorkflowArgs({
  state,
  derived,
  ui,
  asyncState,
  actions,
  setters,
  resources,
  runtime,
  refs,
  helpers,
}) {
  return {
    ...composeAppRuntimeWorkflowsArgs({
      data: {
        ready: state.ready,
        viewMode: state.viewMode,
        portfolioViewMode: state.portfolioViewMode,
        tab: ui.tab,
        activePortfolioId: state.activePortfolioId,
        canUseCloud: state.canUseCloud,
        todayMarketClock: derived.todayMarketClock,
        shouldTriggerPostCloseSelfHeal: derived.shouldTriggerPostCloseSelfHeal,
        holdings: state.holdings,
        tradeLog: state.tradeLog,
        marketPriceCache: state.marketPriceCache,
        losers: derived.losers,
        newsEvents: state.newsEvents,
        analysisHistory: state.analysisHistory,
        strategyBrain: state.strategyBrain,
        portfolioNotes: state.portfolioNotes,
        reversalConditions: state.reversalConditions,
        reportRefreshMeta: state.reportRefreshMeta,
        todayRefreshKey: derived.todayRefreshKey,
        dossierByCode: derived.dossierByCode,
        H: derived.H,
        W: derived.W,
        totalCost: derived.totalCost,
        totalVal: derived.totalVal,
        totalPnl: derived.totalPnl,
        retPct: derived.retPct,
        overviewPortfolios: derived.overviewPortfolios,
        overviewTotalValue: derived.overviewTotalValue,
        overviewTotalPnl: derived.overviewTotalPnl,
        overviewDuplicateHoldings: derived.overviewDuplicateHoldings,
        overviewPendingItems: derived.overviewPendingItems,
        winners: derived.winners,
        top5: derived.top5,
        holdingsIntegrityIssues: derived.holdingsIntegrityIssues,
        attentionCount: derived.attentionCount,
        pendingCount: derived.pendingCount,
        targetUpdateCount: derived.targetUpdateCount,
        dataRefreshRows: derived.dataRefreshRows,
        researchHistory: state.researchHistory,
        reportRefreshCandidates: derived.reportRefreshCandidates,
        analystReports: state.analystReports,
        portfolios: state.portfolios,
        morningNote: state.morningNote,
        dailyReport: state.dailyReport,
        reviewingEvent: ui.reviewingEvent,
      },
      ui: {
        filterType: ui.filterType,
        catalystFilter: ui.catalystFilter,
        scanQuery: ui.scanQuery,
        scanFilter: ui.scanFilter,
        sortBy: ui.sortBy,
        showReversal: ui.showReversal,
        expandedStock: ui.expandedStock,
        watchlistFocus: derived.watchlistFocus,
        watchlistRows: derived.watchlistRows,
        showRelayPlan: derived.showRelayPlan,
        relayPlanExpanded: ui.relayPlanExpanded,
        dailyExpanded: ui.dailyExpanded,
        researchTarget: ui.researchTarget,
        reviewForm: ui.reviewForm,
        expandedNews: ui.expandedNews,
      },
      asyncState: {
        analyzing: asyncState.analyzing,
        setAnalyzing: asyncState.setAnalyzing,
        analyzeStep: asyncState.analyzeStep,
        setAnalyzeStep: asyncState.setAnalyzeStep,
        researching: asyncState.researching,
        setResearching: asyncState.setResearching,
      },
      actions: {
        upsertTargetReport: actions.upsertTargetReport,
        upsertFundamentalsEntry: actions.upsertFundamentalsEntry,
        updateReversal: actions.updateReversal,
        updateTargetPrice: actions.updateTargetPrice,
        updateAlert: actions.updateAlert,
        handleWatchlistUpsert: actions.handleWatchlistUpsert,
        handleWatchlistDelete: actions.handleWatchlistDelete,
        cancelReview: actions.cancelReview,
        switchPortfolio: actions.switchPortfolio,
        exitOverview: actions.exitOverview,
      },
      setters: {
        // Phase 3A.4 Step 2: store-backed setters 已從 hook 內部直接走 store，
        // 不需從 args 傳入。保留 UI state、portfolio orchestration、cloud sync 等非 store setter。
        setResearchTarget: setters.setResearchTarget,
        setResearchResults: setters.setResearchResults,
        setReviewForm: setters.setReviewForm,
        setReviewingEvent: setters.setReviewingEvent,
        setLastUpdate: setters.setLastUpdate,
        setPortfolios: setters.setPortfolios,
        setActivePortfolioId: setters.setActivePortfolioId,
        setViewMode: setters.setViewMode,
        setCloudSync: setters.setCloudSync,
        setShowReversal: setters.setShowReversal,
        setScanQuery: setters.setScanQuery,
        setScanFilter: setters.setScanFilter,
        setSortBy: setters.setSortBy,
        setExpandedStock: setters.setExpandedStock,
        setRelayPlanExpanded: setters.setRelayPlanExpanded,
        setFilterType: setters.setFilterType,
        setCatalystFilter: setters.setCatalystFilter,
        setDailyExpanded: setters.setDailyExpanded,
        setTab: setters.setTab,
        setExpandedNews: setters.setExpandedNews,
      },
      resources: {
        defaultNewsEvents: resources.defaultNewsEvents,
        researchResults: resources.researchResults,
        stockMeta: resources.stockMeta,
        indColor: resources.indColor,
      },
      runtime: {
        flashSaved: runtime.flashSaved,
        requestAppConfirmation: runtime.requestAppConfirmation,
      },
      helpers,
    }),
    priceSelfHealRef: refs.priceSelfHealRef,
    syncPostClosePrices: refs.syncPostClosePrices,
    refreshAnalystReportsRef: refs.refreshAnalystReportsRef,
    resetTradeCaptureRef: refs.resetTradeCaptureRef,
    applyPortfolioSnapshot: refs.applyPortfolioSnapshot,
    portfolioTransitionRef: refs.portfolioTransitionRef,
    cloudSyncStateRef: refs.cloudSyncStateRef,
    livePortfolioSnapshot: refs.livePortfolioSnapshot,
  }
}
