// @ts-check
import { OWNER_PORTFOLIO_ID, PORTFOLIO_VIEW_MODE } from '../constants.js'
import { usePortfolioManagement } from './usePortfolioManagement.js'
import { usePortfolioBootstrap } from './usePortfolioBootstrap.js'
import { usePortfolioPersistence } from './usePortfolioPersistence.js'
import { usePortfolioDossierActions } from './usePortfolioDossierActions.js'
import { useWatchlistActions } from './useWatchlistActions.js'
import { useTransientUiActions } from './useTransientUiActions.js'
import { useAppRuntimeSyncRefs } from './useAppRuntimeSyncRefs.js'
import {
  useAppBootRuntimeComposer,
  useAppLifecycleRuntimeComposer,
  usePortfolioManagementComposer,
} from './useAppRuntimeComposer.js'
import { usePortfolioSnapshotRuntime } from './usePortfolioSnapshotRuntime.js'
import { useEventLifecycleSync } from './useEventLifecycleSync.js'
import { useMarketData } from './useMarketData.js'

export function useAppRuntimeCoreLifecycle({
  ready,
  holdings,
  watchlist,
  newsEvents,
  tradeLog,
  targets,
  fundamentals,
  analystReports,
  reportRefreshMeta,
  holdingDossiers,
  analysisHistory,
  dailyReport,
  reversalConditions,
  strategyBrain,
  brainValidation,
  researchHistory,
  portfolioNotes,
  tab,
  activePortfolioIdRef,
  viewModeRef,
  portfoliosRef,
  portfolioSetterRef,
  bootRuntimeRef,
  cloudSyncStateRef,
  cloudSaveTimersRef,
  resetTransientUiState,
  setReady,
  setCloudSync,
  setPortfolioNotes,
  setReviewingEvent,
  setReviewForm,
  flashSaved,
  requestAppConfirmation,
  helpers,
}) {
  const {
    createDefaultReviewForm,
    migrateLegacyPortfolioStorageIfNeeded,
    seedJinlianchengIfNeeded,
    ensurePortfolioRegistry,
    applyTradeBackfillPatchesIfNeeded,
    loadPortfolioSnapshot,
    readSyncAt,
    writeSyncAt,
    shouldAdoptCloudHoldings,
    normalizeHoldings,
    buildHoldingPriceHints,
    getPortfolioFallback,
    savePortfolioData,
    buildHoldingDossiers,
    applyMarketQuotesToHoldings,
    normalizeHoldingDossiers,
    normalizeAnalysisHistoryEntries,
    normalizeStrategyBrain,
    normalizeNewsEvents,
    normalizeDailyReportEntry,
    normalizeBrainValidationStore,
    normalizeFundamentalsStore,
    normalizeWatchlist,
    normalizeAnalystReportsStore,
    normalizeReportRefreshMeta,
    clonePortfolioNotes,
    save,
    toSlashDate,
    getEventStockCodes,
    parseSlashDate,
    appendPriceHistory,
  } = helpers

  const { marketDataArgs, portfolioSnapshotArgs } = useAppBootRuntimeComposer({
    holdings,
    watchlist,
    newsEvents,
    portfoliosRef,
    activePortfolioIdRef,
    viewModeRef,
    flashSaved,
    requestAppConfirmation,
    ready,
    marketPriceCache: null,
    cloudSyncStateRef,
    portfolioSetterRef,
    setCloudSync,
    tradeLog,
    targets,
    fundamentals,
    analystReports,
    reportRefreshMeta,
    holdingDossiers,
    analysisHistory,
    dailyReport,
    reversalConditions,
    strategyBrain,
    researchHistory,
    portfolioNotes,
    setPortfolioNotes,
    normalizeAnalysisHistoryEntries,
    applyMarketQuotesToHoldings,
    normalizeFundamentalsStore,
    normalizeWatchlist,
    normalizeAnalystReportsStore,
    normalizeReportRefreshMeta,
    normalizeHoldingDossiers,
    normalizeNewsEvents,
    normalizeStrategyBrain,
    normalizeBrainValidationStore,
    normalizeDailyReportEntry,
    clonePortfolioNotes,
    loadPortfolioSnapshot,
    readSyncAt,
    save,
    savePortfolioData,
  })

  const {
    marketPriceCache,
    marketPriceSync,
    lastUpdate,
    setLastUpdate,
    refreshing,
    priceSyncStatusLabel,
    priceSyncStatusTone,
    activePriceSyncAt,
    refreshPrices,
    syncPostClosePrices,
    getMarketQuotesForCodes,
    priceSelfHealRef,
  } = useMarketData(marketDataArgs)

  const { applyPortfolioSnapshot, flushCurrentPortfolio, livePortfolioSnapshot, loadPortfolio } =
    usePortfolioSnapshotRuntime({
      ...portfolioSnapshotArgs,
      marketPriceCache,
    })

  const portfolioManagementArgs = usePortfolioManagementComposer({
    ready,
    ownerPortfolioId: OWNER_PORTFOLIO_ID,
    portfolioViewMode: PORTFOLIO_VIEW_MODE,
    holdings,
    newsEvents,
    portfolioNotes,
    marketPriceCache,
    flushCurrentPortfolio,
    resetTransientUiState,
    loadPortfolio,
    flashSaved,
  })

  const {
    portfolios,
    setPortfolios,
    activePortfolioId,
    setActivePortfolioId,
    viewMode,
    setViewMode,
    portfolioSwitching,
    showPortfolioManager,
    setShowPortfolioManager,
    portfolioTransitionRef,
    portfolioSummaries,
    createPortfolio,
    renamePortfolio,
    deletePortfolio,
    portfolioEditor,
    portfolioDeleteDialog,
    switchPortfolio,
    openOverview,
    exitOverview,
  } = usePortfolioManagement(portfolioManagementArgs)

  const {
    canUseCloud,
    runtimeSyncRefsArgs,
    portfolioBootstrapArgs,
    portfolioPersistenceArgs,
    dossierActionArgs,
    watchlistActionsArgs,
    transientUiArgs,
    eventLifecycleArgs,
  } = useAppLifecycleRuntimeComposer({
    ready,
    ownerPortfolioId: OWNER_PORTFOLIO_ID,
    portfolioViewMode: PORTFOLIO_VIEW_MODE,
    holdings,
    newsEvents,
    portfolioNotes,
    marketPriceCache,
    flashSaved,
    activePortfolioId,
    viewMode,
    portfolios,
    setPortfolios,
    setActivePortfolioId,
    setViewMode,
    portfolioSwitching,
    tradeLog,
    targets,
    fundamentals,
    watchlist,
    analystReports,
    reportRefreshMeta,
    holdingDossiers,
    analysisHistory,
    dailyReport,
    reversalConditions,
    strategyBrain,
    brainValidation,
    researchHistory,
    marketPriceSync,
    tab,
    cloudSyncStateRef,
    cloudSaveTimersRef,
    activePortfolioIdRef,
    viewModeRef,
    portfoliosRef,
    portfolioSetterRef,
    bootRuntimeRef,
    applyPortfolioSnapshot,
    portfolioTransitionRef,
    getMarketQuotesForCodes,
    normalizeHoldings,
    savePortfolioData,
    buildHoldingDossiers,
    applyMarketQuotesToHoldings,
    normalizeHoldingDossiers,
    normalizeAnalysisHistoryEntries,
    readSyncAt,
    writeSyncAt,
    setReady,
    setCloudSync,
    setReviewingEvent,
    setReviewForm,
    createDefaultReviewForm,
    migrateLegacyPortfolioStorageIfNeeded,
    seedJinlianchengIfNeeded,
    ensurePortfolioRegistry,
    applyTradeBackfillPatchesIfNeeded,
    loadPortfolioSnapshot,
    shouldAdoptCloudHoldings,
    buildHoldingPriceHints,
    getPortfolioFallback,
    normalizeStrategyBrain,
    normalizeNewsEvents,
    normalizeDailyReportEntry,
    toSlashDate,
    getEventStockCodes,
    parseSlashDate,
    appendPriceHistory,
  })

  useAppRuntimeSyncRefs(runtimeSyncRefsArgs)
  usePortfolioBootstrap(portfolioBootstrapArgs)
  usePortfolioPersistence(portfolioPersistenceArgs)

  const { updateTargetPrice, updateAlert, upsertTargetReport, upsertFundamentalsEntry } =
    usePortfolioDossierActions(dossierActionArgs)
  const { upsertWatchlist: handleWatchlistUpsert, removeWatchlist: handleWatchlistDelete } =
    useWatchlistActions()
  void watchlistActionsArgs
  const { updateReversal, cancelReview } = useTransientUiActions(transientUiArgs)
  useEventLifecycleSync(eventLifecycleArgs)

  return {
    marketPriceCache,
    marketPriceSync,
    lastUpdate,
    setLastUpdate,
    refreshing,
    priceSyncStatusLabel,
    priceSyncStatusTone,
    activePriceSyncAt,
    refreshPrices,
    syncPostClosePrices,
    getMarketQuotesForCodes,
    priceSelfHealRef,
    applyPortfolioSnapshot,
    livePortfolioSnapshot,
    portfolios,
    setPortfolios,
    activePortfolioId,
    setActivePortfolioId,
    viewMode,
    setViewMode,
    portfolioSwitching,
    showPortfolioManager,
    setShowPortfolioManager,
    portfolioTransitionRef,
    portfolioSummaries,
    createPortfolio,
    renamePortfolio,
    deletePortfolio,
    portfolioEditor,
    portfolioDeleteDialog,
    switchPortfolio,
    openOverview,
    exitOverview,
    canUseCloud,
    updateTargetPrice,
    updateAlert,
    upsertTargetReport,
    upsertFundamentalsEntry,
    handleWatchlistUpsert,
    handleWatchlistDelete,
    updateReversal,
    cancelReview,
  }
}
