// @ts-check
import { useState } from 'react'
import { APP_LABELS } from '../lib/appMessages.js'
import { filterEventsByType, resolveRuntimeNewsEvents } from '../lib/appShellRuntime.js'
import { useReportRefreshWorkflow } from './useReportRefreshWorkflow.js'
import { useDailyAnalysisWorkflow } from './useDailyAnalysisWorkflow.js'
import { useStressTestWorkflow } from './useStressTestWorkflow.js'
import { useEventReviewWorkflow } from './useEventReviewWorkflow.js'
import { useWeeklyReportClipboard } from './useWeeklyReportClipboard.js'
import { useTradeCaptureRuntime } from './useTradeCaptureRuntime.js'
import { useResearchWorkflow } from './useResearchWorkflow.js'
import { useLocalBackupWorkflow } from './useLocalBackupWorkflow.js'
import { usePortfolioPanelsContextComposer } from './usePortfolioPanelsContextComposer.js'
import { useAppCallbackRefs } from './useAppCallbackRefs.js'
import { usePostCloseSelfHealSync } from './usePostCloseSelfHealSync.js'
import { useResearchAutoRefresh } from './useResearchAutoRefresh.js'
import { brainRuleSummary, mergeBrainPreservingCoachLessons } from '../lib/brainRuntime.js'
import {
  composeReportRefreshWorkflowArgs,
  composeDailyAnalysisWorkflowArgs,
  composeStressTestWorkflowArgs,
  composeEventReviewWorkflowArgs,
  composeWeeklyReportClipboardArgs,
  composeTradeCaptureRuntimeArgs,
  composeResearchWorkflowArgs,
  composeLocalBackupWorkflowArgs,
  composePortfolioPanelsContextInput,
} from './useAppRuntimeComposer.js'

export function useAppRuntimeWorkflows({
  ready,
  viewMode,
  portfolioViewMode,
  tab,
  activePortfolioId,
  canUseCloud,
  todayMarketClock,
  shouldTriggerPostCloseSelfHeal,
  priceSelfHealRef,
  syncPostClosePrices,
  refreshAnalystReportsRef,
  resetTradeCaptureRef,
  filterType,
  catalystFilter,
  holdings,
  tradeLog,
  marketPriceCache,
  losers,
  newsEvents,
  defaultNewsEvents,
  analysisHistory,
  strategyBrain,
  portfolioNotes,
  reversalConditions,
  reportRefreshMeta,
  todayRefreshKey,
  dossierByCode,
  H,
  W,
  totalCost,
  totalVal,
  totalPnl,
  retPct,
  overviewPortfolios,
  overviewTotalValue,
  overviewTotalPnl,
  overviewDuplicateHoldings,
  overviewPendingItems,
  winners,
  top5,
  holdingsIntegrityIssues,
  attentionCount,
  pendingCount,
  targetUpdateCount,
  scanQuery,
  scanFilter,
  sortBy,
  showReversal,
  expandedStock,
  watchlistFocus,
  watchlistRows,
  showRelayPlan,
  relayPlanExpanded,
  morningNote,
  dailyReport,
  analyzing,
  setAnalyzing,
  analyzeStep,
  setAnalyzeStep,
  dailyExpanded,
  researching,
  setResearching,
  researchTarget,
  setResearchTarget,
  dataRefreshRows,
  researchResults,
  setResearchResults,
  researchHistory,
  reviewForm,
  setReviewForm,
  reviewingEvent,
  setReviewingEvent,
  expandedNews,
  stockMeta,
  indColor,
  reportRefreshCandidates,
  analystReports,
  upsertTargetReport,
  upsertFundamentalsEntry,
  portfolios,
  setLastUpdate,
  setPortfolios,
  setActivePortfolioId,
  setViewMode,
  setCloudSync,
  requestAppConfirmation,
  applyPortfolioSnapshot,
  portfolioTransitionRef,
  cloudSyncStateRef,
  livePortfolioSnapshot,
  exitOverview,
  switchPortfolio,
  setShowReversal,
  updateReversal,
  setScanQuery,
  setScanFilter,
  setSortBy,
  setExpandedStock,
  updateTargetPrice,
  updateAlert,
  handleWatchlistUpsert,
  handleWatchlistDelete,
  cancelReview,
  setRelayPlanExpanded,
  setFilterType,
  setCatalystFilter,
  setDailyExpanded,
  setTab,
  setExpandedNews,
  flashSaved,
  helpers,
}) {
  const {
    formatEventStockOutcomeLine,
    isClosedEvent,
    resolveHoldingPrice,
    getHoldingUnrealizedPnl,
    getHoldingReturnPct,
    getMarketQuotesForCodes,
    buildDailyHoldingDossierContext,
    formatPortfolioNotesContext,
    formatBrainChecklistsForPrompt,
    formatBrainRulesForValidationPrompt,
    normalizeStrategyBrain,
    createEmptyBrainAudit,
    ensureBrainAuditCoverage,
    enforceTaiwanHardGatesOnBrainAudit,
    mergeBrainWithAuditLifecycle,
    appendBrainValidationCases,
    normalizeHoldings,
    applyTradeEntryToHoldings,
    createDefaultFundamentalDraft,
    toSlashDate,
    createDefaultReviewForm,
  } = helpers

  const {
    reportRefreshing,
    reportRefreshStatus,
    enrichingResearchCode,
    refreshAnalystReports,
    enrichResearchToDossier,
  } = useReportRefreshWorkflow(
    composeReportRefreshWorkflowArgs({
      holdings: H,
      dossierByCode,
      analystReports,
      reportRefreshMeta,
      reportRefreshCandidates,
      todayRefreshKey,
      upsertTargetReport,
      upsertFundamentalsEntry,
      flashSaved,
      toSlashDate,
    })
  )

  usePostCloseSelfHealSync({
    ready,
    viewMode,
    portfolioViewMode,
    shouldTriggerPostCloseSelfHeal,
    activePortfolioId,
    todayMarketClock,
    priceSelfHealRef,
    syncPostClosePrices,
  })

  useResearchAutoRefresh({
    ready,
    viewMode,
    portfolioViewMode,
    tab,
    reportRefreshing,
    reportRefreshMeta,
    todayRefreshKey,
    reportRefreshCandidates,
    refreshAnalystReportsRef,
  })

  const resolvedNewsEvents = resolveRuntimeNewsEvents(newsEvents, defaultNewsEvents)
  const filteredEvents = filterEventsByType({
    newsEvents,
    fallbackEvents: defaultNewsEvents,
    filterType,
    allFilterLabel: APP_LABELS.allFilter,
  }).filter((event) => catalystFilter === '全部' || event.catalystType === catalystFilter)

  const { runDailyAnalysis } = useDailyAnalysisWorkflow({
    ...composeDailyAnalysisWorkflowArgs({
      analyzing,
      setAnalyzing,
      setAnalyzeStep,
      holdings: H,
      losers,
      newsEvents,
      defaultNewsEvents,
      analysisHistory,
      strategyBrain,
      portfolioNotes,
      reversalConditions,
      reportRefreshMeta,
      todayRefreshKey,
      dossierByCode,
      activePortfolioId,
      canUseCloud,
      getMarketQuotesForCodes,
      resolveHoldingPrice,
      getHoldingUnrealizedPnl,
      getHoldingReturnPct,
      buildDailyHoldingDossierContext,
      formatPortfolioNotesContext,
      formatBrainChecklistsForPrompt,
      formatBrainRulesForValidationPrompt,
      normalizeStrategyBrain,
      createEmptyBrainAudit,
      ensureBrainAuditCoverage,
      enforceTaiwanHardGatesOnBrainAudit,
      mergeBrainWithAuditLifecycle,
      appendBrainValidationCases,
      normalizeHoldings,
      isClosedEvent,
      toSlashDate,
      setLastUpdate,
      flashSaved,
    }),
    refreshAnalystReportsRef,
  })

  const [stressTesting, setStressTesting] = useState(false)
  const [stressResult, setStressResult] = useState(null)

  const { runStressTest } = useStressTestWorkflow(
    composeStressTestWorkflowArgs({
      stressTesting,
      analyzing,
      setStressTesting,
      setAnalyzeStep,
      holdings: H,
      dossierByCode,
      getMarketQuotesForCodes,
      resolveHoldingPrice,
      getHoldingUnrealizedPnl,
      getHoldingReturnPct,
      buildDailyHoldingDossierContext,
      toSlashDate,
      setStressResult,
    })
  )

  const { submitReview } = useEventReviewWorkflow(
    composeEventReviewWorkflowArgs({
      newsEvents,
      defaultNewsEvents,
      reviewForm,
      setReviewingEvent,
      setReviewForm,
      flashSaved,
      activePortfolioId,
      portfolios,
      strategyBrain,
      portfolioNotes,
      dossierByCode,
      toSlashDate,
    })
  )

  const { copyWeeklyReport } = useWeeklyReportClipboard(
    composeWeeklyReportClipboardArgs({
      holdings: H,
      watchlist: W,
      analysisHistory,
      newsEvents: resolvedNewsEvents,
      strategyBrain,
      totalCost,
      totalVal,
      totalPnl,
      retPct,
      isClosedEvent,
      resolveHoldingPrice,
      getHoldingUnrealizedPnl,
      getHoldingReturnPct,
      brainRuleSummary,
      flashSaved,
    })
  )

  const tradeCapture = useTradeCaptureRuntime(
    composeTradeCaptureRuntimeArgs({
      holdings,
      tradeLog,
      marketQuotes: marketPriceCache?.prices,
      upsertTargetReport,
      upsertFundamentalsEntry,
      applyTradeEntryToHoldings,
      createDefaultFundamentalDraft,
      toSlashDate,
      flashSaved,
      setTab,
    })
  )

  useAppCallbackRefs({
    refreshAnalystReportsRef,
    refreshAnalystReports,
    resetTradeCaptureRef,
    resetTradeCapture: tradeCapture.resetTradeCapture,
  })

  const { runResearch } = useResearchWorkflow(
    composeResearchWorkflowArgs({
      researching,
      setResearching,
      setResearchTarget,
      holdings: H,
      dossierByCode,
      stockMeta,
      strategyBrain,
      portfolioNotes,
      canUseCloud,
      newsEvents,
      analysisHistory,
      resolveHoldingPrice,
      getHoldingUnrealizedPnl,
      getHoldingReturnPct,
      setResearchResults,
      flashSaved,
      enrichResearchToDossier,
      mergeBrainPreservingCoachLessons,
    })
  )

  const { backupFileInputRef, exportLocalBackup, importLocalBackup } = useLocalBackupWorkflow({
    ...composeLocalBackupWorkflowArgs({
      portfolios,
      activePortfolioId,
      viewMode,
      marketQuotes: marketPriceCache?.prices,
      requestAppConfirmation,
      applyPortfolioSnapshot,
      setPortfolios,
      setActivePortfolioId,
      setViewMode,
      setCloudSync,
      flashSaved,
    }),
    portfolioTransitionRef,
    cloudSyncStateRef,
    liveSnapshot: livePortfolioSnapshot,
  })

  const { portfolioPanelsData, portfolioPanelsActions } = usePortfolioPanelsContextComposer(
    composePortfolioPanelsContextInput({
      data: {
        activePortfolioId,
        overviewPortfolios,
        overviewTotalValue,
        overviewTotalPnl,
        overviewDuplicateHoldings,
        overviewPendingItems,
        holdings,
        totalVal,
        totalCost,
        winners,
        losers,
        top5,
        holdingsIntegrityIssues,
        filteredEvents,
        morningNote,
        dailyReport,
        newsEvents,
        strategyBrain,
        dataRefreshRows,
        researchHistory,
        tradeLog,
      },
      ui: {
        showReversal,
        reversalConditions,
        reviewingEvent,
        attentionCount,
        pendingCount,
        targetUpdateCount,
        scanQuery,
        scanFilter,
        sortBy,
        expandedStock,
        watchlistFocus,
        watchlistRows,
        showRelayPlan,
        relayPlanExpanded,
        filterType,
        catalystFilter,
        dailyExpanded,
        researchTarget,
        reviewForm,
        expandedNews,
      },
      asyncState: {
        analyzing,
        analyzeStep,
        stressResult,
        stressTesting,
        researching,
        reportRefreshing,
        reportRefreshStatus,
        enrichingResearchCode,
      },
      resources: {
        researchResults,
        stockMeta,
        indColor,
        tradeCapture,
        createDefaultReviewForm,
      },
      controls: {
        exitOverview,
        switchPortfolio,
        setShowReversal,
        setReviewingEvent,
        updateReversal,
        setScanQuery,
        setScanFilter,
        setSortBy,
        setExpandedStock,
        setRelayPlanExpanded,
        setFilterType,
        setCatalystFilter,
        setDailyExpanded,
        setStressResult,
        setTab,
        setExpandedNews,
        setResearchResults,
        setReviewForm,
      },
      actions: {
        updateTargetPrice,
        updateAlert,
        handleWatchlistUpsert,
        handleWatchlistDelete,
        formatEventStockOutcomeLine,
        runDailyAnalysis,
        runStressTest,
        refreshAnalystReports,
        runResearch,
        enrichResearchToDossier,
        submitReview,
        cancelReview,
      },
    })
  )

  return {
    copyWeeklyReport,
    backupFileInputRef,
    exportLocalBackup,
    importLocalBackup,
    portfolioPanelsData,
    portfolioPanelsActions,
  }
}
