#!/usr/bin/env bash
# Build 1e — production catalog read-only fixture generator（明確 opt-in）
#
#   BSR_SLICE_ALLOW_PROD_READ=1 bash scripts/gen-bsr-slice-fixture.sh --project-ref <ref>
#
# 規則（Build 1e Final Plan v3 §1c / §5A）：
#   - 未設 BSR_SLICE_ALLOW_PROD_READ=1 直接拒絕。
#   - 只讀 catalog metadata 與 pg_get_*def；不查任何業務表 row、不讀 secret、
#     不碰 auth / storage。
#   - 先把 production actual 對 pinned expected 做 diff；不符即印 exact diff 並停，
#     絕不自動採用新值。
#   - 本腳本永遠不寫入 bsr_slice_expected.tsv（CI 以 grep 斷言）。
#   - credential / DB URL 只從 secret env 讀取，不輸出、不寫檔。
#     provenance 只允許 project ref / timestamp / generator version / object hashes。

set -euo pipefail

GENERATOR_VERSION="1e.v3"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FIXTURES="$ROOT/supabase/tests/fixtures"
SCHEMA_OUT="$FIXTURES/bsr_slice_schema.sql"
FUNCTIONS_OUT="$FIXTURES/bsr_slice_functions.sql"

die() { echo "FATAL: $*" >&2; exit 1; }

[ "${BSR_SLICE_ALLOW_PROD_READ:-0}" = "1" ] \
  || die "refusing to read production: set BSR_SLICE_ALLOW_PROD_READ=1 to opt in"

PROJECT_REF=""
while [ $# -gt 0 ]; do
  case "$1" in
    --project-ref) PROJECT_REF="${2:-}"; shift 2 ;;
    *) die "unknown arg: $1" ;;
  esac
done
[ -n "$PROJECT_REF" ] || die "--project-ref is required"

# ---- guard：host 必須是 managed PG host 且 project ref 相符 -------------------
[ -n "${PGHOST:-}" ] || die "PGHOST not set (credentials must come from secret env)"
# project ref 可能出現在 host 或 pooler user（postgres.<ref>）
case "${PGHOST}|${PGUSER:-}" in
  *"$PROJECT_REF"*) : ;;
  *) die "connection does not match --project-ref (host/user redacted)" ;;
esac
case "$PGHOST" in
  *.supabase.co|*.supabase.com|*.pooler.supabase.com) : ;;
  *) die "PGHOST is not a managed PG host (host redacted)" ;;
esac

command -v psql >/dev/null || die "psql not found"

PROD_PSQL="$(mktemp /tmp/bsr-prodpsql-XXXXXX)"
cat > "$PROD_PSQL" <<'W'
#!/usr/bin/env bash
exec psql "$@"
W
chmod +x "$PROD_PSQL"
trap 'rm -f "$PROD_PSQL"' EXIT

export SLICE_PSQL="$PROD_PSQL"
BSR_SLICE_LIB=1 source "$ROOT/scripts/bsr-slice-verify.sh"

# ---- 0) 自我約束：本腳本不得寫 expected.tsv ---------------------------------
if grep -nE '>[[:space:]]*.*bsr_slice_expected\.tsv|tee .*bsr_slice_expected\.tsv' "$0" | grep -v '^[0-9]*:#' | grep -q .; then
  die "self-check failed: generator must never write bsr_slice_expected.tsv"
fi

echo "==> [1/4] production closure check (read-only)"
bash "$ROOT/scripts/bsr-slice-closure-check.sh" --scope prod || die "production closure check failed"

echo "==> [2/4] diff production actual vs pinned expected"
if slice_compare_expected production; then
  echo "    OK: production 與 pinned baseline 完全一致"
else
  die "production catalog drifted from pinned baseline — 不產生 fixture、不自動更新 baseline。
更新 bsr_slice_expected.tsv 只能是另一次人工審核 + 新批准。"
fi

mkdir -p "$FIXTURES"
NOW_UTC="$(date -u +%Y-%m-%dT%H:%MZ)"
NOW_TPE="$(TZ=Asia/Taipei date +'%Y-%m-%d %H:%M')"

echo "==> [3/4] emit $SCHEMA_OUT"
RELS_SQL="$(printf "'%s'," $(printf '%s\n' "${BSR_SLICE_RELATIONS[@]}" | sort -u) | sed 's/,$//')"
{
  echo "-- GENERATED by scripts/gen-bsr-slice-fixture.sh (version $GENERATOR_VERSION)"
  echo "-- provenance: project_ref=$PROJECT_REF generated_at=${NOW_UTC} (${NOW_TPE} Asia/Taipei)"
  echo "-- 受測 dependency slice，非完整 current schema。無 rows、無 secrets、無 RLS policy。"
  echo "-- 簡化項見 Build 1e Final Plan v3 §4。"
  echo "SET client_min_messages = warning;"
  echo "CREATE SCHEMA IF NOT EXISTS public;"
  psql -X -A -t -q -v ON_ERROR_STOP=1 <<SQL
WITH rels AS (
  SELECT c.oid, c.relname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname='public' AND c.relkind='r' AND c.relname IN ($RELS_SQL)
),
cols AS (
  SELECT r.relname, string_agg('  '||quote_ident(a.attname)||' '||format_type(a.atttypid,a.atttypmod)||
      coalesce(' DEFAULT '||pg_get_expr(d.adbin,d.adrelid),'')||
      CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END, E',\n' ORDER BY a.attnum) AS body
  FROM rels r JOIN pg_attribute a ON a.attrelid=r.oid AND a.attnum>0 AND NOT a.attisdropped
  LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
  GROUP BY r.relname
)
SELECT 'CREATE TABLE public.'||quote_ident(relname)||E' (\n'||body||E'\n);'
FROM cols ORDER BY relname;
SQL
  # constraints（p/u/c + closure 內 FK）
  psql -X -A -t -q -v ON_ERROR_STOP=1 <<SQL
WITH rels AS (
  SELECT c.oid, c.relname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname='public' AND c.relkind='r' AND c.relname IN ($RELS_SQL)
)
SELECT 'ALTER TABLE public.'||quote_ident(r.relname)||' ADD CONSTRAINT '||quote_ident(co.conname)||' '||pg_get_constraintdef(co.oid)||';'
FROM rels r JOIN pg_constraint co ON co.conrelid=r.oid
WHERE co.contype IN ('p','u','c') OR (co.contype='f' AND co.confrelid IN (SELECT oid FROM rels))
ORDER BY r.relname, co.conname;
SQL
  # unique indexes（排除 constraint 自帶的）
  psql -X -A -t -q -v ON_ERROR_STOP=1 <<SQL
WITH rels AS (
  SELECT c.oid, c.relname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname='public' AND c.relkind='r' AND c.relname IN ($RELS_SQL)
)
SELECT pg_get_indexdef(i.indexrelid)||';'
FROM rels r JOIN pg_index i ON i.indrelid=r.oid
JOIN pg_class ic ON ic.oid=i.indexrelid
WHERE i.indisunique
  AND NOT EXISTS (SELECT 1 FROM pg_constraint co WHERE co.conindid=i.indexrelid)
ORDER BY ic.relname;
SQL
} > "$SCHEMA_OUT"

echo "==> [4/4] emit $FUNCTIONS_OUT"
FNS_SQL="$(printf "'%s'," "${BSR_SLICE_FUNCTIONS[@]}" | sed 's/,$//')"
{
  echo "-- GENERATED by scripts/gen-bsr-slice-fixture.sh (version $GENERATOR_VERSION)"
  echo "-- provenance: project_ref=$PROJECT_REF generated_at=${NOW_UTC} (${NOW_TPE} Asia/Taipei)"
  echo "-- function body 為 production 原文（pg_get_functiondef），不得手改。"
  echo "SET client_min_messages = warning;"
  psql -X -A -t -q -v ON_ERROR_STOP=1 <<SQL
SELECT pg_get_functiondef(p.oid)||E';\n'
FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
WHERE n.nspname='public' AND p.proname IN ($FNS_SQL)
ORDER BY p.proname;
SQL
  echo "-- 保留的 trigger binding（唯一一個）"
  psql -X -A -t -q -v ON_ERROR_STOP=1 <<SQL
SELECT pg_get_triggerdef(t.oid)||';'
FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND NOT t.tgisinternal AND t.tgname='${BSR_SLICE_KEPT_TRIGGER}';
SQL
} > "$FUNCTIONS_OUT"

echo "GENERATE OK"
echo "  schema:    $SCHEMA_OUT  (sha256=$(sha256sum "$SCHEMA_OUT" | cut -d' ' -f1))"
echo "  functions: $FUNCTIONS_OUT  (sha256=$(sha256sum "$FUNCTIONS_OUT" | cut -d' ' -f1))"
