#!/usr/bin/env bash
# Build2 P4 — market-batch fulfill E2E fixture generator（ephemeral-only，read-only 取樣）
#
#   BSR_E2E_ALLOW_PROD_READ=1 bash scripts/gen-bsr-e2e-fixture.sh
#
# 規則：
#   - 只讀 catalog（pg_dump --schema-only / pg_get_functiondef）。不讀任何業務資料列。
#   - 「不碰」Build1f pinned slice（bsr_slice_schema.sql / bsr_slice_functions.sql）。
#     本腳本只產生額外的 delta fixture：bsr_e2e_schema.sql / bsr_e2e_functions.sql，
#     使用方式為「先 load-slice，再載入本 delta」。
#   - 產出檔中不得含 OWNER / GRANT / POLICY / RLS / TRIGGER（ephemeral 無 production roles）。
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_SCHEMA="$ROOT/supabase/tests/fixtures/bsr_e2e_schema.sql"
OUT_FUNCS="$ROOT/supabase/tests/fixtures/bsr_e2e_functions.sql"

die() { echo "FATAL: $*" >&2; exit 1; }
[ "${BSR_E2E_ALLOW_PROD_READ:-0}" = "1" ] || die "set BSR_E2E_ALLOW_PROD_READ=1 to opt in（只讀 catalog）"
[ -n "${PGHOST:-}" ] || die "PGHOST not set"

# slice 已含：checkup_storage chips_prefetch_targets data_source_refresh_logs expert_signals
#             finmind_quota_pools stock_names system_kill_switches trade_records
#             tw_bsr_sync_config tw_bsr_sync_queue tw_chip_fact tw_market_holidays
DELTA_TABLES=(
  bsr_coverage_daily
  daily_price_snapshots
  tw_bsr_daily
  tw_bsr_daily_snapshot_status
  tw_bsr_fetch_failures
  tw_bsr_upstream_probe
  tw_chips_rollup
  tw_institutional_daily
  finmind_quota_ledger
  finmind_inflight_requests
  finmind_upstream_quota
  price_quota_pools
  price_quota_ledger
  experts
  user_roles
)

# slice 已含函式：bsr_backlog_metrics bsr_get_degrade_state bsr_recovery_budget check_kill_switch
#                 checkup_prefetch_universe expected_latest_bsr_date recover_quota_failed_bsr_jobs
#                 tw_bsr_eligibility tw_bsr_sync_queue_touch_updated claim_bsr_queue_jobs
DELTA_FUNCS=(
  materialize_bsr_daily_from_fact
  rebuild_bsr_rollup
  bsr_snapshot_mark
  bsr_snapshot_fulfill_jobs
  bsr_snapshot_claim
  refresh_bsr_coverage_daily
  reconcile_snapshot
  ensure_bsr_queued
  ensure_bsr_window
  is_tw_trading_day
  tw_prev_trading_day
  finmind_admit
  finmind_admit_v2
  finmind_pool_reset
  finmind_pool_set_budget
  finmind_inflight_acquire
  finmind_inflight_release
  chips_prefetch_targets_touch
  enqueue_chips_prefetch_gaps
  detect_chip_gap_jobs
  tw_trading_days
  detect_institutional_gap_jobs
  recover_stale_bsr_queue_jobs
  enqueue_bsr_backfill
  has_role
)

DELTA_TYPES=(
  app_role
  expert_role
)

echo "==> dumping delta enum types (catalog read-only)"
{
  for ty in "${DELTA_TYPES[@]}"; do
    psql -At -v ON_ERROR_STOP=1 -c "
      select 'CREATE TYPE public.' || t.typname || ' AS ENUM ('
             || string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder)
             || ');'
        from pg_type t
        join pg_namespace n on n.oid = t.typnamespace
        join pg_enum e on e.enumtypid = t.oid
       where n.nspname='public' and t.typname = '$ty'
       group by t.typname"
  done
} > "$OUT_SCHEMA.types.body"
{
  echo "-- ephemeral-only auth stub：user_roles / experts 具 auth.users FK，載入前必須先存在。"
  echo "CREATE SCHEMA IF NOT EXISTS auth;"
  echo "CREATE TABLE IF NOT EXISTS auth.users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text);"
  cat "$OUT_SCHEMA.types.body"
} > "$OUT_SCHEMA.types"
rm -f "$OUT_SCHEMA.types.body"

echo "==> dumping delta table DDL (schema-only, read-only)"
args=()
for t in "${DELTA_TABLES[@]}"; do args+=(-t "public.$t"); done
pg_dump --schema-only --no-owner --no-privileges --no-comments --no-publications \
  --no-subscriptions --no-security-labels --no-tablespaces "${args[@]}" \
  | awk '
      /^CREATE TRIGGER/,/;$/ { next }
      /^CREATE POLICY/,/;$/ { next }
      /ROW LEVEL SECURITY/ { next }
      /^GRANT |^REVOKE |^ALTER .* OWNER TO / { next }
      /^SET |^SELECT pg_catalog.set_config/ { next }
      { print }
  ' > "$OUT_SCHEMA.body"
cat "$OUT_SCHEMA.types" "$OUT_SCHEMA.body" > "$OUT_SCHEMA"
rm -f "$OUT_SCHEMA.types" "$OUT_SCHEMA.body"

echo "==> dumping delta function definitions"
{
  echo "-- generated by scripts/gen-bsr-e2e-fixture.sh（ephemeral-only；不可用於 production）"
  echo "-- 載入順序無關：SQL-language 函式互相引用時關閉 body 驗證（僅影響載入期，不改函式定義）"
  echo "SET check_function_bodies = off;"
  for f in "${DELTA_FUNCS[@]}"; do
    out="$(psql -At -v ON_ERROR_STOP=1 -c "
      select string_agg(pg_get_functiondef(p.oid), E';\n\n' order by p.oid) || ';'
        from pg_proc p join pg_namespace n on n.oid = p.pronamespace
       where n.nspname='public' and p.proname = '$f'")" \
      || die "dump failed for function $f（連線或權限問題；fixture 不得部分寫入）"
    [ -n "$out" ] || die "empty definition for function $f（production 缺此函式？）"
    printf '%s\n' "$out"
  done
} > "$OUT_FUNCS.part"
for f in "${DELTA_FUNCS[@]}"; do
  grep -q "FUNCTION public.$f(" "$OUT_FUNCS.part" \
    || { rm -f "$OUT_FUNCS.part"; die "completeness check failed: $f 不在輸出中"; }
done
mv "$OUT_FUNCS.part" "$OUT_FUNCS"

grep -qiE '^(GRANT|REVOKE)|OWNER TO|CREATE POLICY|CREATE TRIGGER' "$OUT_SCHEMA" \
  && die "fixture 內含禁止語句（GRANT/OWNER/POLICY/TRIGGER）"

echo "SCHEMA: $(wc -l < "$OUT_SCHEMA") lines  |  FUNCS: $(wc -l < "$OUT_FUNCS") lines"
echo "sha256(schema)=$(sha256sum "$OUT_SCHEMA" | cut -d' ' -f1)"
echo "sha256(funcs) =$(sha256sum "$OUT_FUNCS" | cut -d' ' -f1)"
echo "GEN-E2E-FIXTURE OK"
