CREATE TABLE IF NOT EXISTS public.edge_boot_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fn text NOT NULL,
  boot_at timestamptz NOT NULL DEFAULT now(),
  region text,
  deployment_id text
);

CREATE INDEX IF NOT EXISTS edge_boot_events_fn_boot_at_idx
  ON public.edge_boot_events (fn, boot_at DESC);
CREATE INDEX IF NOT EXISTS edge_boot_events_boot_at_idx
  ON public.edge_boot_events (boot_at DESC);

GRANT SELECT ON public.edge_boot_events TO authenticated;
GRANT ALL ON public.edge_boot_events TO service_role;

ALTER TABLE public.edge_boot_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "company_admin can read edge boot events"
  ON public.edge_boot_events
  FOR SELECT
  TO authenticated
  USING (public.has_role(auth.uid(), 'company_admin'));